<a href="https://colab.research.google.com/github/shonbo1221-collab/DRL_FinalProjectProposal/blob/main/train_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TWSE PPO + SMC Training Notebook

This notebook version mirrors `train_pipeline.py` and splits the training flow into editable steps.

## 1. Imports

### Colab dependency setup

Run this cell once after starting or restarting a Google Colab runtime.

In [5]:
%pip install -q stable-baselines3==2.8.0 gymnasium==1.2.3 yfinance==1.3.0

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 187.5/187.5 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 952.1/952.1 kB 23.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 2.2 MB/s eta 0:00:00

In [6]:
import os
from dataclasses import dataclass

import gymnasium as gym
import numpy as np
import pandas as pd
import torch
import yfinance as yf
from gymnasium import spaces
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

## 2. Shared Trading Module

The definitions below are embedded from `twse_pipeline_common.py` so this notebook can run without importing any local project module.

In [7]:
BROKERAGE_FEE = 0.001425 * 0.6
PRICE_LIMIT_UP = 1.10
SHARPE_WINDOW = 20
EPS = 1e-8


@dataclass(frozen=True)
class ModelConfig:
    name: str
    tickers: tuple[str, ...]
    model_path: str
    mode: str


PAIR_CONFIG = ModelConfig(
    name="pair_0050_2330",
    tickers=("0050.TW", "2330.TW"),
    model_path="model/save_colab/ppo_model_pair.zip",
    mode="pair",
)

BASKET_CONFIG = ModelConfig(
    name="basket_0050_2330_2412",
    tickers=("0050.TW", "2330.TW", "2412.TW"),
    model_path="model/save_colab/ppo_model_basket.zip",
    mode="basket",
)

SELL_TAX = {
    "0050.TW": 0.001,
    "2330.TW": 0.003,
    "2412.TW": 0.003,
}

In [8]:
def download_ohlcv(tickers, start_date, end_date):
    frames = {}
    for ticker in tickers:
        df = yf.download(ticker, start=start_date, end=end_date, auto_adjust=False, progress=False)
        if df.empty:
            raise ValueError(f"No data downloaded for {ticker}")
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)
        df = df.reset_index()
        df = df.rename(
            columns={
                "Date": "date",
                "Open": "open",
                "High": "high",
                "Low": "low",
                "Close": "close",
                "Adj Close": "adj_close",
                "Volume": "volume",
            }
        )
        required = ["date", "open", "high", "low", "close", "volume"]
        frames[ticker] = df[required].dropna().reset_index(drop=True)
    return frames


def add_smc_features(df):
    out = df.copy()
    high_20 = out["high"].rolling(20).max()
    low_20 = out["low"].rolling(20).min()
    dealing_range = (high_20 - low_20).replace(0, np.nan)
    out["PD_Pos"] = ((out["close"] - low_20) / dealing_range).clip(0.0, 1.0)

    ret_3d = out["close"].pct_change(3)
    bearish_candle = out["close"] < out["open"]
    ob_level = np.nan
    ob_levels = []
    for i in range(len(out)):
        if i >= 3 and ret_3d.iloc[i] > 0.03:
            start = max(0, i - 20)
            for j in range(i - 3, start - 1, -1):
                if bearish_candle.iloc[j]:
                    ob_level = out["high"].iloc[j]
                    break
        ob_levels.append(ob_level)
    out["ob_level"] = pd.Series(ob_levels, index=out.index).ffill()
    out["OB_Dist"] = ((out["close"] - out["ob_level"]) / out["close"]).replace([np.inf, -np.inf], np.nan)

    bullish_fvg = out["low"] > out["high"].shift(2)
    bearish_fvg = out["high"] < out["low"].shift(2)
    bull_low = out["high"].shift(2)
    bull_high = out["low"]
    bear_low = out["high"]
    bear_high = out["low"].shift(2)

    unfilled = np.zeros(len(out), dtype=np.float32)
    active_gaps = []
    for i in range(len(out)):
        still_active = []
        for gap in active_gaps:
            touches_gap = out["low"].iloc[i] <= gap["high"] and out["high"].iloc[i] >= gap["low"]
            if not touches_gap:
                still_active.append(gap)
        active_gaps = still_active

        if bullish_fvg.iloc[i]:
            active_gaps.append({"low": bull_low.iloc[i], "high": bull_high.iloc[i], "direction": "bull"})
        if bearish_fvg.iloc[i]:
            active_gaps.append({"low": bear_low.iloc[i], "high": bear_high.iloc[i], "direction": "bear"})

        unfilled[i] = 1.0 if active_gaps else 0.0
    out["FVG_Signal"] = unfilled

    out[["PD_Pos", "OB_Dist", "FVG_Signal"]] = out[["PD_Pos", "OB_Dist", "FVG_Signal"]].fillna(
        {"PD_Pos": 0.5, "OB_Dist": 0.0, "FVG_Signal": 0.0}
    )
    return out

In [9]:
def build_feature_frame(raw_frames, config):
    feature_frames = []
    for ticker in config.tickers:
        df = add_smc_features(raw_frames[ticker])
        prefix = ticker.replace(".", "_")
        cols = ["date", "open", "high", "low", "close", "volume", "PD_Pos", "OB_Dist", "FVG_Signal"]
        renamed = df[cols].rename(columns={col: f"{prefix}_{col}" for col in cols if col != "date"})
        feature_frames.append(renamed)

    merged = feature_frames[0]
    for frame in feature_frames[1:]:
        merged = pd.merge(merged, frame, on="date", how="inner")

    pairs = [(config.tickers[0], config.tickers[1])] if config.mode == "pair" else [
        (config.tickers[i], config.tickers[j])
        for i in range(len(config.tickers))
        for j in range(i + 1, len(config.tickers))
    ]
    for left_ticker, right_ticker in pairs:
        left = left_ticker.replace(".", "_")
        right = right_ticker.replace(".", "_")
        col = f"Spread_ZScore_{left}_{right}"
        spread = np.log(merged[f"{left}_close"]) - np.log(merged[f"{right}_close"])
        mean = spread.rolling(20).mean()
        std = spread.rolling(20).std().replace(0, np.nan)
        merged[col] = ((spread - mean) / std).replace([np.inf, -np.inf], np.nan).fillna(0.0)

    if config.mode == "pair":
        left = config.tickers[0].replace(".", "_")
        right = config.tickers[1].replace(".", "_")
        merged["Spread_ZScore"] = merged[f"Spread_ZScore_{left}_{right}"]
    else:
        merged["Spread_ZScore"] = 0.0

    return merged.dropna().reset_index(drop=True)

In [10]:
class TWTradingEnv(gym.Env):
    metadata = {"render_modes": ["human"]}

    def __init__(self, feature_df, config, initial_balance=1_000_000.0, max_position=0.95):
        super().__init__()
        self.df = feature_df.reset_index(drop=True)
        self.config = config
        self.initial_balance = float(initial_balance)
        self.max_position = float(max_position)
        self.asset_prefixes = [ticker.replace(".", "_") for ticker in config.tickers]
        self.feature_cols = self._make_feature_cols()

        obs_dim = len(self.feature_cols) + len(self.config.tickers) + 1
        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(obs_dim,), dtype=np.float32)
        action_dim = len(self.config.tickers) if self.config.mode == "basket" else 1
        self.action_space = spaces.Box(low=-1.0, high=1.0, shape=(action_dim,), dtype=np.float32)

    def _make_feature_cols(self):
        cols = []
        for prefix in self.asset_prefixes:
            cols.extend([f"{prefix}_PD_Pos", f"{prefix}_OB_Dist", f"{prefix}_FVG_Signal"])
        if self.config.mode == "pair":
            cols.append("Spread_ZScore")
        elif self.config.mode == "basket":
            cols.extend([col for col in self.df.columns if col.startswith("Spread_ZScore_")])
        return cols

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.current_step = 0
        self.cash = self.initial_balance
        self.shares = np.zeros(len(self.config.tickers), dtype=np.float64)
        self.net_worth = self.initial_balance
        self.max_net_worth = self.initial_balance
        self.prev_drawdown = 0.0
        self.portfolio_returns = []
        self.history = []
        return self._get_obs(), {}

    def _prices(self, step=None):
        idx = self.current_step if step is None else step
        return np.array([self.df.loc[idx, f"{prefix}_close"] for prefix in self.asset_prefixes], dtype=np.float64)

    def _prev_closes(self):
        prev_step = max(0, self.current_step - 1)
        return np.array([self.df.loc[prev_step, f"{prefix}_close"] for prefix in self.asset_prefixes], dtype=np.float64)

    def _get_weights(self, prices=None, net_worth=None):
        prices = self._prices() if prices is None else prices
        net_worth = self.net_worth if net_worth is None else net_worth
        if net_worth <= 0:
            return np.zeros(len(self.config.tickers), dtype=np.float64)
        return (self.shares * prices) / net_worth

    def _get_obs(self):
        market_features = self.df.loc[self.current_step, self.feature_cols].to_numpy(dtype=np.float32)
        prices = self._prices()
        net_worth = self.cash + float(np.dot(self.shares, prices))
        weights = self._get_weights(prices, net_worth).astype(np.float32)
        cash_ratio = np.array([self.cash / max(net_worth, EPS)], dtype=np.float32)
        return np.concatenate([market_features, weights, cash_ratio]).astype(np.float32)

    def _target_weights(self, raw_action):
        action_array = np.asarray(raw_action, dtype=np.float64).reshape(-1)
        if self.config.mode == "pair":
            action = float(np.clip(action_array[0], -1.0, 1.0))
            weights = np.zeros(2, dtype=np.float64)
            if action >= 0:
                weights[0] = action * self.max_position
            else:
                weights[1] = -action * self.max_position
            return weights

        if self.config.mode == "basket":
            scores = np.clip(action_array[: len(self.config.tickers)], 0.0, 1.0)
            if scores.sum() <= EPS:
                return np.zeros(len(self.config.tickers), dtype=np.float64)
            return (scores / scores.sum()) * self.max_position

        action = float(np.clip(action_array[0], -1.0, 1.0))
        return np.array([max(0.0, action) * self.max_position], dtype=np.float64)

    def _execute_rebalance(self, target_weights, prices):
        prev_prices = self._prev_closes()
        net_worth_before_trade = self.cash + float(np.dot(self.shares, prices))
        current_values = self.shares * prices
        target_values = target_weights * net_worth_before_trade
        value_diffs = target_values - current_values
        transaction_cost = 0.0
        failed_orders = 0

        for idx, value_diff in enumerate(value_diffs):
            ticker = self.config.tickers[idx]
            price = prices[idx]
            limit_up = prev_prices[idx] * PRICE_LIMIT_UP

            if abs(value_diff) > EPS and price >= limit_up:
                failed_orders += 1
                continue

            if value_diff > 0:
                buy_value = min(value_diff, max(0.0, self.cash / (1.0 + BROKERAGE_FEE)))
                fee = buy_value * BROKERAGE_FEE
                self.cash -= buy_value + fee
                self.shares[idx] += buy_value / price
                transaction_cost += fee
            elif value_diff < 0:
                sell_value = min(-value_diff, self.shares[idx] * price)
                fee = sell_value * BROKERAGE_FEE
                tax = sell_value * SELL_TAX[ticker]
                self.cash += sell_value - fee - tax
                self.shares[idx] -= sell_value / price
                transaction_cost += fee + tax

        return transaction_cost, failed_orders

    def step(self, action):
        raw_action_array = np.asarray(action, dtype=np.float64).reshape(-1)
        raw_action = float(raw_action_array[0])
        prices = self._prices()
        prev_net_worth = self.net_worth
        target_weights = self._target_weights(raw_action_array)
        transaction_cost, failed_orders = self._execute_rebalance(target_weights, prices)

        self.net_worth = self.cash + float(np.dot(self.shares, prices))
        pnl = self.net_worth - prev_net_worth
        pnl_rate = pnl / max(prev_net_worth, EPS)
        self.portfolio_returns.append(pnl_rate)

        recent = np.array(self.portfolio_returns[-SHARPE_WINDOW:], dtype=np.float64)
        if len(recent) > 1 and np.std(recent) > EPS:
            sharpe_adjustment = max(0.0, np.mean(recent) / (np.std(recent) + EPS) * np.sqrt(252))
        else:
            sharpe_adjustment = 1.0

        self.max_net_worth = max(self.max_net_worth, self.net_worth)
        drawdown = (self.max_net_worth - self.net_worth) / max(self.max_net_worth, EPS)
        drawdown_penalty = max(0.0, drawdown - self.prev_drawdown)
        self.prev_drawdown = drawdown

        cost_rate = transaction_cost / max(prev_net_worth, EPS)
        reward = (pnl_rate * sharpe_adjustment) - cost_rate - (2.0 * drawdown_penalty)

        weights = self._get_weights(prices, self.net_worth)
        self.history.append(
            {
                "date": self.df.loc[self.current_step, "date"],
                "raw_action": raw_action,
                "net_worth": self.net_worth,
                "pnl": pnl,
                "pnl_rate": pnl_rate,
                "transaction_cost": transaction_cost,
                "drawdown": drawdown,
                "reward": reward,
                "failed_orders": failed_orders,
                **{f"raw_action_{ticker}": raw_action_array[i] for i, ticker in enumerate(self.config.tickers) if i < len(raw_action_array)},
                **{f"weight_{ticker}": weights[i] for i, ticker in enumerate(self.config.tickers)},
            }
        )

        self.current_step += 1
        terminated = self.current_step >= len(self.df) - 1
        truncated = False
        obs = np.zeros(self.observation_space.shape, dtype=np.float32) if terminated else self._get_obs()
        info = {"net_worth": self.net_worth, "drawdown": drawdown, "transaction_cost": transaction_cost}
        return obs, float(reward), terminated, truncated, info

In [11]:
def calculate_metrics(history_df, initial_balance=1_000_000.0):
    if history_df.empty:
        return {"cumulative_return": 0.0, "sharpe_ratio": 0.0, "max_drawdown": 0.0}
    net_worth = history_df["net_worth"].astype(float)
    cumulative_return = (net_worth.iloc[-1] / initial_balance) - 1.0
    returns = net_worth.pct_change().dropna()
    sharpe = 0.0
    if len(returns) > 1 and returns.std() > EPS:
        sharpe = (returns.mean() / returns.std()) * np.sqrt(252)
    roll_max = net_worth.cummax()
    drawdown = (net_worth - roll_max) / roll_max
    return {
        "cumulative_return": float(cumulative_return),
        "sharpe_ratio": float(sharpe),
        "max_drawdown": float(drawdown.min()),
    }


def prepare_dataset(config, start_date, end_date):
    raw_frames = download_ohlcv(config.tickers, start_date, end_date)
    return build_feature_frame(raw_frames, config)


def ensure_model_dir(path):
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)

## 3. Training Settings

Adjust these values before running the training cells. The original script uses `500_000` timesteps and `cuda:0`.

In [12]:
TRAIN_START = "2018-01-01"
TRAIN_END = "2024-12-31"
TOTAL_TIMESTEPS = 500_000
INITIAL_BALANCE = 1_000_000.0
DEVICE = "cuda:0"

# Train both models by default, same as train_pipeline.py.
# You can change this to [PAIR_CONFIG] or [BASKET_CONFIG] for a shorter run.
CONFIGS_TO_TRAIN = [PAIR_CONFIG, BASKET_CONFIG]

## 4. CUDA Check

The original training script requires a CUDA GPU. Run this cell before preparing data or training.

In [14]:
def require_cuda():
    # Use global DEVICE to modify it if necessary
    global DEVICE
    if not torch.cuda.is_available():
        if DEVICE.startswith("cuda"):
            print("Warning: CUDA GPU is not available. Switching to CPU for training.")
            DEVICE = "cpu"
        else: # If DEVICE was already 'cpu' or something else, and CUDA is not available, just proceed.
            pass

    if DEVICE.startswith("cuda"):
        torch.set_float32_matmul_precision("high")
        torch.backends.cudnn.benchmark = True


require_cuda()
print(f"Using fixed training device: {DEVICE}")
if DEVICE.startswith("cuda"):
    print(f"CUDA device: {torch.cuda.get_device_name(0)}")
else:
    print("Running on CPU.")

Warning: CUDA GPU is not available. Switching to CPU for training.
Using fixed training device: cpu
Running on CPU.

## 5. Download Market Data

This cell downloads OHLCV data from yfinance for the training period. The raw data is kept in memory so later cells can build features without downloading again.

In [15]:
raw_market_data = {}

for config in CONFIGS_TO_TRAIN:
    print(f"\n=== Downloading data for {config.name} ===")
    print(f"Tickers: {', '.join(config.tickers)}")
    raw_market_data[config.name] = download_ohlcv(config.tickers, TRAIN_START, TRAIN_END)
    for ticker, df in raw_market_data[config.name].items():
        print(f"{ticker}: {len(df)} rows, {df['date'].min().date()} to {df['date'].max().date()}")

=== Downloading data for pair_0050_2330 ===
Tickers: 0050.TW, 2330.TW
0050.TW: 1700 rows, 2018-01-02 to 2024-12-30
2330.TW: 1700 rows, 2018-01-02 to 2024-12-30

=== Downloading data for basket_0050_2330_2412 ===
Tickers: 0050.TW, 2330.TW, 2412.TW
0050.TW: 1700 rows, 2018-01-02 to 2024-12-30
2330.TW: 1700 rows, 2018-01-02 to 2024-12-30
2412.TW: 1700 rows, 2018-01-02 to 2024-12-30

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

## 6. Build Feature Frames

This converts the raw OHLCV data into the SMC and spread z-score features used by the PPO environment.

In [16]:
feature_data = {}

for config in CONFIGS_TO_TRAIN:
    feature_df = build_feature_frame(raw_market_data[config.name], config)
    feature_data[config.name] = feature_df
    print(f"{config.name}: {len(feature_df)} feature rows, {len(feature_df.columns)} columns")

feature_data[CONFIGS_TO_TRAIN[0].name].head()

pair_0050_2330: 1700 feature rows, 19 columns

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

basket_0050_2330_2412: 1700 feature rows, 29 columns

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Price,date,0050_TW_open,0050_TW_high,0050_TW_low,0050_TW_close,0050_TW_volume,0050_TW_PD_Pos,0050_TW_OB_Dist,0050_TW_FVG_Signal,2330_TW_open,2330_TW_high,2330_TW_low,2330_TW_close,2330_TW_volume,2330_TW_PD_Pos,2330_TW_OB_Dist,2330_TW_FVG_Signal,Spread_ZScore_0050_TW_2330_TW,Spread_ZScore
0,2018-01-02,20.537500,20.650000,20.537500,20.6500,14452796,0.5,0.0,0.0,231.5,232.5,231.0,232.5,18055269,0.5,0.0,0.0,0.0,0.0
1,2018-01-03,20.737499,20.862499,20.737499,20.8375,28785748,0.5,0.0,0.0,236.0,238.0,235.5,237.0,29308091,0.5,0.0,0.0,0.0,0.0
2,2018-01-04,20.875000,20.912500,20.799999,20.8750,22510260,0.5,0.0,1.0,240.0,240.0,236.5,239.5,29096613,0.5,0.0,1.0,0.0,0.0
3,2018-01-05,20.875000,20.950001,20.825001,20.9375,30467184,0.5,0.0,1.0,240.0,240.0,238.0,240.0,22438255,0.5,0.0,1.0,0.0,0.0
4,2018-01-08,20.950001,21.037500,20.924999,21.0250,20758444,0.5,0.0,1.0,242.0,242.5,240.5,242.0,20233692,0.5,0.0,1.0,0.0,0.0

## 7. Training Function

In [17]:
def train_one_model(config):
    print(f"\n=== Training {config.name} ===")
    print(f"Tickers: {', '.join(config.tickers)}")
    print(f"Period: {TRAIN_START} to {TRAIN_END}")

    if config.name in feature_data:
        feature_df = feature_data[config.name]
    else:
        raw_frames = download_ohlcv(config.tickers, TRAIN_START, TRAIN_END)
        feature_df = build_feature_frame(raw_frames, config)
    print(f"Feature rows: {len(feature_df)}")

    env = DummyVecEnv(
        [
            lambda: TWTradingEnv(
                feature_df=feature_df,
                config=config,
                initial_balance=INITIAL_BALANCE,
            )
        ]
    )

    policy_kwargs = dict(net_arch=dict(pi=[128, 128], vf=[128, 128]))
    model = PPO(
        "MlpPolicy",
        env,
        learning_rate=2e-4,
        n_steps=2048,
        batch_size=128,
        n_epochs=10,
        gamma=0.99,
        gae_lambda=0.95,
        clip_range=0.2,
        ent_coef=0.005,
        target_kl=0.03,
        policy_kwargs=policy_kwargs,
        verbose=1,
        device=DEVICE,
    )

    model.learn(total_timesteps=TOTAL_TIMESTEPS)
    ensure_model_dir(config.model_path)
    model.save(config.model_path)
    print(f"Saved model: {config.model_path}")
    return model

## 8. Start Training

This cell may take a long time. It saves models to the paths defined in `PAIR_CONFIG` and `BASKET_CONFIG`.

In [18]:
trained_models = {}

for config in CONFIGS_TO_TRAIN:
    trained_models[config.name] = train_one_model(config)

trained_models.keys()

=== Training pair_0050_2330 ===
Tickers: 0050.TW, 2330.TW
Period: 2018-01-01 to 2024-12-31
Feature rows: 1700
Using cpu device
-----------------------------
| time/              |      |
|    fps             | 552  |
|    iterations      | 1    |
|    time_elapsed    | 3    |
|    total_timesteps | 2048 |
-----------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 470          |
|    iterations           | 2            |
|    time_elapsed         | 8            |
|    total_timesteps      | 4096         |
| train/                  |              |
|    approx_kl            | 0.0035420216 |
|    clip_fraction        | 0.0241       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.42        |
|    explained_variance   | -1.28        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00128     |
|    n_updates            | 10           |
|    policy_gradient_loss | -0.00167     |
|    std                  | 1            |
|    value_loss           | 0.00742      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 480          |
|    iterations           | 3            |
|    time_elapsed         | 12           |
|    total_timesteps      | 6144         |
| train/                  |              |
|    approx_kl            | 0.0024858934 |
|    clip_fraction        | 0.0151       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.43        |
|    explained_variance   | 0.128        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00613     |
|    n_updates            | 20           |
|    policy_gradient_loss | -0.00259     |
|    std                  | 1.01         |
|    value_loss           | 0.00559      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 482          |
|    iterations           | 4            |
|    time_elapsed         | 16           |
|    total_timesteps      | 8192         |
| train/                  |              |
|    approx_kl            | 0.0052952017 |
|    clip_fraction        | 0.0518       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.42        |
|    explained_variance   | 0.103        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0188      |
|    n_updates            | 30           |
|    policy_gradient_loss | -0.00367     |
|    std                  | 1            |
|    value_loss           | 0.0059       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 468          |
|    iterations           | 5            |
|    time_elapsed         | 21           |
|    total_timesteps      | 10240        |
| train/                  |              |
|    approx_kl            | 0.0035066658 |
|    clip_fraction        | 0.0335       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.41        |
|    explained_variance   | 0.123        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0188      |
|    n_updates            | 40           |
|    policy_gradient_loss | -0.00408     |
|    std                  | 0.99         |
|    value_loss           | 0.00703      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 474         |
|    iterations           | 6           |
|    time_elapsed         | 25          |
|    total_timesteps      | 12288       |
| train/                  |             |
|    approx_kl            | 0.005164394 |
|    clip_fraction        | 0.0382      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.41       |
|    explained_variance   | 0.0508      |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00186     |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.0046     |
|    std                  | 0.989       |
|    value_loss           | 0.00788     |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 476          |
|    iterations           | 7            |
|    time_elapsed         | 30           |
|    total_timesteps      | 14336        |
| train/                  |              |
|    approx_kl            | 0.0028266031 |
|    clip_fraction        | 0.0131       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.41        |
|    explained_variance   | 0.158        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0106      |
|    n_updates            | 60           |
|    policy_gradient_loss | -0.00135     |
|    std                  | 0.984        |
|    value_loss           | 0.00383      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 468          |
|    iterations           | 8            |
|    time_elapsed         | 34           |
|    total_timesteps      | 16384        |
| train/                  |              |
|    approx_kl            | 0.0024302814 |
|    clip_fraction        | 0.0123       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.4         |
|    explained_variance   | 0.14         |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0149      |
|    n_updates            | 70           |
|    policy_gradient_loss | -0.0012      |
|    std                  | 0.982        |
|    value_loss           | 0.00602      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 9            |
|    time_elapsed         | 39           |
|    total_timesteps      | 18432        |
| train/                  |              |
|    approx_kl            | 0.0037181878 |
|    clip_fraction        | 0.03         |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.4         |
|    explained_variance   | 0.158        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00437      |
|    n_updates            | 80           |
|    policy_gradient_loss | -0.00281     |
|    std                  | 0.976        |
|    value_loss           | 0.0102       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 10           |
|    time_elapsed         | 43           |
|    total_timesteps      | 20480        |
| train/                  |              |
|    approx_kl            | 0.0026378818 |
|    clip_fraction        | 0.0206       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.39        |
|    explained_variance   | 0.102        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00789     |
|    n_updates            | 90           |
|    policy_gradient_loss | -0.00166     |
|    std                  | 0.976        |
|    value_loss           | 0.0121       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 469          |
|    iterations           | 11           |
|    time_elapsed         | 48           |
|    total_timesteps      | 22528        |
| train/                  |              |
|    approx_kl            | 0.0028586714 |
|    clip_fraction        | 0.0221       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.4         |
|    explained_variance   | 0.143        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0189      |
|    n_updates            | 100          |
|    policy_gradient_loss | -0.00155     |
|    std                  | 0.981        |
|    value_loss           | 0.00822      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 12           |
|    time_elapsed         | 52           |
|    total_timesteps      | 24576        |
| train/                  |              |
|    approx_kl            | 0.0026830286 |
|    clip_fraction        | 0.0218       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.4         |
|    explained_variance   | 0.186        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00608     |
|    n_updates            | 110          |
|    policy_gradient_loss | -0.00195     |
|    std                  | 0.979        |
|    value_loss           | 0.00665      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 13          |
|    time_elapsed         | 56          |
|    total_timesteps      | 26624       |
| train/                  |             |
|    approx_kl            | 0.007284724 |
|    clip_fraction        | 0.0672      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.39       |
|    explained_variance   | 0.123       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0173      |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.00488    |
|    std                  | 0.968       |
|    value_loss           | 0.0152      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 469          |
|    iterations           | 14           |
|    time_elapsed         | 61           |
|    total_timesteps      | 28672        |
| train/                  |              |
|    approx_kl            | 0.0077027236 |
|    clip_fraction        | 0.0649       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.38        |
|    explained_variance   | 0.124        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0171       |
|    n_updates            | 130          |
|    policy_gradient_loss | -0.00384     |
|    std                  | 0.96         |
|    value_loss           | 0.00901      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 15           |
|    time_elapsed         | 65           |
|    total_timesteps      | 30720        |
| train/                  |              |
|    approx_kl            | 0.0026310626 |
|    clip_fraction        | 0.0211       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.38        |
|    explained_variance   | 0.0636       |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00212     |
|    n_updates            | 140          |
|    policy_gradient_loss | -0.00188     |
|    std                  | 0.956        |
|    value_loss           | 0.0132       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 471         |
|    iterations           | 16          |
|    time_elapsed         | 69          |
|    total_timesteps      | 32768       |
| train/                  |             |
|    approx_kl            | 0.004822363 |
|    clip_fraction        | 0.0554      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.36       |
|    explained_variance   | 0.126       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0159     |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.00474    |
|    std                  | 0.939       |
|    value_loss           | 0.0136      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 469          |
|    iterations           | 17           |
|    time_elapsed         | 74           |
|    total_timesteps      | 34816        |
| train/                  |              |
|    approx_kl            | 0.0046646288 |
|    clip_fraction        | 0.0461       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.36        |
|    explained_variance   | 0.146        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00466     |
|    n_updates            | 160          |
|    policy_gradient_loss | -0.00322     |
|    std                  | 0.939        |
|    value_loss           | 0.00979      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 471         |
|    iterations           | 18          |
|    time_elapsed         | 78          |
|    total_timesteps      | 36864       |
| train/                  |             |
|    approx_kl            | 0.004762671 |
|    clip_fraction        | 0.0422      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.35       |
|    explained_variance   | 0.123       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00825     |
|    n_updates            | 170         |
|    policy_gradient_loss | -0.00278    |
|    std                  | 0.935       |
|    value_loss           | 0.0221      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 470          |
|    iterations           | 19           |
|    time_elapsed         | 82           |
|    total_timesteps      | 38912        |
| train/                  |              |
|    approx_kl            | 0.0022159033 |
|    clip_fraction        | 0.0253       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.35        |
|    explained_variance   | 0.149        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00978      |
|    n_updates            | 180          |
|    policy_gradient_loss | -0.0026      |
|    std                  | 0.929        |
|    value_loss           | 0.0191       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 469          |
|    iterations           | 20           |
|    time_elapsed         | 87           |
|    total_timesteps      | 40960        |
| train/                  |              |
|    approx_kl            | 0.0020335582 |
|    clip_fraction        | 0.016        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.34        |
|    explained_variance   | 0.112        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.000161     |
|    n_updates            | 190          |
|    policy_gradient_loss | -0.000601    |
|    std                  | 0.922        |
|    value_loss           | 0.0213       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 470          |
|    iterations           | 21           |
|    time_elapsed         | 91           |
|    total_timesteps      | 43008        |
| train/                  |              |
|    approx_kl            | 0.0025986247 |
|    clip_fraction        | 0.0175       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.33        |
|    explained_variance   | 0.13         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00225      |
|    n_updates            | 200          |
|    policy_gradient_loss | -0.00133     |
|    std                  | 0.917        |
|    value_loss           | 0.0201       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 470          |
|    iterations           | 22           |
|    time_elapsed         | 95           |
|    total_timesteps      | 45056        |
| train/                  |              |
|    approx_kl            | 0.0037341323 |
|    clip_fraction        | 0.0327       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.32        |
|    explained_variance   | 0.187        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0119       |
|    n_updates            | 210          |
|    policy_gradient_loss | -0.00209     |
|    std                  | 0.904        |
|    value_loss           | 0.0222       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 469          |
|    iterations           | 23           |
|    time_elapsed         | 100          |
|    total_timesteps      | 47104        |
| train/                  |              |
|    approx_kl            | 0.0030124057 |
|    clip_fraction        | 0.0427       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.31        |
|    explained_variance   | 0.141        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00435      |
|    n_updates            | 220          |
|    policy_gradient_loss | -0.00234     |
|    std                  | 0.897        |
|    value_loss           | 0.0342       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 470         |
|    iterations           | 24          |
|    time_elapsed         | 104         |
|    total_timesteps      | 49152       |
| train/                  |             |
|    approx_kl            | 0.004523305 |
|    clip_fraction        | 0.0433      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.31       |
|    explained_variance   | 0.136       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00446     |
|    n_updates            | 230         |
|    policy_gradient_loss | -0.00312    |
|    std                  | 0.892       |
|    value_loss           | 0.0345      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 470          |
|    iterations           | 25           |
|    time_elapsed         | 108          |
|    total_timesteps      | 51200        |
| train/                  |              |
|    approx_kl            | 0.0042229104 |
|    clip_fraction        | 0.0172       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.3         |
|    explained_variance   | 0.141        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00565      |
|    n_updates            | 240          |
|    policy_gradient_loss | -0.00163     |
|    std                  | 0.89         |
|    value_loss           | 0.0304       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 470          |
|    iterations           | 26           |
|    time_elapsed         | 113          |
|    total_timesteps      | 53248        |
| train/                  |              |
|    approx_kl            | 0.0026445386 |
|    clip_fraction        | 0.0457       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.3         |
|    explained_variance   | 0.158        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00268     |
|    n_updates            | 250          |
|    policy_gradient_loss | -0.00385     |
|    std                  | 0.885        |
|    value_loss           | 0.0365       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 27           |
|    time_elapsed         | 117          |
|    total_timesteps      | 55296        |
| train/                  |              |
|    approx_kl            | 0.0030658604 |
|    clip_fraction        | 0.0362       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.29        |
|    explained_variance   | 0.142        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0201       |
|    n_updates            | 260          |
|    policy_gradient_loss | -0.00157     |
|    std                  | 0.877        |
|    value_loss           | 0.0418       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 471         |
|    iterations           | 28          |
|    time_elapsed         | 121         |
|    total_timesteps      | 57344       |
| train/                  |             |
|    approx_kl            | 0.005094944 |
|    clip_fraction        | 0.0331      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.29       |
|    explained_variance   | 0.164       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.027       |
|    n_updates            | 270         |
|    policy_gradient_loss | -0.00195    |
|    std                  | 0.873       |
|    value_loss           | 0.0517      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 29           |
|    time_elapsed         | 126          |
|    total_timesteps      | 59392        |
| train/                  |              |
|    approx_kl            | 0.0032281103 |
|    clip_fraction        | 0.0115       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.28        |
|    explained_variance   | 0.132        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00258      |
|    n_updates            | 280          |
|    policy_gradient_loss | -0.000784    |
|    std                  | 0.87         |
|    value_loss           | 0.0397       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 30           |
|    time_elapsed         | 130          |
|    total_timesteps      | 61440        |
| train/                  |              |
|    approx_kl            | 0.0022902484 |
|    clip_fraction        | 0.0213       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.27        |
|    explained_variance   | 0.158        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0201       |
|    n_updates            | 290          |
|    policy_gradient_loss | -0.00149     |
|    std                  | 0.862        |
|    value_loss           | 0.0489       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 31           |
|    time_elapsed         | 134          |
|    total_timesteps      | 63488        |
| train/                  |              |
|    approx_kl            | 0.0033099828 |
|    clip_fraction        | 0.0267       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.27        |
|    explained_variance   | 0.169        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0276       |
|    n_updates            | 300          |
|    policy_gradient_loss | -0.00157     |
|    std                  | 0.858        |
|    value_loss           | 0.0449       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 470          |
|    iterations           | 32           |
|    time_elapsed         | 139          |
|    total_timesteps      | 65536        |
| train/                  |              |
|    approx_kl            | 0.0032240688 |
|    clip_fraction        | 0.0298       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.26        |
|    explained_variance   | 0.175        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0132       |
|    n_updates            | 310          |
|    policy_gradient_loss | -0.00133     |
|    std                  | 0.853        |
|    value_loss           | 0.0459       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 33           |
|    time_elapsed         | 143          |
|    total_timesteps      | 67584        |
| train/                  |              |
|    approx_kl            | 0.0029686694 |
|    clip_fraction        | 0.0134       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.25        |
|    explained_variance   | 0.18         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0222       |
|    n_updates            | 320          |
|    policy_gradient_loss | -0.00101     |
|    std                  | 0.84         |
|    value_loss           | 0.0418       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 34           |
|    time_elapsed         | 147          |
|    total_timesteps      | 69632        |
| train/                  |              |
|    approx_kl            | 0.0032511498 |
|    clip_fraction        | 0.0211       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.24        |
|    explained_variance   | 0.15         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00989      |
|    n_updates            | 330          |
|    policy_gradient_loss | -0.000617    |
|    std                  | 0.835        |
|    value_loss           | 0.043        |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-------------------------------------------
| time/                   |               |
|    fps                  | 470           |
|    iterations           | 35            |
|    time_elapsed         | 152           |
|    total_timesteps      | 71680         |
| train/                  |               |
|    approx_kl            | 0.00078562996 |
|    clip_fraction        | 0.0148        |
|    clip_range           | 0.2           |
|    entropy_loss         | -1.24         |
|    explained_variance   | 0.139         |
|    learning_rate        | 0.0002        |
|    loss                 | 0.0232        |
|    n_updates            | 340           |
|    policy_gradient_loss | -0.00022      |
|    std                  | 0.833         |
|    value_loss           | 0.0527        |
-------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 471         |
|    iterations           | 36          |
|    time_elapsed         | 156         |
|    total_timesteps      | 73728       |
| train/                  |             |
|    approx_kl            | 0.008307964 |
|    clip_fraction        | 0.0606      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.23       |
|    explained_variance   | 0.18        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0269      |
|    n_updates            | 350         |
|    policy_gradient_loss | -0.00371    |
|    std                  | 0.828       |
|    value_loss           | 0.0367      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 470          |
|    iterations           | 37           |
|    time_elapsed         | 160          |
|    total_timesteps      | 75776        |
| train/                  |              |
|    approx_kl            | 0.0035759334 |
|    clip_fraction        | 0.0356       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.23        |
|    explained_variance   | 0.171        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0206       |
|    n_updates            | 360          |
|    policy_gradient_loss | -0.00148     |
|    std                  | 0.823        |
|    value_loss           | 0.057        |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 470          |
|    iterations           | 38           |
|    time_elapsed         | 165          |
|    total_timesteps      | 77824        |
| train/                  |              |
|    approx_kl            | 0.0034209117 |
|    clip_fraction        | 0.025        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.22        |
|    explained_variance   | 0.169        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0314       |
|    n_updates            | 370          |
|    policy_gradient_loss | -0.00111     |
|    std                  | 0.823        |
|    value_loss           | 0.04         |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 39           |
|    time_elapsed         | 169          |
|    total_timesteps      | 79872        |
| train/                  |              |
|    approx_kl            | 0.0074370373 |
|    clip_fraction        | 0.0386       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.22        |
|    explained_variance   | 0.162        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00519      |
|    n_updates            | 380          |
|    policy_gradient_loss | -0.00223     |
|    std                  | 0.822        |
|    value_loss           | 0.0403       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 40           |
|    time_elapsed         | 173          |
|    total_timesteps      | 81920        |
| train/                  |              |
|    approx_kl            | 0.0024809802 |
|    clip_fraction        | 0.0311       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.22        |
|    explained_variance   | 0.149        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00923     |
|    n_updates            | 390          |
|    policy_gradient_loss | -0.00174     |
|    std                  | 0.816        |
|    value_loss           | 0.0436       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 41           |
|    time_elapsed         | 178          |
|    total_timesteps      | 83968        |
| train/                  |              |
|    approx_kl            | 0.0031426123 |
|    clip_fraction        | 0.0292       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.21        |
|    explained_variance   | 0.164        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00587      |
|    n_updates            | 400          |
|    policy_gradient_loss | -0.00224     |
|    std                  | 0.807        |
|    value_loss           | 0.0505       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 42           |
|    time_elapsed         | 182          |
|    total_timesteps      | 86016        |
| train/                  |              |
|    approx_kl            | 0.0039739106 |
|    clip_fraction        | 0.033        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.2         |
|    explained_variance   | 0.179        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0252       |
|    n_updates            | 410          |
|    policy_gradient_loss | -0.00159     |
|    std                  | 0.801        |
|    value_loss           | 0.0557       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 470          |
|    iterations           | 43           |
|    time_elapsed         | 187          |
|    total_timesteps      | 88064        |
| train/                  |              |
|    approx_kl            | 0.0035296627 |
|    clip_fraction        | 0.0348       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.19        |
|    explained_variance   | 0.172        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0152       |
|    n_updates            | 420          |
|    policy_gradient_loss | -0.00257     |
|    std                  | 0.793        |
|    value_loss           | 0.0571       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 470          |
|    iterations           | 44           |
|    time_elapsed         | 191          |
|    total_timesteps      | 90112        |
| train/                  |              |
|    approx_kl            | 0.0031921265 |
|    clip_fraction        | 0.0375       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.18        |
|    explained_variance   | 0.154        |
|    learning_rate        | 0.0002       |
|    loss                 | -7.4e-05     |
|    n_updates            | 430          |
|    policy_gradient_loss | -0.00255     |
|    std                  | 0.784        |
|    value_loss           | 0.0411       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 45           |
|    time_elapsed         | 195          |
|    total_timesteps      | 92160        |
| train/                  |              |
|    approx_kl            | 0.0052892203 |
|    clip_fraction        | 0.0231       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.17        |
|    explained_variance   | 0.143        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0158       |
|    n_updates            | 440          |
|    policy_gradient_loss | -0.000402    |
|    std                  | 0.78         |
|    value_loss           | 0.0507       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 470          |
|    iterations           | 46           |
|    time_elapsed         | 200          |
|    total_timesteps      | 94208        |
| train/                  |              |
|    approx_kl            | 0.0038273337 |
|    clip_fraction        | 0.0181       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.17        |
|    explained_variance   | 0.148        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0137       |
|    n_updates            | 450          |
|    policy_gradient_loss | -0.000985    |
|    std                  | 0.779        |
|    value_loss           | 0.0485       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 47           |
|    time_elapsed         | 204          |
|    total_timesteps      | 96256        |
| train/                  |              |
|    approx_kl            | 0.0031193378 |
|    clip_fraction        | 0.0267       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.17        |
|    explained_variance   | 0.183        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0192       |
|    n_updates            | 460          |
|    policy_gradient_loss | -0.00131     |
|    std                  | 0.776        |
|    value_loss           | 0.0709       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 48           |
|    time_elapsed         | 208          |
|    total_timesteps      | 98304        |
| train/                  |              |
|    approx_kl            | 0.0027614457 |
|    clip_fraction        | 0.00996      |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.16        |
|    explained_variance   | 0.16         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0226       |
|    n_updates            | 470          |
|    policy_gradient_loss | 0.000216     |
|    std                  | 0.774        |
|    value_loss           | 0.053        |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 470          |
|    iterations           | 49           |
|    time_elapsed         | 213          |
|    total_timesteps      | 100352       |
| train/                  |              |
|    approx_kl            | 0.0016341873 |
|    clip_fraction        | 0.0143       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.16        |
|    explained_variance   | 0.15         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0101       |
|    n_updates            | 480          |
|    policy_gradient_loss | -7.93e-05    |
|    std                  | 0.775        |
|    value_loss           | 0.0463       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 50           |
|    time_elapsed         | 217          |
|    total_timesteps      | 102400       |
| train/                  |              |
|    approx_kl            | 0.0042742034 |
|    clip_fraction        | 0.0158       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.16        |
|    explained_variance   | 0.16         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0246       |
|    n_updates            | 490          |
|    policy_gradient_loss | 0.000104     |
|    std                  | 0.775        |
|    value_loss           | 0.0514       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 471         |
|    iterations           | 51          |
|    time_elapsed         | 221         |
|    total_timesteps      | 104448      |
| train/                  |             |
|    approx_kl            | 0.003762415 |
|    clip_fraction        | 0.0219      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.17       |
|    explained_variance   | 0.179       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0161      |
|    n_updates            | 500         |
|    policy_gradient_loss | -0.00102    |
|    std                  | 0.778       |
|    value_loss           | 0.0486      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 470          |
|    iterations           | 52           |
|    time_elapsed         | 226          |
|    total_timesteps      | 106496       |
| train/                  |              |
|    approx_kl            | 0.0064983643 |
|    clip_fraction        | 0.0478       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.16        |
|    explained_variance   | 0.186        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0199       |
|    n_updates            | 510          |
|    policy_gradient_loss | -0.00248     |
|    std                  | 0.772        |
|    value_loss           | 0.0642       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 471         |
|    iterations           | 53          |
|    time_elapsed         | 230         |
|    total_timesteps      | 108544      |
| train/                  |             |
|    approx_kl            | 0.004464566 |
|    clip_fraction        | 0.0285      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.16       |
|    explained_variance   | 0.17        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0249      |
|    n_updates            | 520         |
|    policy_gradient_loss | -0.00171    |
|    std                  | 0.772       |
|    value_loss           | 0.0514      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 54          |
|    time_elapsed         | 234         |
|    total_timesteps      | 110592      |
| train/                  |             |
|    approx_kl            | 0.002244516 |
|    clip_fraction        | 0.0187      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.16       |
|    explained_variance   | 0.132       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00352     |
|    n_updates            | 530         |
|    policy_gradient_loss | -0.00142    |
|    std                  | 0.764       |
|    value_loss           | 0.0482      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 55           |
|    time_elapsed         | 239          |
|    total_timesteps      | 112640       |
| train/                  |              |
|    approx_kl            | 0.0029669548 |
|    clip_fraction        | 0.0359       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.15        |
|    explained_variance   | 0.164        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00942      |
|    n_updates            | 540          |
|    policy_gradient_loss | -0.00302     |
|    std                  | 0.77         |
|    value_loss           | 0.0384       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 56           |
|    time_elapsed         | 243          |
|    total_timesteps      | 114688       |
| train/                  |              |
|    approx_kl            | 0.0043787058 |
|    clip_fraction        | 0.0376       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.15        |
|    explained_variance   | 0.156        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0381       |
|    n_updates            | 550          |
|    policy_gradient_loss | -0.00228     |
|    std                  | 0.764        |
|    value_loss           | 0.0513       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 57          |
|    time_elapsed         | 247         |
|    total_timesteps      | 116736      |
| train/                  |             |
|    approx_kl            | 0.004600373 |
|    clip_fraction        | 0.05        |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.15       |
|    explained_variance   | 0.183       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0188      |
|    n_updates            | 560         |
|    policy_gradient_loss | -0.00254    |
|    std                  | 0.766       |
|    value_loss           | 0.0744      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 471         |
|    iterations           | 58          |
|    time_elapsed         | 251         |
|    total_timesteps      | 118784      |
| train/                  |             |
|    approx_kl            | 0.004670746 |
|    clip_fraction        | 0.0459      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.15       |
|    explained_variance   | 0.149       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0286      |
|    n_updates            | 570         |
|    policy_gradient_loss | -0.00339    |
|    std                  | 0.762       |
|    value_loss           | 0.0625      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 59           |
|    time_elapsed         | 255          |
|    total_timesteps      | 120832       |
| train/                  |              |
|    approx_kl            | 0.0045772567 |
|    clip_fraction        | 0.0429       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.15        |
|    explained_variance   | 0.168        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.021        |
|    n_updates            | 580          |
|    policy_gradient_loss | -0.00314     |
|    std                  | 0.76         |
|    value_loss           | 0.0641       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 60           |
|    time_elapsed         | 259          |
|    total_timesteps      | 122880       |
| train/                  |              |
|    approx_kl            | 0.0051353844 |
|    clip_fraction        | 0.0405       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.14        |
|    explained_variance   | 0.172        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0094       |
|    n_updates            | 590          |
|    policy_gradient_loss | -0.00434     |
|    std                  | 0.754        |
|    value_loss           | 0.0442       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 61           |
|    time_elapsed         | 264          |
|    total_timesteps      | 124928       |
| train/                  |              |
|    approx_kl            | 0.0015184677 |
|    clip_fraction        | 0.0221       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.13        |
|    explained_variance   | 0.184        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0164       |
|    n_updates            | 600          |
|    policy_gradient_loss | -0.00159     |
|    std                  | 0.744        |
|    value_loss           | 0.0516       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 62          |
|    time_elapsed         | 268         |
|    total_timesteps      | 126976      |
| train/                  |             |
|    approx_kl            | 0.007125799 |
|    clip_fraction        | 0.0532      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.12       |
|    explained_variance   | 0.182       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0193      |
|    n_updates            | 610         |
|    policy_gradient_loss | -0.00182    |
|    std                  | 0.742       |
|    value_loss           | 0.0743      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 63           |
|    time_elapsed         | 272          |
|    total_timesteps      | 129024       |
| train/                  |              |
|    approx_kl            | 0.0028516012 |
|    clip_fraction        | 0.0257       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.12        |
|    explained_variance   | 0.167        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0239       |
|    n_updates            | 620          |
|    policy_gradient_loss | -0.00132     |
|    std                  | 0.735        |
|    value_loss           | 0.057        |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 64           |
|    time_elapsed         | 277          |
|    total_timesteps      | 131072       |
| train/                  |              |
|    approx_kl            | 0.0012303083 |
|    clip_fraction        | 0.0085       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.11        |
|    explained_variance   | 0.173        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00523      |
|    n_updates            | 630          |
|    policy_gradient_loss | -7.96e-05    |
|    std                  | 0.732        |
|    value_loss           | 0.0485       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 65           |
|    time_elapsed         | 281          |
|    total_timesteps      | 133120       |
| train/                  |              |
|    approx_kl            | 0.0039293757 |
|    clip_fraction        | 0.0229       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.11        |
|    explained_variance   | 0.193        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0199       |
|    n_updates            | 640          |
|    policy_gradient_loss | -0.000622    |
|    std                  | 0.73         |
|    value_loss           | 0.046        |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 66          |
|    time_elapsed         | 285         |
|    total_timesteps      | 135168      |
| train/                  |             |
|    approx_kl            | 0.005064634 |
|    clip_fraction        | 0.0342      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.11       |
|    explained_variance   | 0.176       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00651     |
|    n_updates            | 650         |
|    policy_gradient_loss | -0.00293    |
|    std                  | 0.73        |
|    value_loss           | 0.0503      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 471          |
|    iterations           | 67           |
|    time_elapsed         | 290          |
|    total_timesteps      | 137216       |
| train/                  |              |
|    approx_kl            | 0.0027164381 |
|    clip_fraction        | 0.0168       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.1         |
|    explained_variance   | 0.201        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0227       |
|    n_updates            | 660          |
|    policy_gradient_loss | -0.000846    |
|    std                  | 0.729        |
|    value_loss           | 0.0714       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 68           |
|    time_elapsed         | 294          |
|    total_timesteps      | 139264       |
| train/                  |              |
|    approx_kl            | 0.0038678665 |
|    clip_fraction        | 0.022        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.1         |
|    explained_variance   | 0.155        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0164       |
|    n_updates            | 670          |
|    policy_gradient_loss | 0.000341     |
|    std                  | 0.72         |
|    value_loss           | 0.0653       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 69           |
|    time_elapsed         | 298          |
|    total_timesteps      | 141312       |
| train/                  |              |
|    approx_kl            | 0.0024472314 |
|    clip_fraction        | 0.0279       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.09        |
|    explained_variance   | 0.177        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0157       |
|    n_updates            | 680          |
|    policy_gradient_loss | -0.000958    |
|    std                  | 0.719        |
|    value_loss           | 0.0581       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 70           |
|    time_elapsed         | 303          |
|    total_timesteps      | 143360       |
| train/                  |              |
|    approx_kl            | 0.0032202764 |
|    clip_fraction        | 0.0266       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.09        |
|    explained_variance   | 0.183        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00718      |
|    n_updates            | 690          |
|    policy_gradient_loss | -0.00195     |
|    std                  | 0.721        |
|    value_loss           | 0.0517       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 71           |
|    time_elapsed         | 307          |
|    total_timesteps      | 145408       |
| train/                  |              |
|    approx_kl            | 0.0021196739 |
|    clip_fraction        | 0.0233       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.09        |
|    explained_variance   | 0.181        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0226       |
|    n_updates            | 700          |
|    policy_gradient_loss | -0.00115     |
|    std                  | 0.722        |
|    value_loss           | 0.072        |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 72          |
|    time_elapsed         | 311         |
|    total_timesteps      | 147456      |
| train/                  |             |
|    approx_kl            | 0.005609144 |
|    clip_fraction        | 0.0338      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.09       |
|    explained_variance   | 0.149       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0338      |
|    n_updates            | 710         |
|    policy_gradient_loss | -0.00281    |
|    std                  | 0.713       |
|    value_loss           | 0.061       |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 73           |
|    time_elapsed         | 316          |
|    total_timesteps      | 149504       |
| train/                  |              |
|    approx_kl            | 0.0055905282 |
|    clip_fraction        | 0.029        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.08        |
|    explained_variance   | 0.176        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0335       |
|    n_updates            | 720          |
|    policy_gradient_loss | -0.000606    |
|    std                  | 0.715        |
|    value_loss           | 0.0622       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 74          |
|    time_elapsed         | 320         |
|    total_timesteps      | 151552      |
| train/                  |             |
|    approx_kl            | 0.003281112 |
|    clip_fraction        | 0.0453      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.08       |
|    explained_variance   | 0.181       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0179      |
|    n_updates            | 730         |
|    policy_gradient_loss | -0.00237    |
|    std                  | 0.711       |
|    value_loss           | 0.0572      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 75          |
|    time_elapsed         | 324         |
|    total_timesteps      | 153600      |
| train/                  |             |
|    approx_kl            | 0.005694908 |
|    clip_fraction        | 0.0648      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.08       |
|    explained_variance   | 0.167       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0174      |
|    n_updates            | 740         |
|    policy_gradient_loss | -0.0017     |
|    std                  | 0.711       |
|    value_loss           | 0.0528      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 76           |
|    time_elapsed         | 329          |
|    total_timesteps      | 155648       |
| train/                  |              |
|    approx_kl            | 0.0047909752 |
|    clip_fraction        | 0.0505       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.08        |
|    explained_variance   | 0.204        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00296      |
|    n_updates            | 750          |
|    policy_gradient_loss | -0.0032      |
|    std                  | 0.713        |
|    value_loss           | 0.062        |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 77           |
|    time_elapsed         | 333          |
|    total_timesteps      | 157696       |
| train/                  |              |
|    approx_kl            | 0.0025925022 |
|    clip_fraction        | 0.0129       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.08        |
|    explained_variance   | 0.192        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00741      |
|    n_updates            | 760          |
|    policy_gradient_loss | -0.000171    |
|    std                  | 0.71         |
|    value_loss           | 0.0601       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 78          |
|    time_elapsed         | 337         |
|    total_timesteps      | 159744      |
| train/                  |             |
|    approx_kl            | 0.003957284 |
|    clip_fraction        | 0.0283      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.08       |
|    explained_variance   | 0.175       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0365      |
|    n_updates            | 770         |
|    policy_gradient_loss | -0.00123    |
|    std                  | 0.709       |
|    value_loss           | 0.0604      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 79           |
|    time_elapsed         | 342          |
|    total_timesteps      | 161792       |
| train/                  |              |
|    approx_kl            | 0.0022843266 |
|    clip_fraction        | 0.022        |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.07        |
|    explained_variance   | 0.189        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0214       |
|    n_updates            | 780          |
|    policy_gradient_loss | 0.000114     |
|    std                  | 0.704        |
|    value_loss           | 0.0595       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 80          |
|    time_elapsed         | 346         |
|    total_timesteps      | 163840      |
| train/                  |             |
|    approx_kl            | 0.003876907 |
|    clip_fraction        | 0.0223      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.07       |
|    explained_variance   | 0.19        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0357      |
|    n_updates            | 790         |
|    policy_gradient_loss | -0.00105    |
|    std                  | 0.704       |
|    value_loss           | 0.0518      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 81           |
|    time_elapsed         | 350          |
|    total_timesteps      | 165888       |
| train/                  |              |
|    approx_kl            | 0.0037043374 |
|    clip_fraction        | 0.0336       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.07        |
|    explained_variance   | 0.22         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.022        |
|    n_updates            | 800          |
|    policy_gradient_loss | -0.00144     |
|    std                  | 0.705        |
|    value_loss           | 0.0672       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 82          |
|    time_elapsed         | 355         |
|    total_timesteps      | 167936      |
| train/                  |             |
|    approx_kl            | 0.005788939 |
|    clip_fraction        | 0.0329      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.06       |
|    explained_variance   | 0.191       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.04        |
|    n_updates            | 810         |
|    policy_gradient_loss | -0.00203    |
|    std                  | 0.698       |
|    value_loss           | 0.0576      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 83           |
|    time_elapsed         | 359          |
|    total_timesteps      | 169984       |
| train/                  |              |
|    approx_kl            | 0.0025871447 |
|    clip_fraction        | 0.0361       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.06        |
|    explained_variance   | 0.15         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0253       |
|    n_updates            | 820          |
|    policy_gradient_loss | -0.00085     |
|    std                  | 0.695        |
|    value_loss           | 0.0567       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 84          |
|    time_elapsed         | 363         |
|    total_timesteps      | 172032      |
| train/                  |             |
|    approx_kl            | 0.005348273 |
|    clip_fraction        | 0.0648      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.05       |
|    explained_variance   | 0.186       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00313    |
|    n_updates            | 830         |
|    policy_gradient_loss | -0.00394    |
|    std                  | 0.692       |
|    value_loss           | 0.0533      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 85          |
|    time_elapsed         | 368         |
|    total_timesteps      | 174080      |
| train/                  |             |
|    approx_kl            | 0.005469082 |
|    clip_fraction        | 0.0622      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.05       |
|    explained_variance   | 0.197       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0213      |
|    n_updates            | 840         |
|    policy_gradient_loss | -0.00532    |
|    std                  | 0.685       |
|    value_loss           | 0.0559      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 86           |
|    time_elapsed         | 372          |
|    total_timesteps      | 176128       |
| train/                  |              |
|    approx_kl            | 0.0026157494 |
|    clip_fraction        | 0.0429       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.05        |
|    explained_variance   | 0.203        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0321       |
|    n_updates            | 850          |
|    policy_gradient_loss | -0.00108     |
|    std                  | 0.692        |
|    value_loss           | 0.0755       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 87           |
|    time_elapsed         | 376          |
|    total_timesteps      | 178176       |
| train/                  |              |
|    approx_kl            | 0.0022007928 |
|    clip_fraction        | 0.0285       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.05        |
|    explained_variance   | 0.17         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0244       |
|    n_updates            | 860          |
|    policy_gradient_loss | -0.00253     |
|    std                  | 0.697        |
|    value_loss           | 0.0596       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 472        |
|    iterations           | 88         |
|    time_elapsed         | 381        |
|    total_timesteps      | 180224     |
| train/                  |            |
|    approx_kl            | 0.00396781 |
|    clip_fraction        | 0.0352     |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.06      |
|    explained_variance   | 0.163      |
|    learning_rate        | 0.0002     |
|    loss                 | 0.0281     |
|    n_updates            | 870        |
|    policy_gradient_loss | -0.000829  |
|    std                  | 0.696      |
|    value_loss           | 0.06       |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 89           |
|    time_elapsed         | 385          |
|    total_timesteps      | 182272       |
| train/                  |              |
|    approx_kl            | 0.0025826911 |
|    clip_fraction        | 0.0256       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.06        |
|    explained_variance   | 0.184        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0267       |
|    n_updates            | 880          |
|    policy_gradient_loss | -0.00118     |
|    std                  | 0.695        |
|    value_loss           | 0.0571       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 90           |
|    time_elapsed         | 389          |
|    total_timesteps      | 184320       |
| train/                  |              |
|    approx_kl            | 0.0020180088 |
|    clip_fraction        | 0.0175       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.05        |
|    explained_variance   | 0.193        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0185       |
|    n_updates            | 890          |
|    policy_gradient_loss | -0.000603    |
|    std                  | 0.69         |
|    value_loss           | 0.0583       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 472        |
|    iterations           | 91         |
|    time_elapsed         | 394        |
|    total_timesteps      | 186368     |
| train/                  |            |
|    approx_kl            | 0.00381684 |
|    clip_fraction        | 0.0446     |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.04      |
|    explained_variance   | 0.196      |
|    learning_rate        | 0.0002     |
|    loss                 | 0.00584    |
|    n_updates            | 900        |
|    policy_gradient_loss | -0.0038    |
|    std                  | 0.681      |
|    value_loss           | 0.0761     |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 473        |
|    iterations           | 92         |
|    time_elapsed         | 398        |
|    total_timesteps      | 188416     |
| train/                  |            |
|    approx_kl            | 0.00361431 |
|    clip_fraction        | 0.0342     |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.03      |
|    explained_variance   | 0.193      |
|    learning_rate        | 0.0002     |
|    loss                 | 0.0245     |
|    n_updates            | 910        |
|    policy_gradient_loss | -0.00192   |
|    std                  | 0.675      |
|    value_loss           | 0.0595     |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 93          |
|    time_elapsed         | 402         |
|    total_timesteps      | 190464      |
| train/                  |             |
|    approx_kl            | 0.002460877 |
|    clip_fraction        | 0.0177      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.02       |
|    explained_variance   | 0.177       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0207      |
|    n_updates            | 920         |
|    policy_gradient_loss | -0.000344   |
|    std                  | 0.671       |
|    value_loss           | 0.0631      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 94           |
|    time_elapsed         | 407          |
|    total_timesteps      | 192512       |
| train/                  |              |
|    approx_kl            | 0.0022297492 |
|    clip_fraction        | 0.0452       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.02        |
|    explained_variance   | 0.185        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0234       |
|    n_updates            | 930          |
|    policy_gradient_loss | -0.00244     |
|    std                  | 0.667        |
|    value_loss           | 0.0572       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 95           |
|    time_elapsed         | 411          |
|    total_timesteps      | 194560       |
| train/                  |              |
|    approx_kl            | 0.0015696425 |
|    clip_fraction        | 0.0225       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.01        |
|    explained_variance   | 0.196        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0191       |
|    n_updates            | 940          |
|    policy_gradient_loss | -0.00138     |
|    std                  | 0.663        |
|    value_loss           | 0.0582       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 96           |
|    time_elapsed         | 415          |
|    total_timesteps      | 196608       |
| train/                  |              |
|    approx_kl            | 0.0026999167 |
|    clip_fraction        | 0.0194       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1.01        |
|    explained_variance   | 0.205        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0339       |
|    n_updates            | 950          |
|    policy_gradient_loss | -0.000488    |
|    std                  | 0.661        |
|    value_loss           | 0.0795       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 97           |
|    time_elapsed         | 419          |
|    total_timesteps      | 198656       |
| train/                  |              |
|    approx_kl            | 0.0032332991 |
|    clip_fraction        | 0.0279       |
|    clip_range           | 0.2          |
|    entropy_loss         | -1           |
|    explained_variance   | 0.175        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0175       |
|    n_updates            | 960          |
|    policy_gradient_loss | -0.000554    |
|    std                  | 0.657        |
|    value_loss           | 0.0603       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 98           |
|    time_elapsed         | 424          |
|    total_timesteps      | 200704       |
| train/                  |              |
|    approx_kl            | 0.0037944333 |
|    clip_fraction        | 0.0383       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.998       |
|    explained_variance   | 0.184        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.016        |
|    n_updates            | 970          |
|    policy_gradient_loss | -0.000962    |
|    std                  | 0.656        |
|    value_loss           | 0.0563       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 99          |
|    time_elapsed         | 428         |
|    total_timesteps      | 202752      |
| train/                  |             |
|    approx_kl            | 0.004353984 |
|    clip_fraction        | 0.0376      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.995      |
|    explained_variance   | 0.191       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0387      |
|    n_updates            | 980         |
|    policy_gradient_loss | -0.00169    |
|    std                  | 0.653       |
|    value_loss           | 0.0565      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 100         |
|    time_elapsed         | 433         |
|    total_timesteps      | 204800      |
| train/                  |             |
|    approx_kl            | 0.002279107 |
|    clip_fraction        | 0.0344      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.993      |
|    explained_variance   | 0.19        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0176      |
|    n_updates            | 990         |
|    policy_gradient_loss | -0.00099    |
|    std                  | 0.654       |
|    value_loss           | 0.0522      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 101          |
|    time_elapsed         | 437          |
|    total_timesteps      | 206848       |
| train/                  |              |
|    approx_kl            | 0.0027321381 |
|    clip_fraction        | 0.0285       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.989       |
|    explained_variance   | 0.195        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0422       |
|    n_updates            | 1000         |
|    policy_gradient_loss | 0.000167     |
|    std                  | 0.647        |
|    value_loss           | 0.0776       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 102          |
|    time_elapsed         | 441          |
|    total_timesteps      | 208896       |
| train/                  |              |
|    approx_kl            | 0.0031372672 |
|    clip_fraction        | 0.0335       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.975       |
|    explained_variance   | 0.163        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0125       |
|    n_updates            | 1010         |
|    policy_gradient_loss | -0.00047     |
|    std                  | 0.636        |
|    value_loss           | 0.062        |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 103          |
|    time_elapsed         | 446          |
|    total_timesteps      | 210944       |
| train/                  |              |
|    approx_kl            | 0.0033396427 |
|    clip_fraction        | 0.0305       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.962       |
|    explained_variance   | 0.182        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0335       |
|    n_updates            | 1020         |
|    policy_gradient_loss | -0.000691    |
|    std                  | 0.63         |
|    value_loss           | 0.0612       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 104         |
|    time_elapsed         | 450         |
|    total_timesteps      | 212992      |
| train/                  |             |
|    approx_kl            | 0.004285981 |
|    clip_fraction        | 0.0358      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.954      |
|    explained_variance   | 0.186       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0134      |
|    n_updates            | 1030        |
|    policy_gradient_loss | -0.00163    |
|    std                  | 0.627       |
|    value_loss           | 0.0552      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 105          |
|    time_elapsed         | 454          |
|    total_timesteps      | 215040       |
| train/                  |              |
|    approx_kl            | 0.0036805712 |
|    clip_fraction        | 0.0187       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.948       |
|    explained_variance   | 0.206        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0209       |
|    n_updates            | 1040         |
|    policy_gradient_loss | 5.53e-05     |
|    std                  | 0.622        |
|    value_loss           | 0.0655       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 106          |
|    time_elapsed         | 459          |
|    total_timesteps      | 217088       |
| train/                  |              |
|    approx_kl            | 0.0047136205 |
|    clip_fraction        | 0.0662       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.948       |
|    explained_variance   | 0.197        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0141       |
|    n_updates            | 1050         |
|    policy_gradient_loss | -0.007       |
|    std                  | 0.627        |
|    value_loss           | 0.0649       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 107          |
|    time_elapsed         | 463          |
|    total_timesteps      | 219136       |
| train/                  |              |
|    approx_kl            | 0.0047304602 |
|    clip_fraction        | 0.0344       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.949       |
|    explained_variance   | 0.154        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0256       |
|    n_updates            | 1060         |
|    policy_gradient_loss | -0.00067     |
|    std                  | 0.621        |
|    value_loss           | 0.0498       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 108         |
|    time_elapsed         | 467         |
|    total_timesteps      | 221184      |
| train/                  |             |
|    approx_kl            | 0.001967669 |
|    clip_fraction        | 0.0215      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.944      |
|    explained_variance   | 0.191       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0249      |
|    n_updates            | 1070        |
|    policy_gradient_loss | -0.000308   |
|    std                  | 0.623       |
|    value_loss           | 0.0579      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 109          |
|    time_elapsed         | 472          |
|    total_timesteps      | 223232       |
| train/                  |              |
|    approx_kl            | 0.0015890548 |
|    clip_fraction        | 0.0348       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.948       |
|    explained_variance   | 0.195        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0231       |
|    n_updates            | 1080         |
|    policy_gradient_loss | -0.00032     |
|    std                  | 0.626        |
|    value_loss           | 0.0555       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 110         |
|    time_elapsed         | 476         |
|    total_timesteps      | 225280      |
| train/                  |             |
|    approx_kl            | 0.003928956 |
|    clip_fraction        | 0.0234      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.945      |
|    explained_variance   | 0.216       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0216      |
|    n_updates            | 1090        |
|    policy_gradient_loss | -0.000805   |
|    std                  | 0.62        |
|    value_loss           | 0.0709      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 111         |
|    time_elapsed         | 480         |
|    total_timesteps      | 227328      |
| train/                  |             |
|    approx_kl            | 0.006729114 |
|    clip_fraction        | 0.0434      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.938      |
|    explained_variance   | 0.19        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0319      |
|    n_updates            | 1100        |
|    policy_gradient_loss | -0.00308    |
|    std                  | 0.616       |
|    value_loss           | 0.0655      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 112         |
|    time_elapsed         | 485         |
|    total_timesteps      | 229376      |
| train/                  |             |
|    approx_kl            | 0.004940966 |
|    clip_fraction        | 0.0511      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.929      |
|    explained_variance   | 0.172       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0155      |
|    n_updates            | 1110        |
|    policy_gradient_loss | -0.00283    |
|    std                  | 0.609       |
|    value_loss           | 0.0591      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 113         |
|    time_elapsed         | 489         |
|    total_timesteps      | 231424      |
| train/                  |             |
|    approx_kl            | 0.006064343 |
|    clip_fraction        | 0.0625      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.92       |
|    explained_variance   | 0.193       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0263      |
|    n_updates            | 1120        |
|    policy_gradient_loss | -0.00233    |
|    std                  | 0.605       |
|    value_loss           | 0.0573      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 114          |
|    time_elapsed         | 493          |
|    total_timesteps      | 233472       |
| train/                  |              |
|    approx_kl            | 0.0037959046 |
|    clip_fraction        | 0.0351       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.917       |
|    explained_variance   | 0.179        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0363       |
|    n_updates            | 1130         |
|    policy_gradient_loss | -0.00249     |
|    std                  | 0.605        |
|    value_loss           | 0.0492       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 115         |
|    time_elapsed         | 498         |
|    total_timesteps      | 235520      |
| train/                  |             |
|    approx_kl            | 0.004034053 |
|    clip_fraction        | 0.0331      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.907      |
|    explained_variance   | 0.204       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0259      |
|    n_updates            | 1140        |
|    policy_gradient_loss | -0.00224    |
|    std                  | 0.594       |
|    value_loss           | 0.0676      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 116          |
|    time_elapsed         | 502          |
|    total_timesteps      | 237568       |
| train/                  |              |
|    approx_kl            | 0.0015804843 |
|    clip_fraction        | 0.018        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.892       |
|    explained_variance   | 0.192        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0476       |
|    n_updates            | 1150         |
|    policy_gradient_loss | 0.000637     |
|    std                  | 0.588        |
|    value_loss           | 0.0629       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 117         |
|    time_elapsed         | 506         |
|    total_timesteps      | 239616      |
| train/                  |             |
|    approx_kl            | 0.004270673 |
|    clip_fraction        | 0.0313      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.888      |
|    explained_variance   | 0.152       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0219      |
|    n_updates            | 1160        |
|    policy_gradient_loss | -0.000272   |
|    std                  | 0.588       |
|    value_loss           | 0.0607      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 118          |
|    time_elapsed         | 511          |
|    total_timesteps      | 241664       |
| train/                  |              |
|    approx_kl            | 0.0023561027 |
|    clip_fraction        | 0.0433       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.886       |
|    explained_variance   | 0.188        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0326       |
|    n_updates            | 1170         |
|    policy_gradient_loss | -0.0015      |
|    std                  | 0.586        |
|    value_loss           | 0.0571       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 119          |
|    time_elapsed         | 515          |
|    total_timesteps      | 243712       |
| train/                  |              |
|    approx_kl            | 0.0028924956 |
|    clip_fraction        | 0.0361       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.882       |
|    explained_variance   | 0.17         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0147       |
|    n_updates            | 1180         |
|    policy_gradient_loss | -0.000836    |
|    std                  | 0.583        |
|    value_loss           | 0.0548       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 120          |
|    time_elapsed         | 519          |
|    total_timesteps      | 245760       |
| train/                  |              |
|    approx_kl            | 0.0036979252 |
|    clip_fraction        | 0.0183       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.876       |
|    explained_variance   | 0.208        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0176       |
|    n_updates            | 1190         |
|    policy_gradient_loss | -9.49e-05    |
|    std                  | 0.579        |
|    value_loss           | 0.0691       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 121          |
|    time_elapsed         | 524          |
|    total_timesteps      | 247808       |
| train/                  |              |
|    approx_kl            | 0.0030116555 |
|    clip_fraction        | 0.0314       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.873       |
|    explained_variance   | 0.193        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0303       |
|    n_updates            | 1200         |
|    policy_gradient_loss | -0.000826    |
|    std                  | 0.58         |
|    value_loss           | 0.0547       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 122          |
|    time_elapsed         | 528          |
|    total_timesteps      | 249856       |
| train/                  |              |
|    approx_kl            | 0.0059173387 |
|    clip_fraction        | 0.0517       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.876       |
|    explained_variance   | 0.178        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0241       |
|    n_updates            | 1210         |
|    policy_gradient_loss | -0.00297     |
|    std                  | 0.581        |
|    value_loss           | 0.0587       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 123          |
|    time_elapsed         | 532          |
|    total_timesteps      | 251904       |
| train/                  |              |
|    approx_kl            | 0.0022398536 |
|    clip_fraction        | 0.0291       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.875       |
|    explained_variance   | 0.191        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0379       |
|    n_updates            | 1220         |
|    policy_gradient_loss | 0.000399     |
|    std                  | 0.579        |
|    value_loss           | 0.0567       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 124         |
|    time_elapsed         | 537         |
|    total_timesteps      | 253952      |
| train/                  |             |
|    approx_kl            | 0.004402024 |
|    clip_fraction        | 0.0403      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.869      |
|    explained_variance   | 0.203       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0233      |
|    n_updates            | 1230        |
|    policy_gradient_loss | -0.00132    |
|    std                  | 0.574       |
|    value_loss           | 0.054       |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 125          |
|    time_elapsed         | 541          |
|    total_timesteps      | 256000       |
| train/                  |              |
|    approx_kl            | 0.0024303498 |
|    clip_fraction        | 0.015        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.86        |
|    explained_variance   | 0.224        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0258       |
|    n_updates            | 1240         |
|    policy_gradient_loss | -0.000512    |
|    std                  | 0.569        |
|    value_loss           | 0.0676       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 126          |
|    time_elapsed         | 545          |
|    total_timesteps      | 258048       |
| train/                  |              |
|    approx_kl            | 0.0021347469 |
|    clip_fraction        | 0.0437       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.856       |
|    explained_variance   | 0.201        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0129       |
|    n_updates            | 1250         |
|    policy_gradient_loss | -0.00173     |
|    std                  | 0.569        |
|    value_loss           | 0.0527       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 127          |
|    time_elapsed         | 550          |
|    total_timesteps      | 260096       |
| train/                  |              |
|    approx_kl            | 0.0014138222 |
|    clip_fraction        | 0.0248       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.851       |
|    explained_variance   | 0.177        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0159       |
|    n_updates            | 1260         |
|    policy_gradient_loss | -0.000244    |
|    std                  | 0.564        |
|    value_loss           | 0.0526       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 128          |
|    time_elapsed         | 554          |
|    total_timesteps      | 262144       |
| train/                  |              |
|    approx_kl            | 0.0037523643 |
|    clip_fraction        | 0.0443       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.842       |
|    explained_variance   | 0.181        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.022        |
|    n_updates            | 1270         |
|    policy_gradient_loss | -0.00102     |
|    std                  | 0.559        |
|    value_loss           | 0.0534       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 129          |
|    time_elapsed         | 558          |
|    total_timesteps      | 264192       |
| train/                  |              |
|    approx_kl            | 0.0030136174 |
|    clip_fraction        | 0.0279       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.835       |
|    explained_variance   | 0.188        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0076       |
|    n_updates            | 1280         |
|    policy_gradient_loss | -0.00188     |
|    std                  | 0.557        |
|    value_loss           | 0.0491       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 130          |
|    time_elapsed         | 563          |
|    total_timesteps      | 266240       |
| train/                  |              |
|    approx_kl            | 0.0017504893 |
|    clip_fraction        | 0.0381       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.837       |
|    explained_variance   | 0.221        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0255       |
|    n_updates            | 1290         |
|    policy_gradient_loss | -0.000975    |
|    std                  | 0.561        |
|    value_loss           | 0.0702       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 131          |
|    time_elapsed         | 567          |
|    total_timesteps      | 268288       |
| train/                  |              |
|    approx_kl            | 0.0038036772 |
|    clip_fraction        | 0.0434       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.84        |
|    explained_variance   | 0.19         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0221       |
|    n_updates            | 1300         |
|    policy_gradient_loss | -0.00156     |
|    std                  | 0.56         |
|    value_loss           | 0.0602       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 132         |
|    time_elapsed         | 572         |
|    total_timesteps      | 270336      |
| train/                  |             |
|    approx_kl            | 0.004974502 |
|    clip_fraction        | 0.038       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.841      |
|    explained_variance   | 0.183       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0376      |
|    n_updates            | 1310        |
|    policy_gradient_loss | -0.000789   |
|    std                  | 0.561       |
|    value_loss           | 0.0543      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 133         |
|    time_elapsed         | 576         |
|    total_timesteps      | 272384      |
| train/                  |             |
|    approx_kl            | 0.001983458 |
|    clip_fraction        | 0.0155      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.84       |
|    explained_variance   | 0.18        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0317      |
|    n_updates            | 1320        |
|    policy_gradient_loss | -0.000358   |
|    std                  | 0.559       |
|    value_loss           | 0.0526      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 134          |
|    time_elapsed         | 580          |
|    total_timesteps      | 274432       |
| train/                  |              |
|    approx_kl            | 0.0032561598 |
|    clip_fraction        | 0.0453       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.841       |
|    explained_variance   | 0.193        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0162       |
|    n_updates            | 1330         |
|    policy_gradient_loss | -0.0015      |
|    std                  | 0.562        |
|    value_loss           | 0.0547       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 135          |
|    time_elapsed         | 585          |
|    total_timesteps      | 276480       |
| train/                  |              |
|    approx_kl            | 0.0035014641 |
|    clip_fraction        | 0.0281       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.839       |
|    explained_variance   | 0.213        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0118       |
|    n_updates            | 1340         |
|    policy_gradient_loss | -0.000193    |
|    std                  | 0.557        |
|    value_loss           | 0.0742       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 136          |
|    time_elapsed         | 589          |
|    total_timesteps      | 278528       |
| train/                  |              |
|    approx_kl            | 0.0041314303 |
|    clip_fraction        | 0.0458       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.835       |
|    explained_variance   | 0.167        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0249       |
|    n_updates            | 1350         |
|    policy_gradient_loss | -0.00374     |
|    std                  | 0.559        |
|    value_loss           | 0.0608       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 137          |
|    time_elapsed         | 593          |
|    total_timesteps      | 280576       |
| train/                  |              |
|    approx_kl            | 0.0037049723 |
|    clip_fraction        | 0.0326       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.834       |
|    explained_variance   | 0.193        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0137       |
|    n_updates            | 1360         |
|    policy_gradient_loss | -0.00183     |
|    std                  | 0.555        |
|    value_loss           | 0.0539       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 138         |
|    time_elapsed         | 598         |
|    total_timesteps      | 282624      |
| train/                  |             |
|    approx_kl            | 0.007641551 |
|    clip_fraction        | 0.0472      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.828      |
|    explained_variance   | 0.206       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0215      |
|    n_updates            | 1370        |
|    policy_gradient_loss | -5.98e-05   |
|    std                  | 0.553       |
|    value_loss           | 0.0518      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 139          |
|    time_elapsed         | 602          |
|    total_timesteps      | 284672       |
| train/                  |              |
|    approx_kl            | 0.0039991783 |
|    clip_fraction        | 0.0352       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.829       |
|    explained_variance   | 0.199        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0122       |
|    n_updates            | 1380         |
|    policy_gradient_loss | -0.00128     |
|    std                  | 0.556        |
|    value_loss           | 0.0577       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 140         |
|    time_elapsed         | 606         |
|    total_timesteps      | 286720      |
| train/                  |             |
|    approx_kl            | 0.005275251 |
|    clip_fraction        | 0.0517      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.835      |
|    explained_variance   | 0.212       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0188      |
|    n_updates            | 1390        |
|    policy_gradient_loss | -0.00143    |
|    std                  | 0.56        |
|    value_loss           | 0.0729      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 141         |
|    time_elapsed         | 611         |
|    total_timesteps      | 288768      |
| train/                  |             |
|    approx_kl            | 0.004620795 |
|    clip_fraction        | 0.0543      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.835      |
|    explained_variance   | 0.187       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0451      |
|    n_updates            | 1400        |
|    policy_gradient_loss | -0.00248    |
|    std                  | 0.555       |
|    value_loss           | 0.0599      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 142          |
|    time_elapsed         | 615          |
|    total_timesteps      | 290816       |
| train/                  |              |
|    approx_kl            | 0.0032116342 |
|    clip_fraction        | 0.0519       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.831       |
|    explained_variance   | 0.205        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0199       |
|    n_updates            | 1410         |
|    policy_gradient_loss | -0.00248     |
|    std                  | 0.556        |
|    value_loss           | 0.0579       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 143         |
|    time_elapsed         | 619         |
|    total_timesteps      | 292864      |
| train/                  |             |
|    approx_kl            | 0.002539626 |
|    clip_fraction        | 0.0278      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.831      |
|    explained_variance   | 0.218       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0102      |
|    n_updates            | 1420        |
|    policy_gradient_loss | 0.00017     |
|    std                  | 0.554       |
|    value_loss           | 0.0536      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 144          |
|    time_elapsed         | 623          |
|    total_timesteps      | 294912       |
| train/                  |              |
|    approx_kl            | 0.0025723875 |
|    clip_fraction        | 0.0293       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.829       |
|    explained_variance   | 0.204        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.028        |
|    n_updates            | 1430         |
|    policy_gradient_loss | -0.000875    |
|    std                  | 0.554        |
|    value_loss           | 0.0716       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 145          |
|    time_elapsed         | 628          |
|    total_timesteps      | 296960       |
| train/                  |              |
|    approx_kl            | 0.0032689692 |
|    clip_fraction        | 0.0396       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.827       |
|    explained_variance   | 0.213        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0289       |
|    n_updates            | 1440         |
|    policy_gradient_loss | -0.00293     |
|    std                  | 0.552        |
|    value_loss           | 0.066        |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 146         |
|    time_elapsed         | 632         |
|    total_timesteps      | 299008      |
| train/                  |             |
|    approx_kl            | 0.006500571 |
|    clip_fraction        | 0.0474      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.817      |
|    explained_variance   | 0.198       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0352      |
|    n_updates            | 1450        |
|    policy_gradient_loss | -0.00263    |
|    std                  | 0.543       |
|    value_loss           | 0.0619      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 147          |
|    time_elapsed         | 636          |
|    total_timesteps      | 301056       |
| train/                  |              |
|    approx_kl            | 0.0040040947 |
|    clip_fraction        | 0.0429       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.809       |
|    explained_variance   | 0.194        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0298       |
|    n_updates            | 1460         |
|    policy_gradient_loss | -0.00173     |
|    std                  | 0.543        |
|    value_loss           | 0.0577       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 148          |
|    time_elapsed         | 641          |
|    total_timesteps      | 303104       |
| train/                  |              |
|    approx_kl            | 0.0064436076 |
|    clip_fraction        | 0.0437       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.81        |
|    explained_variance   | 0.211        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0346       |
|    n_updates            | 1470         |
|    policy_gradient_loss | -0.00277     |
|    std                  | 0.545        |
|    value_loss           | 0.0589       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 149         |
|    time_elapsed         | 645         |
|    total_timesteps      | 305152      |
| train/                  |             |
|    approx_kl            | 0.004465021 |
|    clip_fraction        | 0.0613      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.807      |
|    explained_variance   | 0.231       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0197      |
|    n_updates            | 1480        |
|    policy_gradient_loss | -0.00373    |
|    std                  | 0.54        |
|    value_loss           | 0.0728      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 150          |
|    time_elapsed         | 649          |
|    total_timesteps      | 307200       |
| train/                  |              |
|    approx_kl            | 0.0044131307 |
|    clip_fraction        | 0.0403       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.798       |
|    explained_variance   | 0.218        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0227       |
|    n_updates            | 1490         |
|    policy_gradient_loss | -0.00293     |
|    std                  | 0.535        |
|    value_loss           | 0.0658       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 151          |
|    time_elapsed         | 654          |
|    total_timesteps      | 309248       |
| train/                  |              |
|    approx_kl            | 0.0046254476 |
|    clip_fraction        | 0.0346       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.79        |
|    explained_variance   | 0.199        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0317       |
|    n_updates            | 1500         |
|    policy_gradient_loss | -0.000645    |
|    std                  | 0.531        |
|    value_loss           | 0.0606       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 152          |
|    time_elapsed         | 658          |
|    total_timesteps      | 311296       |
| train/                  |              |
|    approx_kl            | 0.0038711156 |
|    clip_fraction        | 0.0454       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.784       |
|    explained_variance   | 0.207        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0135       |
|    n_updates            | 1510         |
|    policy_gradient_loss | -0.00175     |
|    std                  | 0.529        |
|    value_loss           | 0.0605       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 153          |
|    time_elapsed         | 663          |
|    total_timesteps      | 313344       |
| train/                  |              |
|    approx_kl            | 0.0034919507 |
|    clip_fraction        | 0.0365       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.78        |
|    explained_variance   | 0.204        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0179       |
|    n_updates            | 1520         |
|    policy_gradient_loss | -0.000912    |
|    std                  | 0.527        |
|    value_loss           | 0.055        |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 154         |
|    time_elapsed         | 667         |
|    total_timesteps      | 315392      |
| train/                  |             |
|    approx_kl            | 0.004280953 |
|    clip_fraction        | 0.0131      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.78       |
|    explained_variance   | 0.232       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.022       |
|    n_updates            | 1530        |
|    policy_gradient_loss | 0.000467    |
|    std                  | 0.528       |
|    value_loss           | 0.0697      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 155          |
|    time_elapsed         | 671          |
|    total_timesteps      | 317440       |
| train/                  |              |
|    approx_kl            | 0.0053964006 |
|    clip_fraction        | 0.0764       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.781       |
|    explained_variance   | 0.229        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.035        |
|    n_updates            | 1540         |
|    policy_gradient_loss | -0.00612     |
|    std                  | 0.528        |
|    value_loss           | 0.0635       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 156         |
|    time_elapsed         | 675         |
|    total_timesteps      | 319488      |
| train/                  |             |
|    approx_kl            | 0.002737718 |
|    clip_fraction        | 0.0316      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.777      |
|    explained_variance   | 0.193       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0406      |
|    n_updates            | 1550        |
|    policy_gradient_loss | -0.00108    |
|    std                  | 0.524       |
|    value_loss           | 0.0634      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 157         |
|    time_elapsed         | 679         |
|    total_timesteps      | 321536      |
| train/                  |             |
|    approx_kl            | 0.003279105 |
|    clip_fraction        | 0.073       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.765      |
|    explained_variance   | 0.213       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0145      |
|    n_updates            | 1560        |
|    policy_gradient_loss | -0.0038     |
|    std                  | 0.516       |
|    value_loss           | 0.0604      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 158         |
|    time_elapsed         | 684         |
|    total_timesteps      | 323584      |
| train/                  |             |
|    approx_kl            | 0.003999033 |
|    clip_fraction        | 0.0192      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.758      |
|    explained_variance   | 0.21        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0535      |
|    n_updates            | 1570        |
|    policy_gradient_loss | -0.000211   |
|    std                  | 0.516       |
|    value_loss           | 0.0572      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 159          |
|    time_elapsed         | 688          |
|    total_timesteps      | 325632       |
| train/                  |              |
|    approx_kl            | 0.0051500425 |
|    clip_fraction        | 0.0202       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.759       |
|    explained_variance   | 0.231        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0491       |
|    n_updates            | 1580         |
|    policy_gradient_loss | -0.000627    |
|    std                  | 0.517        |
|    value_loss           | 0.072        |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 472         |
|    iterations           | 160         |
|    time_elapsed         | 692         |
|    total_timesteps      | 327680      |
| train/                  |             |
|    approx_kl            | 0.008068716 |
|    clip_fraction        | 0.062       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.753      |
|    explained_variance   | 0.206       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0223      |
|    n_updates            | 1590        |
|    policy_gradient_loss | -0.00409    |
|    std                  | 0.511       |
|    value_loss           | 0.0579      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 161         |
|    time_elapsed         | 696         |
|    total_timesteps      | 329728      |
| train/                  |             |
|    approx_kl            | 0.006726847 |
|    clip_fraction        | 0.0275      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.746      |
|    explained_variance   | 0.194       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0211      |
|    n_updates            | 1600        |
|    policy_gradient_loss | -0.00146    |
|    std                  | 0.51        |
|    value_loss           | 0.0555      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 162          |
|    time_elapsed         | 701          |
|    total_timesteps      | 331776       |
| train/                  |              |
|    approx_kl            | 0.0035214003 |
|    clip_fraction        | 0.0356       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.74        |
|    explained_variance   | 0.207        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0298       |
|    n_updates            | 1610         |
|    policy_gradient_loss | -0.000972    |
|    std                  | 0.505        |
|    value_loss           | 0.0575       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 163          |
|    time_elapsed         | 705          |
|    total_timesteps      | 333824       |
| train/                  |              |
|    approx_kl            | 0.0044144755 |
|    clip_fraction        | 0.0543       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.738       |
|    explained_variance   | 0.223        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0154       |
|    n_updates            | 1620         |
|    policy_gradient_loss | -0.0023      |
|    std                  | 0.508        |
|    value_loss           | 0.061        |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 164          |
|    time_elapsed         | 709          |
|    total_timesteps      | 335872       |
| train/                  |              |
|    approx_kl            | 0.0046197716 |
|    clip_fraction        | 0.0513       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.737       |
|    explained_variance   | 0.233        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0306       |
|    n_updates            | 1630         |
|    policy_gradient_loss | -0.00258     |
|    std                  | 0.503        |
|    value_loss           | 0.0799       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 472          |
|    iterations           | 165          |
|    time_elapsed         | 714          |
|    total_timesteps      | 337920       |
| train/                  |              |
|    approx_kl            | 0.0040665753 |
|    clip_fraction        | 0.0437       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.734       |
|    explained_variance   | 0.227        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0224       |
|    n_updates            | 1640         |
|    policy_gradient_loss | -0.0025      |
|    std                  | 0.506        |
|    value_loss           | 0.0558       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 166          |
|    time_elapsed         | 718          |
|    total_timesteps      | 339968       |
| train/                  |              |
|    approx_kl            | 0.0020482205 |
|    clip_fraction        | 0.0265       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.735       |
|    explained_variance   | 0.214        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0248       |
|    n_updates            | 1650         |
|    policy_gradient_loss | -0.000656    |
|    std                  | 0.504        |
|    value_loss           | 0.0591       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 167          |
|    time_elapsed         | 722          |
|    total_timesteps      | 342016       |
| train/                  |              |
|    approx_kl            | 0.0027605067 |
|    clip_fraction        | 0.0328       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.728       |
|    explained_variance   | 0.212        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.026        |
|    n_updates            | 1660         |
|    policy_gradient_loss | -0.000309    |
|    std                  | 0.499        |
|    value_loss           | 0.0608       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 168         |
|    time_elapsed         | 727         |
|    total_timesteps      | 344064      |
| train/                  |             |
|    approx_kl            | 0.001834187 |
|    clip_fraction        | 0.0285      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.721      |
|    explained_variance   | 0.225       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0294      |
|    n_updates            | 1670        |
|    policy_gradient_loss | -0.000464   |
|    std                  | 0.497       |
|    value_loss           | 0.0575      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 169          |
|    time_elapsed         | 731          |
|    total_timesteps      | 346112       |
| train/                  |              |
|    approx_kl            | 0.0050056614 |
|    clip_fraction        | 0.0487       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.714       |
|    explained_variance   | 0.236        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0146       |
|    n_updates            | 1680         |
|    policy_gradient_loss | -0.00325     |
|    std                  | 0.492        |
|    value_loss           | 0.0749       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 170         |
|    time_elapsed         | 735         |
|    total_timesteps      | 348160      |
| train/                  |             |
|    approx_kl            | 0.004456532 |
|    clip_fraction        | 0.0335      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.706      |
|    explained_variance   | 0.205       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0348      |
|    n_updates            | 1690        |
|    policy_gradient_loss | -5.47e-05   |
|    std                  | 0.489       |
|    value_loss           | 0.0613      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 171          |
|    time_elapsed         | 740          |
|    total_timesteps      | 350208       |
| train/                  |              |
|    approx_kl            | 0.0027675203 |
|    clip_fraction        | 0.0388       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.702       |
|    explained_variance   | 0.217        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0256       |
|    n_updates            | 1700         |
|    policy_gradient_loss | -0.00105     |
|    std                  | 0.487        |
|    value_loss           | 0.0605       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 172          |
|    time_elapsed         | 744          |
|    total_timesteps      | 352256       |
| train/                  |              |
|    approx_kl            | 0.0019224008 |
|    clip_fraction        | 0.0219       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.699       |
|    explained_variance   | 0.217        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0202       |
|    n_updates            | 1710         |
|    policy_gradient_loss | 7.93e-05     |
|    std                  | 0.487        |
|    value_loss           | 0.0565       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 173          |
|    time_elapsed         | 748          |
|    total_timesteps      | 354304       |
| train/                  |              |
|    approx_kl            | 0.0029155328 |
|    clip_fraction        | 0.0247       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.702       |
|    explained_variance   | 0.216        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00843      |
|    n_updates            | 1720         |
|    policy_gradient_loss | -0.00058     |
|    std                  | 0.49         |
|    value_loss           | 0.0551       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 174          |
|    time_elapsed         | 753          |
|    total_timesteps      | 356352       |
| train/                  |              |
|    approx_kl            | 0.0046107443 |
|    clip_fraction        | 0.0481       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.703       |
|    explained_variance   | 0.224        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0242       |
|    n_updates            | 1730         |
|    policy_gradient_loss | -0.00169     |
|    std                  | 0.488        |
|    value_loss           | 0.0764       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 473        |
|    iterations           | 175        |
|    time_elapsed         | 757        |
|    total_timesteps      | 358400     |
| train/                  |            |
|    approx_kl            | 0.00587956 |
|    clip_fraction        | 0.0518     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.701     |
|    explained_variance   | 0.204      |
|    learning_rate        | 0.0002     |
|    loss                 | 0.0109     |
|    n_updates            | 1740       |
|    policy_gradient_loss | -0.00383   |
|    std                  | 0.487      |
|    value_loss           | 0.0643     |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 176          |
|    time_elapsed         | 761          |
|    total_timesteps      | 360448       |
| train/                  |              |
|    approx_kl            | 0.0062439647 |
|    clip_fraction        | 0.0597       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.7         |
|    explained_variance   | 0.226        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0133       |
|    n_updates            | 1750         |
|    policy_gradient_loss | -0.00257     |
|    std                  | 0.488        |
|    value_loss           | 0.0637       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 177         |
|    time_elapsed         | 765         |
|    total_timesteps      | 362496      |
| train/                  |             |
|    approx_kl            | 0.001188039 |
|    clip_fraction        | 0.0299      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.705      |
|    explained_variance   | 0.224       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0136      |
|    n_updates            | 1760        |
|    policy_gradient_loss | -0.00153    |
|    std                  | 0.492       |
|    value_loss           | 0.0587      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 178         |
|    time_elapsed         | 770         |
|    total_timesteps      | 364544      |
| train/                  |             |
|    approx_kl            | 0.006972283 |
|    clip_fraction        | 0.0538      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.708      |
|    explained_variance   | 0.231       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0298      |
|    n_updates            | 1770        |
|    policy_gradient_loss | -0.00262    |
|    std                  | 0.491       |
|    value_loss           | 0.0605      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 179          |
|    time_elapsed         | 774          |
|    total_timesteps      | 366592       |
| train/                  |              |
|    approx_kl            | 0.0058519756 |
|    clip_fraction        | 0.0573       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.706       |
|    explained_variance   | 0.246        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0247       |
|    n_updates            | 1780         |
|    policy_gradient_loss | -0.00214     |
|    std                  | 0.49         |
|    value_loss           | 0.0712       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 180         |
|    time_elapsed         | 778         |
|    total_timesteps      | 368640      |
| train/                  |             |
|    approx_kl            | 0.004268538 |
|    clip_fraction        | 0.0351      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.707      |
|    explained_variance   | 0.201       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0337      |
|    n_updates            | 1790        |
|    policy_gradient_loss | -0.00107    |
|    std                  | 0.491       |
|    value_loss           | 0.0647      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 181          |
|    time_elapsed         | 782          |
|    total_timesteps      | 370688       |
| train/                  |              |
|    approx_kl            | 0.0042625177 |
|    clip_fraction        | 0.0305       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.706       |
|    explained_variance   | 0.223        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0168       |
|    n_updates            | 1800         |
|    policy_gradient_loss | -0.00159     |
|    std                  | 0.489        |
|    value_loss           | 0.0594       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 182          |
|    time_elapsed         | 787          |
|    total_timesteps      | 372736       |
| train/                  |              |
|    approx_kl            | 0.0023833402 |
|    clip_fraction        | 0.0216       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.704       |
|    explained_variance   | 0.232        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0328       |
|    n_updates            | 1810         |
|    policy_gradient_loss | -0.000444    |
|    std                  | 0.489        |
|    value_loss           | 0.0584       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 183          |
|    time_elapsed         | 792          |
|    total_timesteps      | 374784       |
| train/                  |              |
|    approx_kl            | 0.0024076202 |
|    clip_fraction        | 0.0257       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.701       |
|    explained_variance   | 0.256        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.023        |
|    n_updates            | 1820         |
|    policy_gradient_loss | -0.000673    |
|    std                  | 0.486        |
|    value_loss           | 0.0727       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 184          |
|    time_elapsed         | 796          |
|    total_timesteps      | 376832       |
| train/                  |              |
|    approx_kl            | 0.0020318215 |
|    clip_fraction        | 0.0164       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.694       |
|    explained_variance   | 0.231        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0317       |
|    n_updates            | 1830         |
|    policy_gradient_loss | -0.000112    |
|    std                  | 0.482        |
|    value_loss           | 0.0701       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 185          |
|    time_elapsed         | 800          |
|    total_timesteps      | 378880       |
| train/                  |              |
|    approx_kl            | 0.0028521102 |
|    clip_fraction        | 0.0208       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.687       |
|    explained_variance   | 0.219        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0307       |
|    n_updates            | 1840         |
|    policy_gradient_loss | 0.000828     |
|    std                  | 0.48         |
|    value_loss           | 0.0615       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 186         |
|    time_elapsed         | 804         |
|    total_timesteps      | 380928      |
| train/                  |             |
|    approx_kl            | 0.004355269 |
|    clip_fraction        | 0.0756      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.687      |
|    explained_variance   | 0.228       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0159      |
|    n_updates            | 1850        |
|    policy_gradient_loss | -0.00227    |
|    std                  | 0.483       |
|    value_loss           | 0.0628      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 187         |
|    time_elapsed         | 808         |
|    total_timesteps      | 382976      |
| train/                  |             |
|    approx_kl            | 0.002128278 |
|    clip_fraction        | 0.0198      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.692      |
|    explained_variance   | 0.227       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0202      |
|    n_updates            | 1860        |
|    policy_gradient_loss | -0.000531   |
|    std                  | 0.483       |
|    value_loss           | 0.0603      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 188          |
|    time_elapsed         | 812          |
|    total_timesteps      | 385024       |
| train/                  |              |
|    approx_kl            | 0.0052994844 |
|    clip_fraction        | 0.0671       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.685       |
|    explained_variance   | 0.259        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0188       |
|    n_updates            | 1870         |
|    policy_gradient_loss | -0.00298     |
|    std                  | 0.477        |
|    value_loss           | 0.0709       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 189          |
|    time_elapsed         | 817          |
|    total_timesteps      | 387072       |
| train/                  |              |
|    approx_kl            | 0.0045617702 |
|    clip_fraction        | 0.0524       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.679       |
|    explained_variance   | 0.235        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0214       |
|    n_updates            | 1880         |
|    policy_gradient_loss | -0.00155     |
|    std                  | 0.478        |
|    value_loss           | 0.0699       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 190          |
|    time_elapsed         | 821          |
|    total_timesteps      | 389120       |
| train/                  |              |
|    approx_kl            | 0.0029062442 |
|    clip_fraction        | 0.0431       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.679       |
|    explained_variance   | 0.217        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0276       |
|    n_updates            | 1890         |
|    policy_gradient_loss | -0.00193     |
|    std                  | 0.476        |
|    value_loss           | 0.0619       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 191         |
|    time_elapsed         | 825         |
|    total_timesteps      | 391168      |
| train/                  |             |
|    approx_kl            | 0.003330552 |
|    clip_fraction        | 0.0179      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.673      |
|    explained_variance   | 0.226       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0338      |
|    n_updates            | 1900        |
|    policy_gradient_loss | -0.00113    |
|    std                  | 0.472       |
|    value_loss           | 0.0608      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 192          |
|    time_elapsed         | 830          |
|    total_timesteps      | 393216       |
| train/                  |              |
|    approx_kl            | 0.0075479243 |
|    clip_fraction        | 0.0533       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.664       |
|    explained_variance   | 0.225        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0423       |
|    n_updates            | 1910         |
|    policy_gradient_loss | -0.00141     |
|    std                  | 0.468        |
|    value_loss           | 0.0579       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 193          |
|    time_elapsed         | 834          |
|    total_timesteps      | 395264       |
| train/                  |              |
|    approx_kl            | 0.0017749831 |
|    clip_fraction        | 0.0332       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.656       |
|    explained_variance   | 0.252        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0444       |
|    n_updates            | 1920         |
|    policy_gradient_loss | 0.00048      |
|    std                  | 0.465        |
|    value_loss           | 0.0776       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 194          |
|    time_elapsed         | 838          |
|    total_timesteps      | 397312       |
| train/                  |              |
|    approx_kl            | 0.0022773354 |
|    clip_fraction        | 0.0276       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.653       |
|    explained_variance   | 0.243        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0455       |
|    n_updates            | 1930         |
|    policy_gradient_loss | -0.00031     |
|    std                  | 0.465        |
|    value_loss           | 0.0621       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 195         |
|    time_elapsed         | 843         |
|    total_timesteps      | 399360      |
| train/                  |             |
|    approx_kl            | 0.004908588 |
|    clip_fraction        | 0.0359      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.656      |
|    explained_variance   | 0.21        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0213      |
|    n_updates            | 1940        |
|    policy_gradient_loss | -0.0017     |
|    std                  | 0.467       |
|    value_loss           | 0.0624      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 196          |
|    time_elapsed         | 847          |
|    total_timesteps      | 401408       |
| train/                  |              |
|    approx_kl            | 0.0022119074 |
|    clip_fraction        | 0.0272       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.653       |
|    explained_variance   | 0.234        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0372       |
|    n_updates            | 1950         |
|    policy_gradient_loss | -0.000319    |
|    std                  | 0.464        |
|    value_loss           | 0.0594       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 197          |
|    time_elapsed         | 851          |
|    total_timesteps      | 403456       |
| train/                  |              |
|    approx_kl            | 0.0060912357 |
|    clip_fraction        | 0.0485       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.648       |
|    explained_variance   | 0.257        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0422       |
|    n_updates            | 1960         |
|    policy_gradient_loss | -0.00184     |
|    std                  | 0.462        |
|    value_loss           | 0.0605       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 198          |
|    time_elapsed         | 856          |
|    total_timesteps      | 405504       |
| train/                  |              |
|    approx_kl            | 0.0046231207 |
|    clip_fraction        | 0.0367       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.647       |
|    explained_variance   | 0.255        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0518       |
|    n_updates            | 1970         |
|    policy_gradient_loss | -0.0012      |
|    std                  | 0.463        |
|    value_loss           | 0.0769       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 199          |
|    time_elapsed         | 860          |
|    total_timesteps      | 407552       |
| train/                  |              |
|    approx_kl            | 0.0048390077 |
|    clip_fraction        | 0.0548       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.64        |
|    explained_variance   | 0.233        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0269       |
|    n_updates            | 1980         |
|    policy_gradient_loss | -0.00208     |
|    std                  | 0.456        |
|    value_loss           | 0.0605       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 200         |
|    time_elapsed         | 864         |
|    total_timesteps      | 409600      |
| train/                  |             |
|    approx_kl            | 0.003926827 |
|    clip_fraction        | 0.0553      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.635      |
|    explained_variance   | 0.234       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0326      |
|    n_updates            | 1990        |
|    policy_gradient_loss | -0.00307    |
|    std                  | 0.458       |
|    value_loss           | 0.0654      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 201         |
|    time_elapsed         | 868         |
|    total_timesteps      | 411648      |
| train/                  |             |
|    approx_kl            | 0.002817834 |
|    clip_fraction        | 0.0169      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.641      |
|    explained_variance   | 0.237       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0162      |
|    n_updates            | 2000        |
|    policy_gradient_loss | -0.000218   |
|    std                  | 0.462       |
|    value_loss           | 0.0597      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 202          |
|    time_elapsed         | 873          |
|    total_timesteps      | 413696       |
| train/                  |              |
|    approx_kl            | 0.0039993795 |
|    clip_fraction        | 0.0242       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.644       |
|    explained_variance   | 0.237        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0336       |
|    n_updates            | 2010         |
|    policy_gradient_loss | -0.00113     |
|    std                  | 0.459        |
|    value_loss           | 0.0628       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 203          |
|    time_elapsed         | 877          |
|    total_timesteps      | 415744       |
| train/                  |              |
|    approx_kl            | 0.0026159873 |
|    clip_fraction        | 0.0226       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.64        |
|    explained_variance   | 0.269        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0354       |
|    n_updates            | 2020         |
|    policy_gradient_loss | 0.000449     |
|    std                  | 0.459        |
|    value_loss           | 0.0759       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 204         |
|    time_elapsed         | 881         |
|    total_timesteps      | 417792      |
| train/                  |             |
|    approx_kl            | 0.004432603 |
|    clip_fraction        | 0.0423      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.635      |
|    explained_variance   | 0.24        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0329      |
|    n_updates            | 2030        |
|    policy_gradient_loss | -0.00165    |
|    std                  | 0.454       |
|    value_loss           | 0.071       |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 205          |
|    time_elapsed         | 885          |
|    total_timesteps      | 419840       |
| train/                  |              |
|    approx_kl            | 0.0024810438 |
|    clip_fraction        | 0.0271       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.627       |
|    explained_variance   | 0.241        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0257       |
|    n_updates            | 2040         |
|    policy_gradient_loss | -0.000289    |
|    std                  | 0.453        |
|    value_loss           | 0.0644       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 206         |
|    time_elapsed         | 890         |
|    total_timesteps      | 421888      |
| train/                  |             |
|    approx_kl            | 0.002592634 |
|    clip_fraction        | 0.0315      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.633      |
|    explained_variance   | 0.241       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.027       |
|    n_updates            | 2050        |
|    policy_gradient_loss | -0.00189    |
|    std                  | 0.459       |
|    value_loss           | 0.0626      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 207          |
|    time_elapsed         | 894          |
|    total_timesteps      | 423936       |
| train/                  |              |
|    approx_kl            | 0.0034495813 |
|    clip_fraction        | 0.0457       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.637       |
|    explained_variance   | 0.264        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0132       |
|    n_updates            | 2060         |
|    policy_gradient_loss | -0.00366     |
|    std                  | 0.456        |
|    value_loss           | 0.0589       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 208          |
|    time_elapsed         | 898          |
|    total_timesteps      | 425984       |
| train/                  |              |
|    approx_kl            | 0.0036685565 |
|    clip_fraction        | 0.0334       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.631       |
|    explained_variance   | 0.276        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0423       |
|    n_updates            | 2070         |
|    policy_gradient_loss | -0.0013      |
|    std                  | 0.454        |
|    value_loss           | 0.0779       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 209          |
|    time_elapsed         | 902          |
|    total_timesteps      | 428032       |
| train/                  |              |
|    approx_kl            | 0.0026586577 |
|    clip_fraction        | 0.0404       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.628       |
|    explained_variance   | 0.237        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.014        |
|    n_updates            | 2080         |
|    policy_gradient_loss | -0.0029      |
|    std                  | 0.453        |
|    value_loss           | 0.0678       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 210          |
|    time_elapsed         | 907          |
|    total_timesteps      | 430080       |
| train/                  |              |
|    approx_kl            | 0.0049098125 |
|    clip_fraction        | 0.0423       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.625       |
|    explained_variance   | 0.255        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0428       |
|    n_updates            | 2090         |
|    policy_gradient_loss | -0.00295     |
|    std                  | 0.452        |
|    value_loss           | 0.0662       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 211         |
|    time_elapsed         | 911         |
|    total_timesteps      | 432128      |
| train/                  |             |
|    approx_kl            | 0.005466015 |
|    clip_fraction        | 0.0481      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.623      |
|    explained_variance   | 0.238       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0224      |
|    n_updates            | 2100        |
|    policy_gradient_loss | -0.00317    |
|    std                  | 0.449       |
|    value_loss           | 0.065       |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 212          |
|    time_elapsed         | 915          |
|    total_timesteps      | 434176       |
| train/                  |              |
|    approx_kl            | 0.0020351098 |
|    clip_fraction        | 0.0229       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.615       |
|    explained_variance   | 0.255        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0262       |
|    n_updates            | 2110         |
|    policy_gradient_loss | -0.000628    |
|    std                  | 0.447        |
|    value_loss           | 0.0606       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 213          |
|    time_elapsed         | 920          |
|    total_timesteps      | 436224       |
| train/                  |              |
|    approx_kl            | 0.0041807964 |
|    clip_fraction        | 0.0291       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.608       |
|    explained_variance   | 0.262        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0324       |
|    n_updates            | 2120         |
|    policy_gradient_loss | -0.000672    |
|    std                  | 0.443        |
|    value_loss           | 0.081        |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 214          |
|    time_elapsed         | 924          |
|    total_timesteps      | 438272       |
| train/                  |              |
|    approx_kl            | 0.0028988407 |
|    clip_fraction        | 0.0246       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.603       |
|    explained_variance   | 0.229        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0308       |
|    n_updates            | 2130         |
|    policy_gradient_loss | -0.000771    |
|    std                  | 0.442        |
|    value_loss           | 0.0654       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 215          |
|    time_elapsed         | 928          |
|    total_timesteps      | 440320       |
| train/                  |              |
|    approx_kl            | 0.0027941163 |
|    clip_fraction        | 0.034        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.599       |
|    explained_variance   | 0.253        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0164       |
|    n_updates            | 2140         |
|    policy_gradient_loss | -0.00144     |
|    std                  | 0.439        |
|    value_loss           | 0.0621       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 216          |
|    time_elapsed         | 933          |
|    total_timesteps      | 442368       |
| train/                  |              |
|    approx_kl            | 0.0028939159 |
|    clip_fraction        | 0.026        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.594       |
|    explained_variance   | 0.26         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.029        |
|    n_updates            | 2150         |
|    policy_gradient_loss | -0.000135    |
|    std                  | 0.438        |
|    value_loss           | 0.0603       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 217          |
|    time_elapsed         | 937          |
|    total_timesteps      | 444416       |
| train/                  |              |
|    approx_kl            | 0.0027454519 |
|    clip_fraction        | 0.0391       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.596       |
|    explained_variance   | 0.278        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0514       |
|    n_updates            | 2160         |
|    policy_gradient_loss | -0.00185     |
|    std                  | 0.439        |
|    value_loss           | 0.076        |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 474         |
|    iterations           | 218         |
|    time_elapsed         | 941         |
|    total_timesteps      | 446464      |
| train/                  |             |
|    approx_kl            | 0.003165176 |
|    clip_fraction        | 0.0422      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.591      |
|    explained_variance   | 0.272       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0598      |
|    n_updates            | 2170        |
|    policy_gradient_loss | -0.00235    |
|    std                  | 0.434       |
|    value_loss           | 0.069       |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 474         |
|    iterations           | 219         |
|    time_elapsed         | 946         |
|    total_timesteps      | 448512      |
| train/                  |             |
|    approx_kl            | 0.003970482 |
|    clip_fraction        | 0.0291      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.58       |
|    explained_variance   | 0.247       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0424      |
|    n_updates            | 2180        |
|    policy_gradient_loss | -0.000582   |
|    std                  | 0.431       |
|    value_loss           | 0.0642      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 474         |
|    iterations           | 220         |
|    time_elapsed         | 950         |
|    total_timesteps      | 450560      |
| train/                  |             |
|    approx_kl            | 0.007654547 |
|    clip_fraction        | 0.0745      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.574      |
|    explained_variance   | 0.255       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0243      |
|    n_updates            | 2190        |
|    policy_gradient_loss | -0.00477    |
|    std                  | 0.429       |
|    value_loss           | 0.0631      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 474         |
|    iterations           | 221         |
|    time_elapsed         | 954         |
|    total_timesteps      | 452608      |
| train/                  |             |
|    approx_kl            | 0.002519311 |
|    clip_fraction        | 0.028       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.57       |
|    explained_variance   | 0.269       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0315      |
|    n_updates            | 2200        |
|    policy_gradient_loss | -0.000876   |
|    std                  | 0.427       |
|    value_loss           | 0.0605      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 222          |
|    time_elapsed         | 958          |
|    total_timesteps      | 454656       |
| train/                  |              |
|    approx_kl            | 0.0030966839 |
|    clip_fraction        | 0.0375       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.567       |
|    explained_variance   | 0.283        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0198       |
|    n_updates            | 2210         |
|    policy_gradient_loss | -0.000343    |
|    std                  | 0.426        |
|    value_loss           | 0.0714       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 474         |
|    iterations           | 223         |
|    time_elapsed         | 963         |
|    total_timesteps      | 456704      |
| train/                  |             |
|    approx_kl            | 0.003706668 |
|    clip_fraction        | 0.0349      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.57       |
|    explained_variance   | 0.267       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0338      |
|    n_updates            | 2220        |
|    policy_gradient_loss | -0.00163    |
|    std                  | 0.43        |
|    value_loss           | 0.0712      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 224          |
|    time_elapsed         | 967          |
|    total_timesteps      | 458752       |
| train/                  |              |
|    approx_kl            | 0.0024205311 |
|    clip_fraction        | 0.0208       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.571       |
|    explained_variance   | 0.261        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.031        |
|    n_updates            | 2230         |
|    policy_gradient_loss | -0.000805    |
|    std                  | 0.426        |
|    value_loss           | 0.0633       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 474         |
|    iterations           | 225         |
|    time_elapsed         | 972         |
|    total_timesteps      | 460800      |
| train/                  |             |
|    approx_kl            | 0.002846303 |
|    clip_fraction        | 0.034       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.566      |
|    explained_variance   | 0.273       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0336      |
|    n_updates            | 2240        |
|    policy_gradient_loss | -0.000576   |
|    std                  | 0.427       |
|    value_loss           | 0.0644      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 474        |
|    iterations           | 226        |
|    time_elapsed         | 976        |
|    total_timesteps      | 462848     |
| train/                  |            |
|    approx_kl            | 0.00200198 |
|    clip_fraction        | 0.019      |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.563     |
|    explained_variance   | 0.27       |
|    learning_rate        | 0.0002     |
|    loss                 | 0.0328     |
|    n_updates            | 2250       |
|    policy_gradient_loss | -0.000195  |
|    std                  | 0.424      |
|    value_loss           | 0.0585     |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 227          |
|    time_elapsed         | 980          |
|    total_timesteps      | 464896       |
| train/                  |              |
|    approx_kl            | 0.0021484985 |
|    clip_fraction        | 0.046        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.564       |
|    explained_variance   | 0.299        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0285       |
|    n_updates            | 2260         |
|    policy_gradient_loss | -0.00327     |
|    std                  | 0.427        |
|    value_loss           | 0.0717       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 474         |
|    iterations           | 228         |
|    time_elapsed         | 985         |
|    total_timesteps      | 466944      |
| train/                  |             |
|    approx_kl            | 0.003897233 |
|    clip_fraction        | 0.0424      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.568      |
|    explained_variance   | 0.271       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0335      |
|    n_updates            | 2270        |
|    policy_gradient_loss | -0.000581   |
|    std                  | 0.426       |
|    value_loss           | 0.07        |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 229          |
|    time_elapsed         | 989          |
|    total_timesteps      | 468992       |
| train/                  |              |
|    approx_kl            | 0.0026333262 |
|    clip_fraction        | 0.0207       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.567       |
|    explained_variance   | 0.262        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0315       |
|    n_updates            | 2280         |
|    policy_gradient_loss | 0.000216     |
|    std                  | 0.427        |
|    value_loss           | 0.0612       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 230          |
|    time_elapsed         | 993          |
|    total_timesteps      | 471040       |
| train/                  |              |
|    approx_kl            | 0.0042356793 |
|    clip_fraction        | 0.036        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.57        |
|    explained_variance   | 0.272        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0237       |
|    n_updates            | 2290         |
|    policy_gradient_loss | -0.00255     |
|    std                  | 0.428        |
|    value_loss           | 0.0624       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 231          |
|    time_elapsed         | 998          |
|    total_timesteps      | 473088       |
| train/                  |              |
|    approx_kl            | 0.0022145007 |
|    clip_fraction        | 0.051        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.57        |
|    explained_variance   | 0.27         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0177       |
|    n_updates            | 2300         |
|    policy_gradient_loss | -0.00209     |
|    std                  | 0.427        |
|    value_loss           | 0.0588       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 232          |
|    time_elapsed         | 1002         |
|    total_timesteps      | 475136       |
| train/                  |              |
|    approx_kl            | 0.0030009996 |
|    clip_fraction        | 0.025        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.563       |
|    explained_variance   | 0.28         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0468       |
|    n_updates            | 2310         |
|    policy_gradient_loss | -0.00122     |
|    std                  | 0.423        |
|    value_loss           | 0.0799       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 474         |
|    iterations           | 233         |
|    time_elapsed         | 1006        |
|    total_timesteps      | 477184      |
| train/                  |             |
|    approx_kl            | 0.003106887 |
|    clip_fraction        | 0.0345      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.559      |
|    explained_variance   | 0.272       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0118      |
|    n_updates            | 2320        |
|    policy_gradient_loss | -0.00214    |
|    std                  | 0.423       |
|    value_loss           | 0.0629      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 234          |
|    time_elapsed         | 1011         |
|    total_timesteps      | 479232       |
| train/                  |              |
|    approx_kl            | 0.0053220494 |
|    clip_fraction        | 0.0482       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.555       |
|    explained_variance   | 0.27         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0341       |
|    n_updates            | 2330         |
|    policy_gradient_loss | -0.00264     |
|    std                  | 0.42         |
|    value_loss           | 0.0619       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 474         |
|    iterations           | 235         |
|    time_elapsed         | 1015        |
|    total_timesteps      | 481280      |
| train/                  |             |
|    approx_kl            | 0.002707812 |
|    clip_fraction        | 0.0404      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.549      |
|    explained_variance   | 0.285       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0323      |
|    n_updates            | 2340        |
|    policy_gradient_loss | -0.00143    |
|    std                  | 0.418       |
|    value_loss           | 0.064       |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 236          |
|    time_elapsed         | 1019         |
|    total_timesteps      | 483328       |
| train/                  |              |
|    approx_kl            | 0.0038645982 |
|    clip_fraction        | 0.0387       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.552       |
|    explained_variance   | 0.292        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0405       |
|    n_updates            | 2350         |
|    policy_gradient_loss | -0.0015      |
|    std                  | 0.423        |
|    value_loss           | 0.0619       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 237          |
|    time_elapsed         | 1024         |
|    total_timesteps      | 485376       |
| train/                  |              |
|    approx_kl            | 0.0046579577 |
|    clip_fraction        | 0.0398       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.555       |
|    explained_variance   | 0.303        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0295       |
|    n_updates            | 2360         |
|    policy_gradient_loss | -0.00227     |
|    std                  | 0.42         |
|    value_loss           | 0.0819       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 238          |
|    time_elapsed         | 1028         |
|    total_timesteps      | 487424       |
| train/                  |              |
|    approx_kl            | 0.0031077748 |
|    clip_fraction        | 0.0212       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.551       |
|    explained_variance   | 0.278        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0242       |
|    n_updates            | 2370         |
|    policy_gradient_loss | -0.000261    |
|    std                  | 0.419        |
|    value_loss           | 0.0645       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 239          |
|    time_elapsed         | 1032         |
|    total_timesteps      | 489472       |
| train/                  |              |
|    approx_kl            | 0.0047959094 |
|    clip_fraction        | 0.0411       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.552       |
|    explained_variance   | 0.298        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0197       |
|    n_updates            | 2380         |
|    policy_gradient_loss | -0.003       |
|    std                  | 0.421        |
|    value_loss           | 0.0651       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 240          |
|    time_elapsed         | 1037         |
|    total_timesteps      | 491520       |
| train/                  |              |
|    approx_kl            | 0.0044158464 |
|    clip_fraction        | 0.0314       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.551       |
|    explained_variance   | 0.272        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00962      |
|    n_updates            | 2390         |
|    policy_gradient_loss | -0.00147     |
|    std                  | 0.419        |
|    value_loss           | 0.0629       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 241          |
|    time_elapsed         | 1041         |
|    total_timesteps      | 493568       |
| train/                  |              |
|    approx_kl            | 0.0018369822 |
|    clip_fraction        | 0.0245       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.547       |
|    explained_variance   | 0.28         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0236       |
|    n_updates            | 2400         |
|    policy_gradient_loss | 0.000452     |
|    std                  | 0.418        |
|    value_loss           | 0.0627       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 474         |
|    iterations           | 242         |
|    time_elapsed         | 1045        |
|    total_timesteps      | 495616      |
| train/                  |             |
|    approx_kl            | 0.005183015 |
|    clip_fraction        | 0.0416      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.547      |
|    explained_variance   | 0.292       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0543      |
|    n_updates            | 2410        |
|    policy_gradient_loss | -0.00161    |
|    std                  | 0.418       |
|    value_loss           | 0.0797      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 473         |
|    iterations           | 243         |
|    time_elapsed         | 1050        |
|    total_timesteps      | 497664      |
| train/                  |             |
|    approx_kl            | 0.002665854 |
|    clip_fraction        | 0.0208      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.546      |
|    explained_variance   | 0.27        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0499      |
|    n_updates            | 2420        |
|    policy_gradient_loss | 0.000755    |
|    std                  | 0.419       |
|    value_loss           | 0.066       |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 474         |
|    iterations           | 244         |
|    time_elapsed         | 1054        |
|    total_timesteps      | 499712      |
| train/                  |             |
|    approx_kl            | 0.005093759 |
|    clip_fraction        | 0.036       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.547      |
|    explained_variance   | 0.28        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0268      |
|    n_updates            | 2430        |
|    policy_gradient_loss | -0.00125    |
|    std                  | 0.417       |
|    value_loss           | 0.0647      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 245          |
|    time_elapsed         | 1058         |
|    total_timesteps      | 501760       |
| train/                  |              |
|    approx_kl            | 0.0027389892 |
|    clip_fraction        | 0.0401       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.543       |
|    explained_variance   | 0.268        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0446       |
|    n_updates            | 2440         |
|    policy_gradient_loss | -0.00114     |
|    std                  | 0.414        |
|    value_loss           | 0.0614       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Saved model: model/saved/ppo_model_pair.zip

=== Training basket_0050_2330_2412 ===
Tickers: 0050.TW, 2330.TW, 2412.TW
Period: 2018-01-01 to 2024-12-31
Feature rows: 1700
Using cpu device

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------
| time/              |      |
|    fps             | 518  |
|    iterations      | 1    |
|    time_elapsed    | 3    |
|    total_timesteps | 2048 |
-----------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 500          |
|    iterations           | 2            |
|    time_elapsed         | 8            |
|    total_timesteps      | 4096         |
| train/                  |              |
|    approx_kl            | 0.0044308286 |
|    clip_fraction        | 0.0383       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.27        |
|    explained_variance   | -0.968       |
|    learning_rate        | 0.0002       |
|    loss                 | -0.031       |
|    n_updates            | 10           |
|    policy_gradient_loss | -0.00523     |
|    std                  | 1.01         |
|    value_loss           | 0.0104       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 489          |
|    iterations           | 3            |
|    time_elapsed         | 12           |
|    total_timesteps      | 6144         |
| train/                  |              |
|    approx_kl            | 0.0056826556 |
|    clip_fraction        | 0.0434       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.29        |
|    explained_variance   | 0.552        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0337      |
|    n_updates            | 20           |
|    policy_gradient_loss | -0.00534     |
|    std                  | 1.01         |
|    value_loss           | 0.00475      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 474          |
|    iterations           | 4            |
|    time_elapsed         | 17           |
|    total_timesteps      | 8192         |
| train/                  |              |
|    approx_kl            | 0.0077556474 |
|    clip_fraction        | 0.0719       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.3         |
|    explained_variance   | 0.631        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0207      |
|    n_updates            | 30           |
|    policy_gradient_loss | -0.00702     |
|    std                  | 1.01         |
|    value_loss           | 0.00257      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 477         |
|    iterations           | 5           |
|    time_elapsed         | 21          |
|    total_timesteps      | 10240       |
| train/                  |             |
|    approx_kl            | 0.004625141 |
|    clip_fraction        | 0.032       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.3        |
|    explained_variance   | 0.572       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0276     |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.00582    |
|    std                  | 1.02        |
|    value_loss           | 0.00395     |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 473          |
|    iterations           | 6            |
|    time_elapsed         | 25           |
|    total_timesteps      | 12288        |
| train/                  |              |
|    approx_kl            | 0.0052534854 |
|    clip_fraction        | 0.0333       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.31        |
|    explained_variance   | 0.698        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0316      |
|    n_updates            | 50           |
|    policy_gradient_loss | -0.00511     |
|    std                  | 1.02         |
|    value_loss           | 0.00273      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 468          |
|    iterations           | 7            |
|    time_elapsed         | 30           |
|    total_timesteps      | 14336        |
| train/                  |              |
|    approx_kl            | 0.0068067224 |
|    clip_fraction        | 0.059        |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.31        |
|    explained_variance   | 0.632        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.021       |
|    n_updates            | 60           |
|    policy_gradient_loss | -0.00666     |
|    std                  | 1.02         |
|    value_loss           | 0.00412      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 470         |
|    iterations           | 8           |
|    time_elapsed         | 34          |
|    total_timesteps      | 16384       |
| train/                  |             |
|    approx_kl            | 0.005633748 |
|    clip_fraction        | 0.0447      |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.32       |
|    explained_variance   | 0.585       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0145     |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.00476    |
|    std                  | 1.02        |
|    value_loss           | 0.00479     |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 467          |
|    iterations           | 9            |
|    time_elapsed         | 39           |
|    total_timesteps      | 18432        |
| train/                  |              |
|    approx_kl            | 0.0057682246 |
|    clip_fraction        | 0.0484       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.33        |
|    explained_variance   | 0.563        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0227      |
|    n_updates            | 80           |
|    policy_gradient_loss | -0.00614     |
|    std                  | 1.03         |
|    value_loss           | 0.00481      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 466          |
|    iterations           | 10           |
|    time_elapsed         | 43           |
|    total_timesteps      | 20480        |
| train/                  |              |
|    approx_kl            | 0.0053867614 |
|    clip_fraction        | 0.0422       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.33        |
|    explained_variance   | 0.609        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0273      |
|    n_updates            | 90           |
|    policy_gradient_loss | -0.00414     |
|    std                  | 1.03         |
|    value_loss           | 0.00344      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 468         |
|    iterations           | 11          |
|    time_elapsed         | 48          |
|    total_timesteps      | 22528       |
| train/                  |             |
|    approx_kl            | 0.005682419 |
|    clip_fraction        | 0.031       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.33       |
|    explained_variance   | 0.729       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00807    |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.00407    |
|    std                  | 1.02        |
|    value_loss           | 0.00318     |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 465         |
|    iterations           | 12          |
|    time_elapsed         | 52          |
|    total_timesteps      | 24576       |
| train/                  |             |
|    approx_kl            | 0.006664734 |
|    clip_fraction        | 0.0505      |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.32       |
|    explained_variance   | 0.714       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0219     |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.0059     |
|    std                  | 1.02        |
|    value_loss           | 0.00373     |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 464          |
|    iterations           | 13           |
|    time_elapsed         | 57           |
|    total_timesteps      | 26624        |
| train/                  |              |
|    approx_kl            | 0.0068619265 |
|    clip_fraction        | 0.0654       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.32        |
|    explained_variance   | 0.617        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0273      |
|    n_updates            | 120          |
|    policy_gradient_loss | -0.00723     |
|    std                  | 1.02         |
|    value_loss           | 0.00504      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 466          |
|    iterations           | 14           |
|    time_elapsed         | 61           |
|    total_timesteps      | 28672        |
| train/                  |              |
|    approx_kl            | 0.0065751364 |
|    clip_fraction        | 0.0632       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.31        |
|    explained_variance   | 0.579        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0143      |
|    n_updates            | 130          |
|    policy_gradient_loss | -0.00666     |
|    std                  | 1.02         |
|    value_loss           | 0.00544      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 15          |
|    time_elapsed         | 66          |
|    total_timesteps      | 30720       |
| train/                  |             |
|    approx_kl            | 0.005964763 |
|    clip_fraction        | 0.0543      |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.3        |
|    explained_variance   | 0.548       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0428     |
|    n_updates            | 140         |
|    policy_gradient_loss | -0.00604    |
|    std                  | 1.01        |
|    value_loss           | 0.00568     |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 464          |
|    iterations           | 16           |
|    time_elapsed         | 70           |
|    total_timesteps      | 32768        |
| train/                  |              |
|    approx_kl            | 0.0059771603 |
|    clip_fraction        | 0.0416       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.29        |
|    explained_variance   | 0.683        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0332      |
|    n_updates            | 150          |
|    policy_gradient_loss | -0.00674     |
|    std                  | 1.01         |
|    value_loss           | 0.00516      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 466          |
|    iterations           | 17           |
|    time_elapsed         | 74           |
|    total_timesteps      | 34816        |
| train/                  |              |
|    approx_kl            | 0.0091061415 |
|    clip_fraction        | 0.113        |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.29        |
|    explained_variance   | 0.657        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0281      |
|    n_updates            | 160          |
|    policy_gradient_loss | -0.0116      |
|    std                  | 1.01         |
|    value_loss           | 0.00434      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 18          |
|    time_elapsed         | 79          |
|    total_timesteps      | 36864       |
| train/                  |             |
|    approx_kl            | 0.007784252 |
|    clip_fraction        | 0.082       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.28       |
|    explained_variance   | 0.361       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0385     |
|    n_updates            | 170         |
|    policy_gradient_loss | -0.00853    |
|    std                  | 1.01        |
|    value_loss           | 0.0143      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 464         |
|    iterations           | 19          |
|    time_elapsed         | 83          |
|    total_timesteps      | 38912       |
| train/                  |             |
|    approx_kl            | 0.009525565 |
|    clip_fraction        | 0.109       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.26       |
|    explained_variance   | 0.332       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0245     |
|    n_updates            | 180         |
|    policy_gradient_loss | -0.0116     |
|    std                  | 0.999       |
|    value_loss           | 0.0234      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 466          |
|    iterations           | 20           |
|    time_elapsed         | 87           |
|    total_timesteps      | 40960        |
| train/                  |              |
|    approx_kl            | 0.0061915056 |
|    clip_fraction        | 0.0634       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.25        |
|    explained_variance   | 0.512        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00721     |
|    n_updates            | 190          |
|    policy_gradient_loss | -0.00755     |
|    std                  | 0.998        |
|    value_loss           | 0.00757      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 21          |
|    time_elapsed         | 92          |
|    total_timesteps      | 43008       |
| train/                  |             |
|    approx_kl            | 0.010115445 |
|    clip_fraction        | 0.123       |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.25       |
|    explained_variance   | 0.606       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0392     |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.0113     |
|    std                  | 0.995       |
|    value_loss           | 0.00943     |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 464          |
|    iterations           | 22           |
|    time_elapsed         | 97           |
|    total_timesteps      | 45056        |
| train/                  |              |
|    approx_kl            | 0.0069364524 |
|    clip_fraction        | 0.0773       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.23        |
|    explained_variance   | 0.535        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.019       |
|    n_updates            | 210          |
|    policy_gradient_loss | -0.0074      |
|    std                  | 0.989        |
|    value_loss           | 0.00966      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 465         |
|    iterations           | 23          |
|    time_elapsed         | 101         |
|    total_timesteps      | 47104       |
| train/                  |             |
|    approx_kl            | 0.007891367 |
|    clip_fraction        | 0.0574      |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.22       |
|    explained_variance   | 0.589       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0143     |
|    n_updates            | 220         |
|    policy_gradient_loss | -0.00594    |
|    std                  | 0.989       |
|    value_loss           | 0.00822     |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 463          |
|    iterations           | 24           |
|    time_elapsed         | 106          |
|    total_timesteps      | 49152        |
| train/                  |              |
|    approx_kl            | 0.0071297563 |
|    clip_fraction        | 0.0632       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.22        |
|    explained_variance   | 0.486        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0432      |
|    n_updates            | 230          |
|    policy_gradient_loss | -0.00531     |
|    std                  | 0.986        |
|    value_loss           | 0.0117       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 464         |
|    iterations           | 25          |
|    time_elapsed         | 110         |
|    total_timesteps      | 51200       |
| train/                  |             |
|    approx_kl            | 0.005360502 |
|    clip_fraction        | 0.0594      |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.22       |
|    explained_variance   | 0.594       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.017      |
|    n_updates            | 240         |
|    policy_gradient_loss | -0.00646    |
|    std                  | 0.987       |
|    value_loss           | 0.00911     |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 465          |
|    iterations           | 26           |
|    time_elapsed         | 114          |
|    total_timesteps      | 53248        |
| train/                  |              |
|    approx_kl            | 0.0050580744 |
|    clip_fraction        | 0.0471       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.21        |
|    explained_variance   | 0.623        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.032       |
|    n_updates            | 250          |
|    policy_gradient_loss | -0.00567     |
|    std                  | 0.981        |
|    value_loss           | 0.00718      |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 462        |
|    iterations           | 27         |
|    time_elapsed         | 119        |
|    total_timesteps      | 55296      |
| train/                  |            |
|    approx_kl            | 0.00701857 |
|    clip_fraction        | 0.0568     |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.2       |
|    explained_variance   | 0.596      |
|    learning_rate        | 0.0002     |
|    loss                 | -0.0245    |
|    n_updates            | 260        |
|    policy_gradient_loss | -0.00566   |
|    std                  | 0.979      |
|    value_loss           | 0.00924    |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 28          |
|    time_elapsed         | 123         |
|    total_timesteps      | 57344       |
| train/                  |             |
|    approx_kl            | 0.006472662 |
|    clip_fraction        | 0.0797      |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.18       |
|    explained_variance   | 0.437       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0223     |
|    n_updates            | 270         |
|    policy_gradient_loss | -0.00786    |
|    std                  | 0.972       |
|    value_loss           | 0.0163      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 29          |
|    time_elapsed         | 128         |
|    total_timesteps      | 59392       |
| train/                  |             |
|    approx_kl            | 0.007311511 |
|    clip_fraction        | 0.0676      |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.17       |
|    explained_variance   | 0.358       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0173     |
|    n_updates            | 280         |
|    policy_gradient_loss | -0.00787    |
|    std                  | 0.969       |
|    value_loss           | 0.0173      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 30           |
|    time_elapsed         | 132          |
|    total_timesteps      | 61440        |
| train/                  |              |
|    approx_kl            | 0.0053000916 |
|    clip_fraction        | 0.0719       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.16        |
|    explained_variance   | 0.483        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0291      |
|    n_updates            | 290          |
|    policy_gradient_loss | -0.00826     |
|    std                  | 0.969        |
|    value_loss           | 0.0151       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 463        |
|    iterations           | 31         |
|    time_elapsed         | 137        |
|    total_timesteps      | 63488      |
| train/                  |            |
|    approx_kl            | 0.00537756 |
|    clip_fraction        | 0.05       |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.14      |
|    explained_variance   | 0.421      |
|    learning_rate        | 0.0002     |
|    loss                 | -0.0191    |
|    n_updates            | 300        |
|    policy_gradient_loss | -0.00519   |
|    std                  | 0.958      |
|    value_loss           | 0.0224     |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 463        |
|    iterations           | 32         |
|    time_elapsed         | 141        |
|    total_timesteps      | 65536      |
| train/                  |            |
|    approx_kl            | 0.00742046 |
|    clip_fraction        | 0.0598     |
|    clip_range           | 0.2        |
|    entropy_loss         | -4.11      |
|    explained_variance   | 0.396      |
|    learning_rate        | 0.0002     |
|    loss                 | -0.013     |
|    n_updates            | 310        |
|    policy_gradient_loss | -0.00592   |
|    std                  | 0.951      |
|    value_loss           | 0.0192     |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 33          |
|    time_elapsed         | 146         |
|    total_timesteps      | 67584       |
| train/                  |             |
|    approx_kl            | 0.007576924 |
|    clip_fraction        | 0.0904      |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.09       |
|    explained_variance   | 0.418       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0177     |
|    n_updates            | 320         |
|    policy_gradient_loss | -0.00991    |
|    std                  | 0.945       |
|    value_loss           | 0.0164      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 34           |
|    time_elapsed         | 150          |
|    total_timesteps      | 69632        |
| train/                  |              |
|    approx_kl            | 0.0067401263 |
|    clip_fraction        | 0.0786       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.08        |
|    explained_variance   | 0.359        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0189      |
|    n_updates            | 330          |
|    policy_gradient_loss | -0.00754     |
|    std                  | 0.938        |
|    value_loss           | 0.0187       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 35          |
|    time_elapsed         | 155         |
|    total_timesteps      | 71680       |
| train/                  |             |
|    approx_kl            | 0.007143431 |
|    clip_fraction        | 0.0676      |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.06       |
|    explained_variance   | 0.324       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0155     |
|    n_updates            | 340         |
|    policy_gradient_loss | -0.00714    |
|    std                  | 0.936       |
|    value_loss           | 0.0244      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 461          |
|    iterations           | 36           |
|    time_elapsed         | 159          |
|    total_timesteps      | 73728        |
| train/                  |              |
|    approx_kl            | 0.0069632465 |
|    clip_fraction        | 0.0628       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.05        |
|    explained_variance   | 0.408        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0182      |
|    n_updates            | 350          |
|    policy_gradient_loss | -0.00537     |
|    std                  | 0.93         |
|    value_loss           | 0.0178       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 37          |
|    time_elapsed         | 163         |
|    total_timesteps      | 75776       |
| train/                  |             |
|    approx_kl            | 0.006329013 |
|    clip_fraction        | 0.0463      |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.03       |
|    explained_variance   | 0.28        |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0122     |
|    n_updates            | 360         |
|    policy_gradient_loss | -0.00497    |
|    std                  | 0.925       |
|    value_loss           | 0.0281      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 461          |
|    iterations           | 38           |
|    time_elapsed         | 168          |
|    total_timesteps      | 77824        |
| train/                  |              |
|    approx_kl            | 0.0073272763 |
|    clip_fraction        | 0.0681       |
|    clip_range           | 0.2          |
|    entropy_loss         | -4.01        |
|    explained_variance   | 0.402        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0165      |
|    n_updates            | 370          |
|    policy_gradient_loss | -0.00736     |
|    std                  | 0.92         |
|    value_loss           | 0.0172       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 39          |
|    time_elapsed         | 173         |
|    total_timesteps      | 79872       |
| train/                  |             |
|    approx_kl            | 0.008045826 |
|    clip_fraction        | 0.0752      |
|    clip_range           | 0.2         |
|    entropy_loss         | -4          |
|    explained_variance   | 0.291       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.015      |
|    n_updates            | 380         |
|    policy_gradient_loss | -0.00719    |
|    std                  | 0.918       |
|    value_loss           | 0.0282      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 462        |
|    iterations           | 40         |
|    time_elapsed         | 177        |
|    total_timesteps      | 81920      |
| train/                  |            |
|    approx_kl            | 0.00590713 |
|    clip_fraction        | 0.0502     |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.99      |
|    explained_variance   | 0.307      |
|    learning_rate        | 0.0002     |
|    loss                 | -0.0103    |
|    n_updates            | 390        |
|    policy_gradient_loss | -0.00447   |
|    std                  | 0.915      |
|    value_loss           | 0.0299     |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 461        |
|    iterations           | 41         |
|    time_elapsed         | 182        |
|    total_timesteps      | 83968      |
| train/                  |            |
|    approx_kl            | 0.00712499 |
|    clip_fraction        | 0.0704     |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.98      |
|    explained_variance   | 0.375      |
|    learning_rate        | 0.0002     |
|    loss                 | -0.0262    |
|    n_updates            | 400        |
|    policy_gradient_loss | -0.00466   |
|    std                  | 0.909      |
|    value_loss           | 0.0197     |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 42          |
|    time_elapsed         | 186         |
|    total_timesteps      | 86016       |
| train/                  |             |
|    approx_kl            | 0.006280344 |
|    clip_fraction        | 0.0714      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.97       |
|    explained_variance   | 0.339       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00693    |
|    n_updates            | 410         |
|    policy_gradient_loss | -0.00393    |
|    std                  | 0.909       |
|    value_loss           | 0.0336      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 43          |
|    time_elapsed         | 190         |
|    total_timesteps      | 88064       |
| train/                  |             |
|    approx_kl            | 0.007892977 |
|    clip_fraction        | 0.0798      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.96       |
|    explained_variance   | 0.343       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.019      |
|    n_updates            | 420         |
|    policy_gradient_loss | -0.00702    |
|    std                  | 0.904       |
|    value_loss           | 0.0346      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 44          |
|    time_elapsed         | 195         |
|    total_timesteps      | 90112       |
| train/                  |             |
|    approx_kl            | 0.007145552 |
|    clip_fraction        | 0.0879      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.95       |
|    explained_variance   | 0.338       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.000745   |
|    n_updates            | 430         |
|    policy_gradient_loss | -0.00945    |
|    std                  | 0.904       |
|    value_loss           | 0.0289      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 45          |
|    time_elapsed         | 199         |
|    total_timesteps      | 92160       |
| train/                  |             |
|    approx_kl            | 0.009013955 |
|    clip_fraction        | 0.0891      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.93       |
|    explained_variance   | 0.402       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0217     |
|    n_updates            | 440         |
|    policy_gradient_loss | -0.00896    |
|    std                  | 0.894       |
|    value_loss           | 0.0292      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 46           |
|    time_elapsed         | 203          |
|    total_timesteps      | 94208        |
| train/                  |              |
|    approx_kl            | 0.0059750164 |
|    clip_fraction        | 0.081        |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.91        |
|    explained_variance   | 0.334        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0132      |
|    n_updates            | 450          |
|    policy_gradient_loss | -0.00813     |
|    std                  | 0.891        |
|    value_loss           | 0.0157       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 461        |
|    iterations           | 47         |
|    time_elapsed         | 208        |
|    total_timesteps      | 96256      |
| train/                  |            |
|    approx_kl            | 0.00715571 |
|    clip_fraction        | 0.0877     |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.9       |
|    explained_variance   | 0.274      |
|    learning_rate        | 0.0002     |
|    loss                 | -0.0135    |
|    n_updates            | 460        |
|    policy_gradient_loss | -0.0069    |
|    std                  | 0.884      |
|    value_loss           | 0.037      |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 48          |
|    time_elapsed         | 212         |
|    total_timesteps      | 98304       |
| train/                  |             |
|    approx_kl            | 0.006415362 |
|    clip_fraction        | 0.067       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.88       |
|    explained_variance   | 0.303       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0119     |
|    n_updates            | 470         |
|    policy_gradient_loss | -0.00388    |
|    std                  | 0.882       |
|    value_loss           | 0.0244      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 49          |
|    time_elapsed         | 216         |
|    total_timesteps      | 100352      |
| train/                  |             |
|    approx_kl            | 0.007278253 |
|    clip_fraction        | 0.0874      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.87       |
|    explained_variance   | 0.24        |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0117     |
|    n_updates            | 480         |
|    policy_gradient_loss | -0.00707    |
|    std                  | 0.879       |
|    value_loss           | 0.0289      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 50          |
|    time_elapsed         | 221         |
|    total_timesteps      | 102400      |
| train/                  |             |
|    approx_kl            | 0.009548174 |
|    clip_fraction        | 0.0844      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.86       |
|    explained_variance   | 0.332       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00871    |
|    n_updates            | 490         |
|    policy_gradient_loss | -0.00636    |
|    std                  | 0.873       |
|    value_loss           | 0.0243      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 51           |
|    time_elapsed         | 225          |
|    total_timesteps      | 104448       |
| train/                  |              |
|    approx_kl            | 0.0054795668 |
|    clip_fraction        | 0.0457       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.84        |
|    explained_variance   | 0.226        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.026       |
|    n_updates            | 500          |
|    policy_gradient_loss | -0.00409     |
|    std                  | 0.87         |
|    value_loss           | 0.0169       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 52          |
|    time_elapsed         | 230         |
|    total_timesteps      | 106496      |
| train/                  |             |
|    approx_kl            | 0.009573554 |
|    clip_fraction        | 0.0823      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.82       |
|    explained_variance   | 0.21        |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00305    |
|    n_updates            | 510         |
|    policy_gradient_loss | -0.00507    |
|    std                  | 0.863       |
|    value_loss           | 0.033       |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 53          |
|    time_elapsed         | 235         |
|    total_timesteps      | 108544      |
| train/                  |             |
|    approx_kl            | 0.009252088 |
|    clip_fraction        | 0.0915      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.81       |
|    explained_variance   | 0.242       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00195     |
|    n_updates            | 520         |
|    policy_gradient_loss | -0.00629    |
|    std                  | 0.859       |
|    value_loss           | 0.0354      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 54          |
|    time_elapsed         | 239         |
|    total_timesteps      | 110592      |
| train/                  |             |
|    approx_kl            | 0.009226601 |
|    clip_fraction        | 0.078       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.79       |
|    explained_variance   | 0.147       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.021      |
|    n_updates            | 530         |
|    policy_gradient_loss | -0.00664    |
|    std                  | 0.854       |
|    value_loss           | 0.0313      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 55          |
|    time_elapsed         | 243         |
|    total_timesteps      | 112640      |
| train/                  |             |
|    approx_kl            | 0.008208159 |
|    clip_fraction        | 0.088       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.76       |
|    explained_variance   | 0.258       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0143     |
|    n_updates            | 540         |
|    policy_gradient_loss | -0.00869    |
|    std                  | 0.845       |
|    value_loss           | 0.0227      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 56          |
|    time_elapsed         | 248         |
|    total_timesteps      | 114688      |
| train/                  |             |
|    approx_kl            | 0.006320293 |
|    clip_fraction        | 0.0615      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.74       |
|    explained_variance   | 0.28        |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0195     |
|    n_updates            | 550         |
|    policy_gradient_loss | -0.00402    |
|    std                  | 0.841       |
|    value_loss           | 0.0157      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 57           |
|    time_elapsed         | 252          |
|    total_timesteps      | 116736       |
| train/                  |              |
|    approx_kl            | 0.0087536825 |
|    clip_fraction        | 0.0889       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.71        |
|    explained_variance   | 0.288        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0073      |
|    n_updates            | 560          |
|    policy_gradient_loss | -0.00809     |
|    std                  | 0.829        |
|    value_loss           | 0.0256       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 58           |
|    time_elapsed         | 256          |
|    total_timesteps      | 118784       |
| train/                  |              |
|    approx_kl            | 0.0077867494 |
|    clip_fraction        | 0.087        |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.69        |
|    explained_variance   | 0.287        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0132      |
|    n_updates            | 570          |
|    policy_gradient_loss | -0.00721     |
|    std                  | 0.828        |
|    value_loss           | 0.0235       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 59          |
|    time_elapsed         | 261         |
|    total_timesteps      | 120832      |
| train/                  |             |
|    approx_kl            | 0.007261561 |
|    clip_fraction        | 0.0748      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.68       |
|    explained_variance   | 0.286       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0118     |
|    n_updates            | 580         |
|    policy_gradient_loss | -0.00519    |
|    std                  | 0.823       |
|    value_loss           | 0.0291      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 60           |
|    time_elapsed         | 265          |
|    total_timesteps      | 122880       |
| train/                  |              |
|    approx_kl            | 0.0081130285 |
|    clip_fraction        | 0.0832       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.67        |
|    explained_variance   | 0.293        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0158      |
|    n_updates            | 590          |
|    policy_gradient_loss | -0.00692     |
|    std                  | 0.823        |
|    value_loss           | 0.03         |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 462        |
|    iterations           | 61         |
|    time_elapsed         | 270        |
|    total_timesteps      | 124928     |
| train/                  |            |
|    approx_kl            | 0.00621029 |
|    clip_fraction        | 0.0641     |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.66      |
|    explained_variance   | 0.316      |
|    learning_rate        | 0.0002     |
|    loss                 | -0.0342    |
|    n_updates            | 600        |
|    policy_gradient_loss | -0.00689   |
|    std                  | 0.818      |
|    value_loss           | 0.0271     |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 62          |
|    time_elapsed         | 274         |
|    total_timesteps      | 126976      |
| train/                  |             |
|    approx_kl            | 0.009669399 |
|    clip_fraction        | 0.1         |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.64       |
|    explained_variance   | 0.333       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00881    |
|    n_updates            | 610         |
|    policy_gradient_loss | -0.00741    |
|    std                  | 0.814       |
|    value_loss           | 0.0394      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 63          |
|    time_elapsed         | 279         |
|    total_timesteps      | 129024      |
| train/                  |             |
|    approx_kl            | 0.007489186 |
|    clip_fraction        | 0.0654      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.63       |
|    explained_variance   | 0.305       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0119     |
|    n_updates            | 620         |
|    policy_gradient_loss | -0.00493    |
|    std                  | 0.808       |
|    value_loss           | 0.0308      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 64           |
|    time_elapsed         | 283          |
|    total_timesteps      | 131072       |
| train/                  |              |
|    approx_kl            | 0.0071857194 |
|    clip_fraction        | 0.095        |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.61        |
|    explained_variance   | 0.325        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00786     |
|    n_updates            | 630          |
|    policy_gradient_loss | -0.00586     |
|    std                  | 0.805        |
|    value_loss           | 0.0308       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 461          |
|    iterations           | 65           |
|    time_elapsed         | 288          |
|    total_timesteps      | 133120       |
| train/                  |              |
|    approx_kl            | 0.0072228787 |
|    clip_fraction        | 0.0993       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.6         |
|    explained_variance   | 0.315        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0252      |
|    n_updates            | 640          |
|    policy_gradient_loss | -0.0075      |
|    std                  | 0.802        |
|    value_loss           | 0.0216       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 66           |
|    time_elapsed         | 292          |
|    total_timesteps      | 135168       |
| train/                  |              |
|    approx_kl            | 0.0070424257 |
|    clip_fraction        | 0.0794       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.59        |
|    explained_variance   | 0.327        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00699     |
|    n_updates            | 650          |
|    policy_gradient_loss | -0.00733     |
|    std                  | 0.798        |
|    value_loss           | 0.0186       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 67          |
|    time_elapsed         | 296         |
|    total_timesteps      | 137216      |
| train/                  |             |
|    approx_kl            | 0.007526364 |
|    clip_fraction        | 0.0723      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.57       |
|    explained_variance   | 0.328       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.000553    |
|    n_updates            | 660         |
|    policy_gradient_loss | -0.00549    |
|    std                  | 0.795       |
|    value_loss           | 0.0396      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 68          |
|    time_elapsed         | 301         |
|    total_timesteps      | 139264      |
| train/                  |             |
|    approx_kl            | 0.007515396 |
|    clip_fraction        | 0.0677      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.56       |
|    explained_variance   | 0.203       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0144     |
|    n_updates            | 670         |
|    policy_gradient_loss | -0.00578    |
|    std                  | 0.792       |
|    value_loss           | 0.0288      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 462        |
|    iterations           | 69         |
|    time_elapsed         | 305        |
|    total_timesteps      | 141312     |
| train/                  |            |
|    approx_kl            | 0.00600258 |
|    clip_fraction        | 0.0687     |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.54      |
|    explained_variance   | 0.236      |
|    learning_rate        | 0.0002     |
|    loss                 | -0.00934   |
|    n_updates            | 680        |
|    policy_gradient_loss | -0.00684   |
|    std                  | 0.785      |
|    value_loss           | 0.0309     |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 70           |
|    time_elapsed         | 310          |
|    total_timesteps      | 143360       |
| train/                  |              |
|    approx_kl            | 0.0068154857 |
|    clip_fraction        | 0.0889       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.52        |
|    explained_variance   | 0.278        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00395     |
|    n_updates            | 690          |
|    policy_gradient_loss | -0.00843     |
|    std                  | 0.781        |
|    value_loss           | 0.0232       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 71          |
|    time_elapsed         | 314         |
|    total_timesteps      | 145408      |
| train/                  |             |
|    approx_kl            | 0.008373557 |
|    clip_fraction        | 0.1         |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.51       |
|    explained_variance   | 0.236       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0205     |
|    n_updates            | 700         |
|    policy_gradient_loss | -0.00768    |
|    std                  | 0.782       |
|    value_loss           | 0.0322      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 72          |
|    time_elapsed         | 318         |
|    total_timesteps      | 147456      |
| train/                  |             |
|    approx_kl            | 0.008844693 |
|    clip_fraction        | 0.0742      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.51       |
|    explained_variance   | 0.267       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0002      |
|    n_updates            | 710         |
|    policy_gradient_loss | -0.00608    |
|    std                  | 0.779       |
|    value_loss           | 0.0281      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 73          |
|    time_elapsed         | 323         |
|    total_timesteps      | 149504      |
| train/                  |             |
|    approx_kl            | 0.006779246 |
|    clip_fraction        | 0.104       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.5        |
|    explained_variance   | 0.214       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0159     |
|    n_updates            | 720         |
|    policy_gradient_loss | -0.00894    |
|    std                  | 0.773       |
|    value_loss           | 0.0321      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 74          |
|    time_elapsed         | 327         |
|    total_timesteps      | 151552      |
| train/                  |             |
|    approx_kl            | 0.007847734 |
|    clip_fraction        | 0.0825      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.48       |
|    explained_variance   | 0.242       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0102     |
|    n_updates            | 730         |
|    policy_gradient_loss | -0.0058     |
|    std                  | 0.771       |
|    value_loss           | 0.0292      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 75           |
|    time_elapsed         | 331          |
|    total_timesteps      | 153600       |
| train/                  |              |
|    approx_kl            | 0.0074432367 |
|    clip_fraction        | 0.0792       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.47        |
|    explained_variance   | 0.3          |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0037      |
|    n_updates            | 740          |
|    policy_gradient_loss | -0.0061      |
|    std                  | 0.768        |
|    value_loss           | 0.0251       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 76          |
|    time_elapsed         | 336         |
|    total_timesteps      | 155648      |
| train/                  |             |
|    approx_kl            | 0.006391012 |
|    clip_fraction        | 0.0582      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.47       |
|    explained_variance   | 0.271       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0106      |
|    n_updates            | 750         |
|    policy_gradient_loss | -0.00421    |
|    std                  | 0.77        |
|    value_loss           | 0.0292      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 77           |
|    time_elapsed         | 340          |
|    total_timesteps      | 157696       |
| train/                  |              |
|    approx_kl            | 0.0073276674 |
|    clip_fraction        | 0.0854       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.47        |
|    explained_variance   | 0.3          |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0037      |
|    n_updates            | 760          |
|    policy_gradient_loss | -0.00587     |
|    std                  | 0.766        |
|    value_loss           | 0.0252       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 78          |
|    time_elapsed         | 345         |
|    total_timesteps      | 159744      |
| train/                  |             |
|    approx_kl            | 0.008375041 |
|    clip_fraction        | 0.0657      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.45       |
|    explained_variance   | 0.259       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00192     |
|    n_updates            | 770         |
|    policy_gradient_loss | -0.00592    |
|    std                  | 0.764       |
|    value_loss           | 0.0309      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 79           |
|    time_elapsed         | 350          |
|    total_timesteps      | 161792       |
| train/                  |              |
|    approx_kl            | 0.0061482545 |
|    clip_fraction        | 0.0709       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.43        |
|    explained_variance   | 0.262        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00889     |
|    n_updates            | 780          |
|    policy_gradient_loss | -0.0056      |
|    std                  | 0.757        |
|    value_loss           | 0.0247       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 80          |
|    time_elapsed         | 354         |
|    total_timesteps      | 163840      |
| train/                  |             |
|    approx_kl            | 0.010981508 |
|    clip_fraction        | 0.0884      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.42       |
|    explained_variance   | 0.303       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0061      |
|    n_updates            | 790         |
|    policy_gradient_loss | -0.00711    |
|    std                  | 0.757       |
|    value_loss           | 0.0314      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 81           |
|    time_elapsed         | 358          |
|    total_timesteps      | 165888       |
| train/                  |              |
|    approx_kl            | 0.0094047515 |
|    clip_fraction        | 0.0934       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.41        |
|    explained_variance   | 0.302        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00384     |
|    n_updates            | 800          |
|    policy_gradient_loss | -0.00624     |
|    std                  | 0.749        |
|    value_loss           | 0.0325       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 82          |
|    time_elapsed         | 363         |
|    total_timesteps      | 167936      |
| train/                  |             |
|    approx_kl            | 0.007374748 |
|    clip_fraction        | 0.0659      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.38       |
|    explained_variance   | 0.315       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0017      |
|    n_updates            | 810         |
|    policy_gradient_loss | -0.00695    |
|    std                  | 0.746       |
|    value_loss           | 0.0321      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 83          |
|    time_elapsed         | 367         |
|    total_timesteps      | 169984      |
| train/                  |             |
|    approx_kl            | 0.007232283 |
|    clip_fraction        | 0.0911      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.37       |
|    explained_variance   | 0.292       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00253    |
|    n_updates            | 820         |
|    policy_gradient_loss | -0.00503    |
|    std                  | 0.742       |
|    value_loss           | 0.0352      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 84           |
|    time_elapsed         | 371          |
|    total_timesteps      | 172032       |
| train/                  |              |
|    approx_kl            | 0.0058848085 |
|    clip_fraction        | 0.0725       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.35        |
|    explained_variance   | 0.327        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0144      |
|    n_updates            | 830          |
|    policy_gradient_loss | -0.00793     |
|    std                  | 0.737        |
|    value_loss           | 0.0274       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 85           |
|    time_elapsed         | 376          |
|    total_timesteps      | 174080       |
| train/                  |              |
|    approx_kl            | 0.0062835542 |
|    clip_fraction        | 0.0431       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.33        |
|    explained_variance   | 0.345        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00144     |
|    n_updates            | 840          |
|    policy_gradient_loss | -0.00265     |
|    std                  | 0.734        |
|    value_loss           | 0.0308       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 86          |
|    time_elapsed         | 380         |
|    total_timesteps      | 176128      |
| train/                  |             |
|    approx_kl            | 0.005873584 |
|    clip_fraction        | 0.0782      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.32       |
|    explained_variance   | 0.36        |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0131     |
|    n_updates            | 850         |
|    policy_gradient_loss | -0.00709    |
|    std                  | 0.731       |
|    value_loss           | 0.0384      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 87          |
|    time_elapsed         | 384         |
|    total_timesteps      | 178176      |
| train/                  |             |
|    approx_kl            | 0.005672647 |
|    clip_fraction        | 0.077       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.31       |
|    explained_variance   | 0.336       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0165      |
|    n_updates            | 860         |
|    policy_gradient_loss | -0.00484    |
|    std                  | 0.73        |
|    value_loss           | 0.0371      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 88           |
|    time_elapsed         | 389          |
|    total_timesteps      | 180224       |
| train/                  |              |
|    approx_kl            | 0.0071369605 |
|    clip_fraction        | 0.0576       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.3         |
|    explained_variance   | 0.34         |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00769     |
|    n_updates            | 870          |
|    policy_gradient_loss | -0.00394     |
|    std                  | 0.724        |
|    value_loss           | 0.0294       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 89           |
|    time_elapsed         | 393          |
|    total_timesteps      | 182272       |
| train/                  |              |
|    approx_kl            | 0.0050916257 |
|    clip_fraction        | 0.0816       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.28        |
|    explained_variance   | 0.283        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00711      |
|    n_updates            | 880          |
|    policy_gradient_loss | -0.00613     |
|    std                  | 0.72         |
|    value_loss           | 0.0362       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 463        |
|    iterations           | 90         |
|    time_elapsed         | 398        |
|    total_timesteps      | 184320     |
| train/                  |            |
|    approx_kl            | 0.00872061 |
|    clip_fraction        | 0.0833     |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.26      |
|    explained_variance   | 0.323      |
|    learning_rate        | 0.0002     |
|    loss                 | -0.00515   |
|    n_updates            | 890        |
|    policy_gradient_loss | -0.00717   |
|    std                  | 0.716      |
|    value_loss           | 0.028      |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 91          |
|    time_elapsed         | 402         |
|    total_timesteps      | 186368      |
| train/                  |             |
|    approx_kl            | 0.007872134 |
|    clip_fraction        | 0.0724      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.25       |
|    explained_variance   | 0.32        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00236     |
|    n_updates            | 900         |
|    policy_gradient_loss | -0.0055     |
|    std                  | 0.715       |
|    value_loss           | 0.0398      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 92          |
|    time_elapsed         | 406         |
|    total_timesteps      | 188416      |
| train/                  |             |
|    approx_kl            | 0.007871395 |
|    clip_fraction        | 0.0835      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.25       |
|    explained_variance   | 0.343       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00936    |
|    n_updates            | 910         |
|    policy_gradient_loss | -0.00608    |
|    std                  | 0.718       |
|    value_loss           | 0.0267      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 93          |
|    time_elapsed         | 411         |
|    total_timesteps      | 190464      |
| train/                  |             |
|    approx_kl            | 0.006542621 |
|    clip_fraction        | 0.0803      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.26       |
|    explained_variance   | 0.307       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0114     |
|    n_updates            | 920         |
|    policy_gradient_loss | -0.00643    |
|    std                  | 0.718       |
|    value_loss           | 0.0299      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 94          |
|    time_elapsed         | 416         |
|    total_timesteps      | 192512      |
| train/                  |             |
|    approx_kl            | 0.005966144 |
|    clip_fraction        | 0.0744      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.25       |
|    explained_variance   | 0.338       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0108     |
|    n_updates            | 930         |
|    policy_gradient_loss | -0.00608    |
|    std                  | 0.714       |
|    value_loss           | 0.0371      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 95          |
|    time_elapsed         | 420         |
|    total_timesteps      | 194560      |
| train/                  |             |
|    approx_kl            | 0.008596402 |
|    clip_fraction        | 0.075       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.23       |
|    explained_variance   | 0.354       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00967    |
|    n_updates            | 940         |
|    policy_gradient_loss | -0.00583    |
|    std                  | 0.71        |
|    value_loss           | 0.0271      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 96          |
|    time_elapsed         | 424         |
|    total_timesteps      | 196608      |
| train/                  |             |
|    approx_kl            | 0.010217497 |
|    clip_fraction        | 0.115       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.21       |
|    explained_variance   | 0.335       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00643     |
|    n_updates            | 950         |
|    policy_gradient_loss | -0.00852    |
|    std                  | 0.705       |
|    value_loss           | 0.0436      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 97          |
|    time_elapsed         | 429         |
|    total_timesteps      | 198656      |
| train/                  |             |
|    approx_kl            | 0.006358344 |
|    clip_fraction        | 0.0829      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.19       |
|    explained_variance   | 0.357       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0156      |
|    n_updates            | 960         |
|    policy_gradient_loss | -0.00531    |
|    std                  | 0.701       |
|    value_loss           | 0.0385      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 98           |
|    time_elapsed         | 433          |
|    total_timesteps      | 200704       |
| train/                  |              |
|    approx_kl            | 0.0059859846 |
|    clip_fraction        | 0.058        |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.19        |
|    explained_variance   | 0.332        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00394      |
|    n_updates            | 970          |
|    policy_gradient_loss | -0.00456     |
|    std                  | 0.702        |
|    value_loss           | 0.0338       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 99          |
|    time_elapsed         | 438         |
|    total_timesteps      | 202752      |
| train/                  |             |
|    approx_kl            | 0.006107436 |
|    clip_fraction        | 0.0658      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.19       |
|    explained_variance   | 0.314       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00277     |
|    n_updates            | 980         |
|    policy_gradient_loss | -0.00473    |
|    std                  | 0.7         |
|    value_loss           | 0.0371      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 100         |
|    time_elapsed         | 442         |
|    total_timesteps      | 204800      |
| train/                  |             |
|    approx_kl            | 0.007897848 |
|    clip_fraction        | 0.101       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.19       |
|    explained_variance   | 0.339       |
|    learning_rate        | 0.0002      |
|    loss                 | -8.98e-05   |
|    n_updates            | 990         |
|    policy_gradient_loss | -0.00583    |
|    std                  | 0.703       |
|    value_loss           | 0.0299      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 101          |
|    time_elapsed         | 446          |
|    total_timesteps      | 206848       |
| train/                  |              |
|    approx_kl            | 0.0083068935 |
|    clip_fraction        | 0.0976       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.2         |
|    explained_variance   | 0.368        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00179     |
|    n_updates            | 1000         |
|    policy_gradient_loss | -0.00605     |
|    std                  | 0.704        |
|    value_loss           | 0.0321       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 102         |
|    time_elapsed         | 451         |
|    total_timesteps      | 208896      |
| train/                  |             |
|    approx_kl            | 0.006859811 |
|    clip_fraction        | 0.0606      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.2        |
|    explained_variance   | 0.41        |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00807    |
|    n_updates            | 1010        |
|    policy_gradient_loss | -0.00534    |
|    std                  | 0.704       |
|    value_loss           | 0.0244      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 103         |
|    time_elapsed         | 456         |
|    total_timesteps      | 210944      |
| train/                  |             |
|    approx_kl            | 0.009073021 |
|    clip_fraction        | 0.091       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.2        |
|    explained_variance   | 0.322       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0134     |
|    n_updates            | 1020        |
|    policy_gradient_loss | -0.00745    |
|    std                  | 0.703       |
|    value_loss           | 0.0325      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 104          |
|    time_elapsed         | 460          |
|    total_timesteps      | 212992       |
| train/                  |              |
|    approx_kl            | 0.0059790313 |
|    clip_fraction        | 0.0715       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.19        |
|    explained_variance   | 0.362        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00477     |
|    n_updates            | 1030         |
|    policy_gradient_loss | -0.00447     |
|    std                  | 0.7          |
|    value_loss           | 0.0297       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 105         |
|    time_elapsed         | 465         |
|    total_timesteps      | 215040      |
| train/                  |             |
|    approx_kl            | 0.010690949 |
|    clip_fraction        | 0.118       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.18       |
|    explained_variance   | 0.36        |
|    learning_rate        | 0.0002      |
|    loss                 | 8.74e-05    |
|    n_updates            | 1040        |
|    policy_gradient_loss | -0.00815    |
|    std                  | 0.698       |
|    value_loss           | 0.0401      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 106         |
|    time_elapsed         | 469         |
|    total_timesteps      | 217088      |
| train/                  |             |
|    approx_kl            | 0.008001028 |
|    clip_fraction        | 0.102       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.16       |
|    explained_variance   | 0.374       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00162     |
|    n_updates            | 1050        |
|    policy_gradient_loss | -0.00536    |
|    std                  | 0.694       |
|    value_loss           | 0.0413      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 107         |
|    time_elapsed         | 473         |
|    total_timesteps      | 219136      |
| train/                  |             |
|    approx_kl            | 0.008014059 |
|    clip_fraction        | 0.0918      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.15       |
|    explained_variance   | 0.36        |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0347     |
|    n_updates            | 1060        |
|    policy_gradient_loss | -0.00656    |
|    std                  | 0.693       |
|    value_loss           | 0.0274      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 462        |
|    iterations           | 108        |
|    time_elapsed         | 478        |
|    total_timesteps      | 221184     |
| train/                  |            |
|    approx_kl            | 0.00895923 |
|    clip_fraction        | 0.0872     |
|    clip_range           | 0.2        |
|    entropy_loss         | -3.15      |
|    explained_variance   | 0.362      |
|    learning_rate        | 0.0002     |
|    loss                 | -0.00486   |
|    n_updates            | 1070       |
|    policy_gradient_loss | -0.0057    |
|    std                  | 0.691      |
|    value_loss           | 0.029      |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 109         |
|    time_elapsed         | 482         |
|    total_timesteps      | 223232      |
| train/                  |             |
|    approx_kl            | 0.009043526 |
|    clip_fraction        | 0.119       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.14       |
|    explained_variance   | 0.336       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00891     |
|    n_updates            | 1080        |
|    policy_gradient_loss | -0.00937    |
|    std                  | 0.689       |
|    value_loss           | 0.0332      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 463          |
|    iterations           | 110          |
|    time_elapsed         | 486          |
|    total_timesteps      | 225280       |
| train/                  |              |
|    approx_kl            | 0.0077875615 |
|    clip_fraction        | 0.107        |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.13        |
|    explained_variance   | 0.376        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0127      |
|    n_updates            | 1090         |
|    policy_gradient_loss | -0.00565     |
|    std                  | 0.687        |
|    value_loss           | 0.0339       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 111         |
|    time_elapsed         | 491         |
|    total_timesteps      | 227328      |
| train/                  |             |
|    approx_kl            | 0.009063294 |
|    clip_fraction        | 0.0995      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.12       |
|    explained_variance   | 0.371       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0254     |
|    n_updates            | 1100        |
|    policy_gradient_loss | -0.00726    |
|    std                  | 0.685       |
|    value_loss           | 0.0349      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 112         |
|    time_elapsed         | 495         |
|    total_timesteps      | 229376      |
| train/                  |             |
|    approx_kl            | 0.010143248 |
|    clip_fraction        | 0.122       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.11       |
|    explained_variance   | 0.353       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0127     |
|    n_updates            | 1110        |
|    policy_gradient_loss | -0.00904    |
|    std                  | 0.682       |
|    value_loss           | 0.0372      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 113         |
|    time_elapsed         | 499         |
|    total_timesteps      | 231424      |
| train/                  |             |
|    approx_kl            | 0.007064149 |
|    clip_fraction        | 0.065       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.09       |
|    explained_variance   | 0.393       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0104     |
|    n_updates            | 1120        |
|    policy_gradient_loss | -0.00517    |
|    std                  | 0.677       |
|    value_loss           | 0.027       |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 463          |
|    iterations           | 114          |
|    time_elapsed         | 504          |
|    total_timesteps      | 233472       |
| train/                  |              |
|    approx_kl            | 0.0075289393 |
|    clip_fraction        | 0.0919       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.08        |
|    explained_variance   | 0.337        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00768     |
|    n_updates            | 1130         |
|    policy_gradient_loss | -0.0056      |
|    std                  | 0.678        |
|    value_loss           | 0.0257       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 115         |
|    time_elapsed         | 508         |
|    total_timesteps      | 235520      |
| train/                  |             |
|    approx_kl            | 0.009001564 |
|    clip_fraction        | 0.11        |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.08       |
|    explained_variance   | 0.355       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.012      |
|    n_updates            | 1140        |
|    policy_gradient_loss | -0.00812    |
|    std                  | 0.674       |
|    value_loss           | 0.0321      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 116         |
|    time_elapsed         | 512         |
|    total_timesteps      | 237568      |
| train/                  |             |
|    approx_kl            | 0.006566571 |
|    clip_fraction        | 0.0781      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.07       |
|    explained_variance   | 0.317       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0175     |
|    n_updates            | 1150        |
|    policy_gradient_loss | -0.00471    |
|    std                  | 0.676       |
|    value_loss           | 0.0195      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 117         |
|    time_elapsed         | 517         |
|    total_timesteps      | 239616      |
| train/                  |             |
|    approx_kl            | 0.006892553 |
|    clip_fraction        | 0.0875      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.08       |
|    explained_variance   | 0.355       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.000989   |
|    n_updates            | 1160        |
|    policy_gradient_loss | -0.00679    |
|    std                  | 0.677       |
|    value_loss           | 0.0279      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 118         |
|    time_elapsed         | 521         |
|    total_timesteps      | 241664      |
| train/                  |             |
|    approx_kl            | 0.008806666 |
|    clip_fraction        | 0.0892      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.08       |
|    explained_variance   | 0.366       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0185     |
|    n_updates            | 1170        |
|    policy_gradient_loss | -0.00712    |
|    std                  | 0.674       |
|    value_loss           | 0.0261      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 463          |
|    iterations           | 119          |
|    time_elapsed         | 525          |
|    total_timesteps      | 243712       |
| train/                  |              |
|    approx_kl            | 0.0068951375 |
|    clip_fraction        | 0.0673       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.07        |
|    explained_variance   | 0.402        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0272      |
|    n_updates            | 1180         |
|    policy_gradient_loss | -0.00431     |
|    std                  | 0.674        |
|    value_loss           | 0.0251       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 120         |
|    time_elapsed         | 531         |
|    total_timesteps      | 245760      |
| train/                  |             |
|    approx_kl            | 0.008146303 |
|    clip_fraction        | 0.113       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.06       |
|    explained_variance   | 0.393       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.015       |
|    n_updates            | 1190        |
|    policy_gradient_loss | -0.0064     |
|    std                  | 0.672       |
|    value_loss           | 0.0371      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 463          |
|    iterations           | 121          |
|    time_elapsed         | 535          |
|    total_timesteps      | 247808       |
| train/                  |              |
|    approx_kl            | 0.0070845657 |
|    clip_fraction        | 0.0901       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.06        |
|    explained_variance   | 0.333        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0233      |
|    n_updates            | 1200         |
|    policy_gradient_loss | -0.00618     |
|    std                  | 0.673        |
|    value_loss           | 0.0244       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 122         |
|    time_elapsed         | 539         |
|    total_timesteps      | 249856      |
| train/                  |             |
|    approx_kl            | 0.009951186 |
|    clip_fraction        | 0.0672      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.06       |
|    explained_variance   | 0.348       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00332     |
|    n_updates            | 1210        |
|    policy_gradient_loss | -0.00394    |
|    std                  | 0.673       |
|    value_loss           | 0.0337      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 123         |
|    time_elapsed         | 544         |
|    total_timesteps      | 251904      |
| train/                  |             |
|    approx_kl            | 0.009130755 |
|    clip_fraction        | 0.117       |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.07       |
|    explained_variance   | 0.314       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00885    |
|    n_updates            | 1220        |
|    policy_gradient_loss | -0.00672    |
|    std                  | 0.674       |
|    value_loss           | 0.0299      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 124         |
|    time_elapsed         | 548         |
|    total_timesteps      | 253952      |
| train/                  |             |
|    approx_kl            | 0.008029151 |
|    clip_fraction        | 0.0955      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.06       |
|    explained_variance   | 0.373       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0169     |
|    n_updates            | 1230        |
|    policy_gradient_loss | -0.0079     |
|    std                  | 0.671       |
|    value_loss           | 0.0272      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 125         |
|    time_elapsed         | 552         |
|    total_timesteps      | 256000      |
| train/                  |             |
|    approx_kl            | 0.008486549 |
|    clip_fraction        | 0.0601      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.04       |
|    explained_variance   | 0.422       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00634    |
|    n_updates            | 1240        |
|    policy_gradient_loss | -0.00446    |
|    std                  | 0.666       |
|    value_loss           | 0.0324      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 126          |
|    time_elapsed         | 557          |
|    total_timesteps      | 258048       |
| train/                  |              |
|    approx_kl            | 0.0060635665 |
|    clip_fraction        | 0.0624       |
|    clip_range           | 0.2          |
|    entropy_loss         | -3.03        |
|    explained_variance   | 0.336        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00205     |
|    n_updates            | 1250         |
|    policy_gradient_loss | -0.00349     |
|    std                  | 0.664        |
|    value_loss           | 0.0246       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 127         |
|    time_elapsed         | 561         |
|    total_timesteps      | 260096      |
| train/                  |             |
|    approx_kl            | 0.006515212 |
|    clip_fraction        | 0.0825      |
|    clip_range           | 0.2         |
|    entropy_loss         | -3.01       |
|    explained_variance   | 0.379       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00741    |
|    n_updates            | 1260        |
|    policy_gradient_loss | -0.00416    |
|    std                  | 0.66        |
|    value_loss           | 0.0353      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 128         |
|    time_elapsed         | 565         |
|    total_timesteps      | 262144      |
| train/                  |             |
|    approx_kl            | 0.009437136 |
|    clip_fraction        | 0.107       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.99       |
|    explained_variance   | 0.38        |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0133     |
|    n_updates            | 1270        |
|    policy_gradient_loss | -0.00951    |
|    std                  | 0.655       |
|    value_loss           | 0.0315      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 129          |
|    time_elapsed         | 570          |
|    total_timesteps      | 264192       |
| train/                  |              |
|    approx_kl            | 0.0075229197 |
|    clip_fraction        | 0.0819       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.98        |
|    explained_variance   | 0.399        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00811     |
|    n_updates            | 1280         |
|    policy_gradient_loss | -0.00437     |
|    std                  | 0.652        |
|    value_loss           | 0.0295       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 130         |
|    time_elapsed         | 574         |
|    total_timesteps      | 266240      |
| train/                  |             |
|    approx_kl            | 0.008725807 |
|    clip_fraction        | 0.0885      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.96       |
|    explained_variance   | 0.42        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00552     |
|    n_updates            | 1290        |
|    policy_gradient_loss | -0.00575    |
|    std                  | 0.649       |
|    value_loss           | 0.0369      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 463          |
|    iterations           | 131          |
|    time_elapsed         | 579          |
|    total_timesteps      | 268288       |
| train/                  |              |
|    approx_kl            | 0.0075822813 |
|    clip_fraction        | 0.0905       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.95        |
|    explained_variance   | 0.396        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00672     |
|    n_updates            | 1300         |
|    policy_gradient_loss | -0.00724     |
|    std                  | 0.648        |
|    value_loss           | 0.0329       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 132          |
|    time_elapsed         | 583          |
|    total_timesteps      | 270336       |
| train/                  |              |
|    approx_kl            | 0.0059551466 |
|    clip_fraction        | 0.0657       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.95        |
|    explained_variance   | 0.37         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00208      |
|    n_updates            | 1310         |
|    policy_gradient_loss | -0.00448     |
|    std                  | 0.647        |
|    value_loss           | 0.0392       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 133         |
|    time_elapsed         | 588         |
|    total_timesteps      | 272384      |
| train/                  |             |
|    approx_kl            | 0.010360798 |
|    clip_fraction        | 0.0961      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.94       |
|    explained_variance   | 0.339       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0149     |
|    n_updates            | 1320        |
|    policy_gradient_loss | -0.00718    |
|    std                  | 0.645       |
|    value_loss           | 0.0405      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 134         |
|    time_elapsed         | 592         |
|    total_timesteps      | 274432      |
| train/                  |             |
|    approx_kl            | 0.005997106 |
|    clip_fraction        | 0.0677      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.94       |
|    explained_variance   | 0.392       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.000651    |
|    n_updates            | 1330        |
|    policy_gradient_loss | -0.00478    |
|    std                  | 0.644       |
|    value_loss           | 0.0366      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 135         |
|    time_elapsed         | 597         |
|    total_timesteps      | 276480      |
| train/                  |             |
|    approx_kl            | 0.008703932 |
|    clip_fraction        | 0.0943      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.93       |
|    explained_variance   | 0.397       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00777    |
|    n_updates            | 1340        |
|    policy_gradient_loss | -0.00781    |
|    std                  | 0.643       |
|    value_loss           | 0.0507      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 463          |
|    iterations           | 136          |
|    time_elapsed         | 601          |
|    total_timesteps      | 278528       |
| train/                  |              |
|    approx_kl            | 0.0073208436 |
|    clip_fraction        | 0.0945       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.92        |
|    explained_variance   | 0.382        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00288     |
|    n_updates            | 1350         |
|    policy_gradient_loss | -0.00783     |
|    std                  | 0.641        |
|    value_loss           | 0.0329       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 137         |
|    time_elapsed         | 606         |
|    total_timesteps      | 280576      |
| train/                  |             |
|    approx_kl            | 0.008706969 |
|    clip_fraction        | 0.0933      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.92       |
|    explained_variance   | 0.401       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0147      |
|    n_updates            | 1360        |
|    policy_gradient_loss | -0.00713    |
|    std                  | 0.641       |
|    value_loss           | 0.0436      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 138          |
|    time_elapsed         | 610          |
|    total_timesteps      | 282624       |
| train/                  |              |
|    approx_kl            | 0.0075739897 |
|    clip_fraction        | 0.0733       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.91        |
|    explained_variance   | 0.389        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00244     |
|    n_updates            | 1370         |
|    policy_gradient_loss | -0.0037      |
|    std                  | 0.639        |
|    value_loss           | 0.0383       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 139         |
|    time_elapsed         | 614         |
|    total_timesteps      | 284672      |
| train/                  |             |
|    approx_kl            | 0.008854349 |
|    clip_fraction        | 0.096       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.89       |
|    explained_variance   | 0.404       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0123     |
|    n_updates            | 1380        |
|    policy_gradient_loss | -0.00676    |
|    std                  | 0.633       |
|    value_loss           | 0.0359      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 140          |
|    time_elapsed         | 619          |
|    total_timesteps      | 286720       |
| train/                  |              |
|    approx_kl            | 0.0058001494 |
|    clip_fraction        | 0.0781       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.88        |
|    explained_variance   | 0.417        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00143      |
|    n_updates            | 1390         |
|    policy_gradient_loss | -0.00265     |
|    std                  | 0.632        |
|    value_loss           | 0.0536       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 141         |
|    time_elapsed         | 623         |
|    total_timesteps      | 288768      |
| train/                  |             |
|    approx_kl            | 0.008674683 |
|    clip_fraction        | 0.107       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.86       |
|    explained_variance   | 0.404       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0106     |
|    n_updates            | 1400        |
|    policy_gradient_loss | -0.00654    |
|    std                  | 0.627       |
|    value_loss           | 0.0367      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 463          |
|    iterations           | 142          |
|    time_elapsed         | 628          |
|    total_timesteps      | 290816       |
| train/                  |              |
|    approx_kl            | 0.0072314576 |
|    clip_fraction        | 0.063        |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.85        |
|    explained_variance   | 0.396        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00577      |
|    n_updates            | 1410         |
|    policy_gradient_loss | -0.0046      |
|    std                  | 0.626        |
|    value_loss           | 0.0364       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 143         |
|    time_elapsed         | 632         |
|    total_timesteps      | 292864      |
| train/                  |             |
|    approx_kl            | 0.008945905 |
|    clip_fraction        | 0.102       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.85       |
|    explained_variance   | 0.4         |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00434     |
|    n_updates            | 1420        |
|    policy_gradient_loss | -0.00711    |
|    std                  | 0.627       |
|    value_loss           | 0.0377      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 144         |
|    time_elapsed         | 637         |
|    total_timesteps      | 294912      |
| train/                  |             |
|    approx_kl            | 0.005522054 |
|    clip_fraction        | 0.0733      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.85       |
|    explained_variance   | 0.414       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.000204    |
|    n_updates            | 1430        |
|    policy_gradient_loss | -0.00506    |
|    std                  | 0.625       |
|    value_loss           | 0.0499      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 145         |
|    time_elapsed         | 641         |
|    total_timesteps      | 296960      |
| train/                  |             |
|    approx_kl            | 0.007401023 |
|    clip_fraction        | 0.0933      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.83       |
|    explained_variance   | 0.419       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0188     |
|    n_updates            | 1440        |
|    policy_gradient_loss | -0.0048     |
|    std                  | 0.621       |
|    value_loss           | 0.0508      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 146         |
|    time_elapsed         | 646         |
|    total_timesteps      | 299008      |
| train/                  |             |
|    approx_kl            | 0.010742171 |
|    clip_fraction        | 0.094       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.82       |
|    explained_variance   | 0.379       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.000243   |
|    n_updates            | 1450        |
|    policy_gradient_loss | -0.00729    |
|    std                  | 0.621       |
|    value_loss           | 0.0415      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 147          |
|    time_elapsed         | 650          |
|    total_timesteps      | 301056       |
| train/                  |              |
|    approx_kl            | 0.0077775586 |
|    clip_fraction        | 0.121        |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.82        |
|    explained_variance   | 0.39         |
|    learning_rate        | 0.0002       |
|    loss                 | -0.021       |
|    n_updates            | 1460         |
|    policy_gradient_loss | -0.00758     |
|    std                  | 0.619        |
|    value_loss           | 0.0446       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 148          |
|    time_elapsed         | 654          |
|    total_timesteps      | 303104       |
| train/                  |              |
|    approx_kl            | 0.0077385986 |
|    clip_fraction        | 0.0826       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.8         |
|    explained_variance   | 0.417        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.000575     |
|    n_updates            | 1470         |
|    policy_gradient_loss | -0.00525     |
|    std                  | 0.615        |
|    value_loss           | 0.0396       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 149          |
|    time_elapsed         | 659          |
|    total_timesteps      | 305152       |
| train/                  |              |
|    approx_kl            | 0.0067563355 |
|    clip_fraction        | 0.0646       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.8         |
|    explained_variance   | 0.429        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00625      |
|    n_updates            | 1480         |
|    policy_gradient_loss | -0.00499     |
|    std                  | 0.616        |
|    value_loss           | 0.0482       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 150         |
|    time_elapsed         | 663         |
|    total_timesteps      | 307200      |
| train/                  |             |
|    approx_kl            | 0.007866566 |
|    clip_fraction        | 0.101       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.79       |
|    explained_variance   | 0.422       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0206      |
|    n_updates            | 1490        |
|    policy_gradient_loss | -0.00719    |
|    std                  | 0.611       |
|    value_loss           | 0.0459      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 151         |
|    time_elapsed         | 668         |
|    total_timesteps      | 309248      |
| train/                  |             |
|    approx_kl            | 0.010881231 |
|    clip_fraction        | 0.1         |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.77       |
|    explained_variance   | 0.392       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0139     |
|    n_updates            | 1500        |
|    policy_gradient_loss | -0.00834    |
|    std                  | 0.608       |
|    value_loss           | 0.0421      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 152         |
|    time_elapsed         | 673         |
|    total_timesteps      | 311296      |
| train/                  |             |
|    approx_kl            | 0.006112148 |
|    clip_fraction        | 0.0527      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.76       |
|    explained_variance   | 0.392       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00955     |
|    n_updates            | 1510        |
|    policy_gradient_loss | -0.00266    |
|    std                  | 0.607       |
|    value_loss           | 0.0434      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 153         |
|    time_elapsed         | 677         |
|    total_timesteps      | 313344      |
| train/                  |             |
|    approx_kl            | 0.008411404 |
|    clip_fraction        | 0.106       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.75       |
|    explained_variance   | 0.401       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00859     |
|    n_updates            | 1520        |
|    policy_gradient_loss | -0.00618    |
|    std                  | 0.604       |
|    value_loss           | 0.0399      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 154         |
|    time_elapsed         | 681         |
|    total_timesteps      | 315392      |
| train/                  |             |
|    approx_kl            | 0.004172708 |
|    clip_fraction        | 0.0618      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.73       |
|    explained_variance   | 0.43        |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0201     |
|    n_updates            | 1530        |
|    policy_gradient_loss | -0.00367    |
|    std                  | 0.6         |
|    value_loss           | 0.0438      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 155         |
|    time_elapsed         | 686         |
|    total_timesteps      | 317440      |
| train/                  |             |
|    approx_kl            | 0.008377376 |
|    clip_fraction        | 0.0931      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.71       |
|    explained_variance   | 0.429       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.000588   |
|    n_updates            | 1540        |
|    policy_gradient_loss | -0.00672    |
|    std                  | 0.598       |
|    value_loss           | 0.0412      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 156         |
|    time_elapsed         | 690         |
|    total_timesteps      | 319488      |
| train/                  |             |
|    approx_kl            | 0.009420024 |
|    clip_fraction        | 0.0878      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.7        |
|    explained_variance   | 0.416       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0164     |
|    n_updates            | 1550        |
|    policy_gradient_loss | -0.0062     |
|    std                  | 0.595       |
|    value_loss           | 0.0357      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 157          |
|    time_elapsed         | 694          |
|    total_timesteps      | 321536       |
| train/                  |              |
|    approx_kl            | 0.0075310674 |
|    clip_fraction        | 0.0842       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.69        |
|    explained_variance   | 0.408        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00727     |
|    n_updates            | 1560         |
|    policy_gradient_loss | -0.00537     |
|    std                  | 0.593        |
|    value_loss           | 0.0472       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 158         |
|    time_elapsed         | 699         |
|    total_timesteps      | 323584      |
| train/                  |             |
|    approx_kl            | 0.006364229 |
|    clip_fraction        | 0.0849      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.68       |
|    explained_variance   | 0.412       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.011      |
|    n_updates            | 1570        |
|    policy_gradient_loss | -0.00504    |
|    std                  | 0.591       |
|    value_loss           | 0.0305      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 159         |
|    time_elapsed         | 703         |
|    total_timesteps      | 325632      |
| train/                  |             |
|    approx_kl            | 0.009881207 |
|    clip_fraction        | 0.112       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.67       |
|    explained_variance   | 0.455       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0243      |
|    n_updates            | 1580        |
|    policy_gradient_loss | -0.00607    |
|    std                  | 0.591       |
|    value_loss           | 0.0527      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 160         |
|    time_elapsed         | 708         |
|    total_timesteps      | 327680      |
| train/                  |             |
|    approx_kl            | 0.007973704 |
|    clip_fraction        | 0.0935      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.67       |
|    explained_variance   | 0.451       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00931     |
|    n_updates            | 1590        |
|    policy_gradient_loss | -0.00483    |
|    std                  | 0.589       |
|    value_loss           | 0.0412      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 161          |
|    time_elapsed         | 712          |
|    total_timesteps      | 329728       |
| train/                  |              |
|    approx_kl            | 0.0075983233 |
|    clip_fraction        | 0.101        |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.66        |
|    explained_variance   | 0.452        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0121      |
|    n_updates            | 1600         |
|    policy_gradient_loss | -0.00685     |
|    std                  | 0.589        |
|    value_loss           | 0.0349       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 162          |
|    time_elapsed         | 717          |
|    total_timesteps      | 331776       |
| train/                  |              |
|    approx_kl            | 0.0049532712 |
|    clip_fraction        | 0.0926       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.66        |
|    explained_variance   | 0.421        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00187      |
|    n_updates            | 1610         |
|    policy_gradient_loss | -0.00633     |
|    std                  | 0.587        |
|    value_loss           | 0.0418       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 163          |
|    time_elapsed         | 721          |
|    total_timesteps      | 333824       |
| train/                  |              |
|    approx_kl            | 0.0067570275 |
|    clip_fraction        | 0.0605       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.65        |
|    explained_variance   | 0.447        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00676      |
|    n_updates            | 1620         |
|    policy_gradient_loss | -0.00441     |
|    std                  | 0.588        |
|    value_loss           | 0.0404       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 164          |
|    time_elapsed         | 726          |
|    total_timesteps      | 335872       |
| train/                  |              |
|    approx_kl            | 0.0066395616 |
|    clip_fraction        | 0.0897       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.65        |
|    explained_variance   | 0.492        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0055       |
|    n_updates            | 1630         |
|    policy_gradient_loss | -0.00461     |
|    std                  | 0.586        |
|    value_loss           | 0.0438       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 165         |
|    time_elapsed         | 730         |
|    total_timesteps      | 337920      |
| train/                  |             |
|    approx_kl            | 0.008594355 |
|    clip_fraction        | 0.0969      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.65       |
|    explained_variance   | 0.463       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0211      |
|    n_updates            | 1640        |
|    policy_gradient_loss | -0.00611    |
|    std                  | 0.588       |
|    value_loss           | 0.0402      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 166         |
|    time_elapsed         | 735         |
|    total_timesteps      | 339968      |
| train/                  |             |
|    approx_kl            | 0.004868934 |
|    clip_fraction        | 0.0682      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.66       |
|    explained_variance   | 0.461       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00967     |
|    n_updates            | 1650        |
|    policy_gradient_loss | -0.00315    |
|    std                  | 0.588       |
|    value_loss           | 0.0411      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 167         |
|    time_elapsed         | 739         |
|    total_timesteps      | 342016      |
| train/                  |             |
|    approx_kl            | 0.010707539 |
|    clip_fraction        | 0.107       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.65       |
|    explained_variance   | 0.417       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0109      |
|    n_updates            | 1660        |
|    policy_gradient_loss | -0.00699    |
|    std                  | 0.588       |
|    value_loss           | 0.0409      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 168         |
|    time_elapsed         | 744         |
|    total_timesteps      | 344064      |
| train/                  |             |
|    approx_kl            | 0.007324811 |
|    clip_fraction        | 0.0787      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.66       |
|    explained_variance   | 0.468       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0138     |
|    n_updates            | 1670        |
|    policy_gradient_loss | -0.00451    |
|    std                  | 0.59        |
|    value_loss           | 0.0382      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 169         |
|    time_elapsed         | 748         |
|    total_timesteps      | 346112      |
| train/                  |             |
|    approx_kl            | 0.008938112 |
|    clip_fraction        | 0.11        |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.67       |
|    explained_variance   | 0.463       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0075      |
|    n_updates            | 1680        |
|    policy_gradient_loss | -0.00636    |
|    std                  | 0.592       |
|    value_loss           | 0.047       |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 170          |
|    time_elapsed         | 753          |
|    total_timesteps      | 348160       |
| train/                  |              |
|    approx_kl            | 0.0061715213 |
|    clip_fraction        | 0.0885       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.68        |
|    explained_variance   | 0.441        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0108       |
|    n_updates            | 1690         |
|    policy_gradient_loss | -0.00511     |
|    std                  | 0.592        |
|    value_loss           | 0.0386       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 171         |
|    time_elapsed         | 757         |
|    total_timesteps      | 350208      |
| train/                  |             |
|    approx_kl            | 0.007430825 |
|    clip_fraction        | 0.0998      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.68       |
|    explained_variance   | 0.435       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00877     |
|    n_updates            | 1700        |
|    policy_gradient_loss | -0.00603    |
|    std                  | 0.592       |
|    value_loss           | 0.0402      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 172         |
|    time_elapsed         | 762         |
|    total_timesteps      | 352256      |
| train/                  |             |
|    approx_kl            | 0.007497434 |
|    clip_fraction        | 0.0718      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.67       |
|    explained_variance   | 0.451       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00493     |
|    n_updates            | 1710        |
|    policy_gradient_loss | -0.00297    |
|    std                  | 0.59        |
|    value_loss           | 0.0364      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 173          |
|    time_elapsed         | 766          |
|    total_timesteps      | 354304       |
| train/                  |              |
|    approx_kl            | 0.0076568797 |
|    clip_fraction        | 0.12         |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.66        |
|    explained_variance   | 0.452        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.0129      |
|    n_updates            | 1720         |
|    policy_gradient_loss | -0.00903     |
|    std                  | 0.588        |
|    value_loss           | 0.0381       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 174         |
|    time_elapsed         | 770         |
|    total_timesteps      | 356352      |
| train/                  |             |
|    approx_kl            | 0.007272329 |
|    clip_fraction        | 0.103       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.65       |
|    explained_variance   | 0.495       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0184     |
|    n_updates            | 1730        |
|    policy_gradient_loss | -0.00644    |
|    std                  | 0.587       |
|    value_loss           | 0.0502      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 175         |
|    time_elapsed         | 775         |
|    total_timesteps      | 358400      |
| train/                  |             |
|    approx_kl            | 0.009503387 |
|    clip_fraction        | 0.111       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.64       |
|    explained_variance   | 0.434       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0107     |
|    n_updates            | 1740        |
|    policy_gradient_loss | -0.009      |
|    std                  | 0.583       |
|    value_loss           | 0.0395      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 176          |
|    time_elapsed         | 779          |
|    total_timesteps      | 360448       |
| train/                  |              |
|    approx_kl            | 0.0072898734 |
|    clip_fraction        | 0.0745       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.63        |
|    explained_variance   | 0.417        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00162      |
|    n_updates            | 1750         |
|    policy_gradient_loss | -0.00554     |
|    std                  | 0.584        |
|    value_loss           | 0.0401       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 177          |
|    time_elapsed         | 783          |
|    total_timesteps      | 362496       |
| train/                  |              |
|    approx_kl            | 0.0053452738 |
|    clip_fraction        | 0.07         |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.64        |
|    explained_variance   | 0.451        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00851      |
|    n_updates            | 1760         |
|    policy_gradient_loss | -0.00366     |
|    std                  | 0.586        |
|    value_loss           | 0.0335       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 462        |
|    iterations           | 178        |
|    time_elapsed         | 788        |
|    total_timesteps      | 364544     |
| train/                  |            |
|    approx_kl            | 0.01050759 |
|    clip_fraction        | 0.107      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.64      |
|    explained_variance   | 0.471      |
|    learning_rate        | 0.0002     |
|    loss                 | -0.0149    |
|    n_updates            | 1770       |
|    policy_gradient_loss | -0.00525   |
|    std                  | 0.585      |
|    value_loss           | 0.0364     |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 179         |
|    time_elapsed         | 792         |
|    total_timesteps      | 366592      |
| train/                  |             |
|    approx_kl            | 0.007665738 |
|    clip_fraction        | 0.0957      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.64       |
|    explained_variance   | 0.52        |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0129     |
|    n_updates            | 1780        |
|    policy_gradient_loss | -0.00457    |
|    std                  | 0.584       |
|    value_loss           | 0.0395      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 180         |
|    time_elapsed         | 796         |
|    total_timesteps      | 368640      |
| train/                  |             |
|    approx_kl            | 0.010276221 |
|    clip_fraction        | 0.112       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.63       |
|    explained_variance   | 0.464       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0109     |
|    n_updates            | 1790        |
|    policy_gradient_loss | -0.00624    |
|    std                  | 0.582       |
|    value_loss           | 0.0419      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 181         |
|    time_elapsed         | 801         |
|    total_timesteps      | 370688      |
| train/                  |             |
|    approx_kl            | 0.011488119 |
|    clip_fraction        | 0.115       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | 0.456       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00231     |
|    n_updates            | 1800        |
|    policy_gradient_loss | -0.00689    |
|    std                  | 0.579       |
|    value_loss           | 0.0401      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 182         |
|    time_elapsed         | 805         |
|    total_timesteps      | 372736      |
| train/                  |             |
|    approx_kl            | 0.008816556 |
|    clip_fraction        | 0.122       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | 0.442       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0179     |
|    n_updates            | 1810        |
|    policy_gradient_loss | -0.0105     |
|    std                  | 0.582       |
|    value_loss           | 0.0388      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 183         |
|    time_elapsed         | 809         |
|    total_timesteps      | 374784      |
| train/                  |             |
|    approx_kl            | 0.007393833 |
|    clip_fraction        | 0.0827      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | 0.486       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00362    |
|    n_updates            | 1820        |
|    policy_gradient_loss | -0.00537    |
|    std                  | 0.58        |
|    value_loss           | 0.045       |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 184         |
|    time_elapsed         | 814         |
|    total_timesteps      | 376832      |
| train/                  |             |
|    approx_kl            | 0.006767323 |
|    clip_fraction        | 0.0755      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.62       |
|    explained_variance   | 0.486       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00641    |
|    n_updates            | 1830        |
|    policy_gradient_loss | -0.00239    |
|    std                  | 0.58        |
|    value_loss           | 0.0427      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 185         |
|    time_elapsed         | 818         |
|    total_timesteps      | 378880      |
| train/                  |             |
|    approx_kl            | 0.007900346 |
|    clip_fraction        | 0.0688      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.6        |
|    explained_variance   | 0.445       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00151     |
|    n_updates            | 1840        |
|    policy_gradient_loss | -0.0037     |
|    std                  | 0.575       |
|    value_loss           | 0.0407      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 462          |
|    iterations           | 186          |
|    time_elapsed         | 822          |
|    total_timesteps      | 380928       |
| train/                  |              |
|    approx_kl            | 0.0072840303 |
|    clip_fraction        | 0.0864       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.58        |
|    explained_variance   | 0.427        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00271      |
|    n_updates            | 1850         |
|    policy_gradient_loss | -0.00493     |
|    std                  | 0.572        |
|    value_loss           | 0.0421       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 187         |
|    time_elapsed         | 827         |
|    total_timesteps      | 382976      |
| train/                  |             |
|    approx_kl            | 0.007592912 |
|    clip_fraction        | 0.0928      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.57       |
|    explained_variance   | 0.455       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00414     |
|    n_updates            | 1860        |
|    policy_gradient_loss | -0.00496    |
|    std                  | 0.57        |
|    value_loss           | 0.0383      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 188         |
|    time_elapsed         | 831         |
|    total_timesteps      | 385024      |
| train/                  |             |
|    approx_kl            | 0.009406977 |
|    clip_fraction        | 0.0793      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.55       |
|    explained_variance   | 0.503       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0159     |
|    n_updates            | 1870        |
|    policy_gradient_loss | -0.00505    |
|    std                  | 0.566       |
|    value_loss           | 0.0436      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 463         |
|    iterations           | 189         |
|    time_elapsed         | 835         |
|    total_timesteps      | 387072      |
| train/                  |             |
|    approx_kl            | 0.009215672 |
|    clip_fraction        | 0.084       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.54       |
|    explained_variance   | 0.493       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00302     |
|    n_updates            | 1880        |
|    policy_gradient_loss | -0.00333    |
|    std                  | 0.566       |
|    value_loss           | 0.0453      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 190         |
|    time_elapsed         | 841         |
|    total_timesteps      | 389120      |
| train/                  |             |
|    approx_kl            | 0.007807158 |
|    clip_fraction        | 0.0867      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.54       |
|    explained_variance   | 0.475       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0127     |
|    n_updates            | 1890        |
|    policy_gradient_loss | -0.00644    |
|    std                  | 0.564       |
|    value_loss           | 0.0425      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 462         |
|    iterations           | 191         |
|    time_elapsed         | 845         |
|    total_timesteps      | 391168      |
| train/                  |             |
|    approx_kl            | 0.007134615 |
|    clip_fraction        | 0.0882      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.53       |
|    explained_variance   | 0.459       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0153      |
|    n_updates            | 1900        |
|    policy_gradient_loss | -0.00446    |
|    std                  | 0.563       |
|    value_loss           | 0.0423      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 462        |
|    iterations           | 192        |
|    time_elapsed         | 849        |
|    total_timesteps      | 393216     |
| train/                  |            |
|    approx_kl            | 0.00826326 |
|    clip_fraction        | 0.114      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.52      |
|    explained_variance   | 0.457      |
|    learning_rate        | 0.0002     |
|    loss                 | 0.0145     |
|    n_updates            | 1910       |
|    policy_gradient_loss | -0.00715   |
|    std                  | 0.562      |
|    value_loss           | 0.038      |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 193         |
|    time_elapsed         | 856         |
|    total_timesteps      | 395264      |
| train/                  |             |
|    approx_kl            | 0.007029783 |
|    clip_fraction        | 0.0954      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.52       |
|    explained_variance   | 0.492       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0131     |
|    n_updates            | 1920        |
|    policy_gradient_loss | -0.00416    |
|    std                  | 0.563       |
|    value_loss           | 0.0477      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 194         |
|    time_elapsed         | 860         |
|    total_timesteps      | 397312      |
| train/                  |             |
|    approx_kl            | 0.009711241 |
|    clip_fraction        | 0.0988      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.52       |
|    explained_variance   | 0.468       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00358     |
|    n_updates            | 1930        |
|    policy_gradient_loss | -0.00464    |
|    std                  | 0.561       |
|    value_loss           | 0.0415      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 461          |
|    iterations           | 195          |
|    time_elapsed         | 865          |
|    total_timesteps      | 399360       |
| train/                  |              |
|    approx_kl            | 0.0095323445 |
|    clip_fraction        | 0.107        |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.51        |
|    explained_variance   | 0.474        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.01         |
|    n_updates            | 1940         |
|    policy_gradient_loss | -0.00768     |
|    std                  | 0.561        |
|    value_loss           | 0.0421       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 461        |
|    iterations           | 196        |
|    time_elapsed         | 869        |
|    total_timesteps      | 401408     |
| train/                  |            |
|    approx_kl            | 0.00898722 |
|    clip_fraction        | 0.109      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.51      |
|    explained_variance   | 0.464      |
|    learning_rate        | 0.0002     |
|    loss                 | -0.0119    |
|    n_updates            | 1950       |
|    policy_gradient_loss | -0.00672   |
|    std                  | 0.561      |
|    value_loss           | 0.0414     |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 197         |
|    time_elapsed         | 873         |
|    total_timesteps      | 403456      |
| train/                  |             |
|    approx_kl            | 0.009202933 |
|    clip_fraction        | 0.113       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.51       |
|    explained_variance   | 0.484       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0154      |
|    n_updates            | 1960        |
|    policy_gradient_loss | -0.00843    |
|    std                  | 0.561       |
|    value_loss           | 0.0397      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 461          |
|    iterations           | 198          |
|    time_elapsed         | 878          |
|    total_timesteps      | 405504       |
| train/                  |              |
|    approx_kl            | 0.0088114515 |
|    clip_fraction        | 0.104        |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.51        |
|    explained_variance   | 0.512        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.000718     |
|    n_updates            | 1970         |
|    policy_gradient_loss | -0.00743     |
|    std                  | 0.56         |
|    value_loss           | 0.0588       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 199         |
|    time_elapsed         | 882         |
|    total_timesteps      | 407552      |
| train/                  |             |
|    approx_kl            | 0.008598635 |
|    clip_fraction        | 0.105       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.5        |
|    explained_variance   | 0.46        |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00156    |
|    n_updates            | 1980        |
|    policy_gradient_loss | -0.00497    |
|    std                  | 0.559       |
|    value_loss           | 0.0408      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 200         |
|    time_elapsed         | 887         |
|    total_timesteps      | 409600      |
| train/                  |             |
|    approx_kl            | 0.008239639 |
|    clip_fraction        | 0.0845      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.49       |
|    explained_variance   | 0.495       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00507     |
|    n_updates            | 1990        |
|    policy_gradient_loss | -0.00523    |
|    std                  | 0.555       |
|    value_loss           | 0.0436      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 461          |
|    iterations           | 201          |
|    time_elapsed         | 891          |
|    total_timesteps      | 411648       |
| train/                  |              |
|    approx_kl            | 0.0090117995 |
|    clip_fraction        | 0.0977       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.48        |
|    explained_variance   | 0.481        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00376      |
|    n_updates            | 2000         |
|    policy_gradient_loss | -0.00478     |
|    std                  | 0.556        |
|    value_loss           | 0.0451       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 202         |
|    time_elapsed         | 896         |
|    total_timesteps      | 413696      |
| train/                  |             |
|    approx_kl            | 0.008914184 |
|    clip_fraction        | 0.0865      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.49       |
|    explained_variance   | 0.493       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0258     |
|    n_updates            | 2010        |
|    policy_gradient_loss | -0.00703    |
|    std                  | 0.559       |
|    value_loss           | 0.0379      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 461          |
|    iterations           | 203          |
|    time_elapsed         | 900          |
|    total_timesteps      | 415744       |
| train/                  |              |
|    approx_kl            | 0.0101688905 |
|    clip_fraction        | 0.106        |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.51        |
|    explained_variance   | 0.513        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0158       |
|    n_updates            | 2020         |
|    policy_gradient_loss | -0.00582     |
|    std                  | 0.561        |
|    value_loss           | 0.0557       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 204         |
|    time_elapsed         | 905         |
|    total_timesteps      | 417792      |
| train/                  |             |
|    approx_kl            | 0.007726747 |
|    clip_fraction        | 0.0934      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.53       |
|    explained_variance   | 0.487       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0035     |
|    n_updates            | 2030        |
|    policy_gradient_loss | -0.00626    |
|    std                  | 0.565       |
|    value_loss           | 0.0423      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 461          |
|    iterations           | 205          |
|    time_elapsed         | 909          |
|    total_timesteps      | 419840       |
| train/                  |              |
|    approx_kl            | 0.0060343295 |
|    clip_fraction        | 0.0795       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.53        |
|    explained_variance   | 0.484        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00756      |
|    n_updates            | 2040         |
|    policy_gradient_loss | -0.00411     |
|    std                  | 0.562        |
|    value_loss           | 0.0413       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 206         |
|    time_elapsed         | 913         |
|    total_timesteps      | 421888      |
| train/                  |             |
|    approx_kl            | 0.007405633 |
|    clip_fraction        | 0.0899      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.52       |
|    explained_variance   | 0.49        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00501     |
|    n_updates            | 2050        |
|    policy_gradient_loss | -0.00486    |
|    std                  | 0.561       |
|    value_loss           | 0.0419      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 207         |
|    time_elapsed         | 918         |
|    total_timesteps      | 423936      |
| train/                  |             |
|    approx_kl            | 0.010620028 |
|    clip_fraction        | 0.123       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.51       |
|    explained_variance   | 0.486       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00626    |
|    n_updates            | 2060        |
|    policy_gradient_loss | -0.00855    |
|    std                  | 0.558       |
|    value_loss           | 0.0384      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 208         |
|    time_elapsed         | 922         |
|    total_timesteps      | 425984      |
| train/                  |             |
|    approx_kl            | 0.008084398 |
|    clip_fraction        | 0.0812      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.5        |
|    explained_variance   | 0.536       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00485     |
|    n_updates            | 2070        |
|    policy_gradient_loss | -0.00423    |
|    std                  | 0.557       |
|    value_loss           | 0.0476      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 209         |
|    time_elapsed         | 926         |
|    total_timesteps      | 428032      |
| train/                  |             |
|    approx_kl            | 0.007502267 |
|    clip_fraction        | 0.104       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.49       |
|    explained_variance   | 0.49        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0212      |
|    n_updates            | 2080        |
|    policy_gradient_loss | -0.00796    |
|    std                  | 0.556       |
|    value_loss           | 0.0448      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 210         |
|    time_elapsed         | 931         |
|    total_timesteps      | 430080      |
| train/                  |             |
|    approx_kl            | 0.009295376 |
|    clip_fraction        | 0.1         |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.49       |
|    explained_variance   | 0.485       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0244      |
|    n_updates            | 2090        |
|    policy_gradient_loss | -0.00753    |
|    std                  | 0.557       |
|    value_loss           | 0.0457      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 211         |
|    time_elapsed         | 935         |
|    total_timesteps      | 432128      |
| train/                  |             |
|    approx_kl            | 0.010067118 |
|    clip_fraction        | 0.117       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.49       |
|    explained_variance   | 0.49        |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00108    |
|    n_updates            | 2100        |
|    policy_gradient_loss | -0.00771    |
|    std                  | 0.555       |
|    value_loss           | 0.0432      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 461          |
|    iterations           | 212          |
|    time_elapsed         | 941          |
|    total_timesteps      | 434176       |
| train/                  |              |
|    approx_kl            | 0.0063425014 |
|    clip_fraction        | 0.0783       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.48        |
|    explained_variance   | 0.487        |
|    learning_rate        | 0.0002       |
|    loss                 | -0.00617     |
|    n_updates            | 2110         |
|    policy_gradient_loss | -0.00393     |
|    std                  | 0.553        |
|    value_loss           | 0.0382       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 213         |
|    time_elapsed         | 945         |
|    total_timesteps      | 436224      |
| train/                  |             |
|    approx_kl            | 0.010543311 |
|    clip_fraction        | 0.1         |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.47       |
|    explained_variance   | 0.533       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0121      |
|    n_updates            | 2120        |
|    policy_gradient_loss | -0.00486    |
|    std                  | 0.551       |
|    value_loss           | 0.0499      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 461          |
|    iterations           | 214          |
|    time_elapsed         | 949          |
|    total_timesteps      | 438272       |
| train/                  |              |
|    approx_kl            | 0.0061283167 |
|    clip_fraction        | 0.0898       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.46        |
|    explained_variance   | 0.478        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0114       |
|    n_updates            | 2130         |
|    policy_gradient_loss | -0.00518     |
|    std                  | 0.551        |
|    value_loss           | 0.0462       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 461          |
|    iterations           | 215          |
|    time_elapsed         | 954          |
|    total_timesteps      | 440320       |
| train/                  |              |
|    approx_kl            | 0.0085187815 |
|    clip_fraction        | 0.0953       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.46        |
|    explained_variance   | 0.49         |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0135       |
|    n_updates            | 2140         |
|    policy_gradient_loss | -0.00431     |
|    std                  | 0.55         |
|    value_loss           | 0.0423       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 216         |
|    time_elapsed         | 959         |
|    total_timesteps      | 442368      |
| train/                  |             |
|    approx_kl            | 0.009839289 |
|    clip_fraction        | 0.115       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.46       |
|    explained_variance   | 0.493       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00218    |
|    n_updates            | 2150        |
|    policy_gradient_loss | -0.00644    |
|    std                  | 0.55        |
|    value_loss           | 0.0387      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 217         |
|    time_elapsed         | 963         |
|    total_timesteps      | 444416      |
| train/                  |             |
|    approx_kl            | 0.009421034 |
|    clip_fraction        | 0.0997      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.45       |
|    explained_variance   | 0.549       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00696     |
|    n_updates            | 2160        |
|    policy_gradient_loss | -0.00597    |
|    std                  | 0.548       |
|    value_loss           | 0.0453      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 218         |
|    time_elapsed         | 968         |
|    total_timesteps      | 446464      |
| train/                  |             |
|    approx_kl            | 0.005878089 |
|    clip_fraction        | 0.0771      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.45       |
|    explained_variance   | 0.526       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00268     |
|    n_updates            | 2170        |
|    policy_gradient_loss | -0.0048     |
|    std                  | 0.548       |
|    value_loss           | 0.0469      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 219         |
|    time_elapsed         | 972         |
|    total_timesteps      | 448512      |
| train/                  |             |
|    approx_kl            | 0.009029209 |
|    clip_fraction        | 0.0917      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.44       |
|    explained_variance   | 0.493       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0223      |
|    n_updates            | 2180        |
|    policy_gradient_loss | -0.00649    |
|    std                  | 0.547       |
|    value_loss           | 0.0391      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 220         |
|    time_elapsed         | 976         |
|    total_timesteps      | 450560      |
| train/                  |             |
|    approx_kl            | 0.007455844 |
|    clip_fraction        | 0.0745      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.44       |
|    explained_variance   | 0.505       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0113     |
|    n_updates            | 2190        |
|    policy_gradient_loss | -0.00382    |
|    std                  | 0.546       |
|    value_loss           | 0.0385      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 221         |
|    time_elapsed         | 981         |
|    total_timesteps      | 452608      |
| train/                  |             |
|    approx_kl            | 0.007763327 |
|    clip_fraction        | 0.0935      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.43       |
|    explained_variance   | 0.508       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.000307   |
|    n_updates            | 2200        |
|    policy_gradient_loss | -0.00538    |
|    std                  | 0.546       |
|    value_loss           | 0.0386      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 222         |
|    time_elapsed         | 985         |
|    total_timesteps      | 454656      |
| train/                  |             |
|    approx_kl            | 0.011055218 |
|    clip_fraction        | 0.119       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.43       |
|    explained_variance   | 0.538       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0125     |
|    n_updates            | 2210        |
|    policy_gradient_loss | -0.00888    |
|    std                  | 0.544       |
|    value_loss           | 0.0438      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 223         |
|    time_elapsed         | 989         |
|    total_timesteps      | 456704      |
| train/                  |             |
|    approx_kl            | 0.010788379 |
|    clip_fraction        | 0.101       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.43       |
|    explained_variance   | 0.517       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0113      |
|    n_updates            | 2220        |
|    policy_gradient_loss | -0.00482    |
|    std                  | 0.546       |
|    value_loss           | 0.0443      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 224         |
|    time_elapsed         | 994         |
|    total_timesteps      | 458752      |
| train/                  |             |
|    approx_kl            | 0.010149054 |
|    clip_fraction        | 0.123       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.43       |
|    explained_variance   | 0.522       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00716    |
|    n_updates            | 2230        |
|    policy_gradient_loss | -0.0075     |
|    std                  | 0.545       |
|    value_loss           | 0.0378      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 225         |
|    time_elapsed         | 998         |
|    total_timesteps      | 460800      |
| train/                  |             |
|    approx_kl            | 0.008543504 |
|    clip_fraction        | 0.103       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.43       |
|    explained_variance   | 0.474       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00199     |
|    n_updates            | 2240        |
|    policy_gradient_loss | -0.00708    |
|    std                  | 0.545       |
|    value_loss           | 0.04        |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 226         |
|    time_elapsed         | 1002        |
|    total_timesteps      | 462848      |
| train/                  |             |
|    approx_kl            | 0.013453513 |
|    clip_fraction        | 0.0971      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.43       |
|    explained_variance   | 0.494       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00486    |
|    n_updates            | 2250        |
|    policy_gradient_loss | -0.0048     |
|    std                  | 0.543       |
|    value_loss           | 0.033       |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 227         |
|    time_elapsed         | 1007        |
|    total_timesteps      | 464896      |
| train/                  |             |
|    approx_kl            | 0.011018461 |
|    clip_fraction        | 0.113       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.41       |
|    explained_variance   | 0.55        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00246     |
|    n_updates            | 2260        |
|    policy_gradient_loss | -0.00653    |
|    std                  | 0.541       |
|    value_loss           | 0.0419      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 228         |
|    time_elapsed         | 1011        |
|    total_timesteps      | 466944      |
| train/                  |             |
|    approx_kl            | 0.007162839 |
|    clip_fraction        | 0.0941      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.41       |
|    explained_variance   | 0.517       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0145     |
|    n_updates            | 2270        |
|    policy_gradient_loss | -0.00563    |
|    std                  | 0.541       |
|    value_loss           | 0.0428      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 461        |
|    iterations           | 229        |
|    time_elapsed         | 1015       |
|    total_timesteps      | 468992     |
| train/                  |            |
|    approx_kl            | 0.00866014 |
|    clip_fraction        | 0.0873     |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.42      |
|    explained_variance   | 0.504      |
|    learning_rate        | 0.0002     |
|    loss                 | -0.0028    |
|    n_updates            | 2280       |
|    policy_gradient_loss | -0.0057    |
|    std                  | 0.545      |
|    value_loss           | 0.0402     |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 230         |
|    time_elapsed         | 1020        |
|    total_timesteps      | 471040      |
| train/                  |             |
|    approx_kl            | 0.011520278 |
|    clip_fraction        | 0.133       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.44       |
|    explained_variance   | 0.508       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00804    |
|    n_updates            | 2290        |
|    policy_gradient_loss | -0.00824    |
|    std                  | 0.548       |
|    value_loss           | 0.0386      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 231         |
|    time_elapsed         | 1025        |
|    total_timesteps      | 473088      |
| train/                  |             |
|    approx_kl            | 0.009656093 |
|    clip_fraction        | 0.0932      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.44       |
|    explained_variance   | 0.53        |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0136      |
|    n_updates            | 2300        |
|    policy_gradient_loss | -0.0053     |
|    std                  | 0.546       |
|    value_loss           | 0.0327      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 232         |
|    time_elapsed         | 1029        |
|    total_timesteps      | 475136      |
| train/                  |             |
|    approx_kl            | 0.008734077 |
|    clip_fraction        | 0.102       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.43       |
|    explained_variance   | 0.559       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0183      |
|    n_updates            | 2310        |
|    policy_gradient_loss | -0.00689    |
|    std                  | 0.545       |
|    value_loss           | 0.0509      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 233         |
|    time_elapsed         | 1034        |
|    total_timesteps      | 477184      |
| train/                  |             |
|    approx_kl            | 0.010880625 |
|    clip_fraction        | 0.103       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.42       |
|    explained_variance   | 0.493       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0027      |
|    n_updates            | 2320        |
|    policy_gradient_loss | -0.00679    |
|    std                  | 0.543       |
|    value_loss           | 0.04        |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 461          |
|    iterations           | 234          |
|    time_elapsed         | 1038         |
|    total_timesteps      | 479232       |
| train/                  |              |
|    approx_kl            | 0.0074352445 |
|    clip_fraction        | 0.0664       |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.42        |
|    explained_variance   | 0.515        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.00997      |
|    n_updates            | 2330         |
|    policy_gradient_loss | -0.00437     |
|    std                  | 0.544        |
|    value_loss           | 0.0422       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 235         |
|    time_elapsed         | 1042        |
|    total_timesteps      | 481280      |
| train/                  |             |
|    approx_kl            | 0.008066437 |
|    clip_fraction        | 0.106       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.41       |
|    explained_variance   | 0.506       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.00144    |
|    n_updates            | 2340        |
|    policy_gradient_loss | -0.0064     |
|    std                  | 0.54        |
|    value_loss           | 0.0414      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 236         |
|    time_elapsed         | 1047        |
|    total_timesteps      | 483328      |
| train/                  |             |
|    approx_kl            | 0.011215511 |
|    clip_fraction        | 0.142       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.4        |
|    explained_variance   | 0.533       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0196     |
|    n_updates            | 2350        |
|    policy_gradient_loss | -0.0101     |
|    std                  | 0.539       |
|    value_loss           | 0.0389      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 237         |
|    time_elapsed         | 1051        |
|    total_timesteps      | 485376      |
| train/                  |             |
|    approx_kl            | 0.009230709 |
|    clip_fraction        | 0.106       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.4        |
|    explained_variance   | 0.564       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0174      |
|    n_updates            | 2360        |
|    policy_gradient_loss | -0.0086     |
|    std                  | 0.538       |
|    value_loss           | 0.0513      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 238         |
|    time_elapsed         | 1056        |
|    total_timesteps      | 487424      |
| train/                  |             |
|    approx_kl            | 0.007382705 |
|    clip_fraction        | 0.087       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.39       |
|    explained_variance   | 0.456       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0126      |
|    n_updates            | 2370        |
|    policy_gradient_loss | -0.00419    |
|    std                  | 0.537       |
|    value_loss           | 0.0379      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

------------------------------------------
| time/                   |              |
|    fps                  | 461          |
|    iterations           | 239          |
|    time_elapsed         | 1060         |
|    total_timesteps      | 489472       |
| train/                  |              |
|    approx_kl            | 0.0075522717 |
|    clip_fraction        | 0.1          |
|    clip_range           | 0.2          |
|    entropy_loss         | -2.39        |
|    explained_variance   | 0.517        |
|    learning_rate        | 0.0002       |
|    loss                 | 0.0156       |
|    n_updates            | 2380         |
|    policy_gradient_loss | -0.00498     |
|    std                  | 0.538        |
|    value_loss           | 0.0414       |
------------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 240         |
|    time_elapsed         | 1065        |
|    total_timesteps      | 491520      |
| train/                  |             |
|    approx_kl            | 0.009049982 |
|    clip_fraction        | 0.0962      |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.39       |
|    explained_variance   | 0.489       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.00497     |
|    n_updates            | 2390        |
|    policy_gradient_loss | -0.00567    |
|    std                  | 0.536       |
|    value_loss           | 0.0324      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 241         |
|    time_elapsed         | 1069        |
|    total_timesteps      | 493568      |
| train/                  |             |
|    approx_kl            | 0.011898914 |
|    clip_fraction        | 0.117       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.38       |
|    explained_variance   | 0.533       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.0091     |
|    n_updates            | 2400        |
|    policy_gradient_loss | -0.00852    |
|    std                  | 0.536       |
|    value_loss           | 0.0356      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 242         |
|    time_elapsed         | 1074        |
|    total_timesteps      | 495616      |
| train/                  |             |
|    approx_kl            | 0.011133414 |
|    clip_fraction        | 0.107       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.38       |
|    explained_variance   | 0.545       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0204      |
|    n_updates            | 2410        |
|    policy_gradient_loss | -0.00558    |
|    std                  | 0.536       |
|    value_loss           | 0.0459      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 243         |
|    time_elapsed         | 1078        |
|    total_timesteps      | 497664      |
| train/                  |             |
|    approx_kl            | 0.009128077 |
|    clip_fraction        | 0.108       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.38       |
|    explained_variance   | 0.541       |
|    learning_rate        | 0.0002      |
|    loss                 | 0.0105      |
|    n_updates            | 2420        |
|    policy_gradient_loss | -0.0069     |
|    std                  | 0.535       |
|    value_loss           | 0.0363      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

----------------------------------------
| time/                   |            |
|    fps                  | 461        |
|    iterations           | 244        |
|    time_elapsed         | 1083       |
|    total_timesteps      | 499712     |
| train/                  |            |
|    approx_kl            | 0.00810975 |
|    clip_fraction        | 0.093      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.37      |
|    explained_variance   | 0.531      |
|    learning_rate        | 0.0002     |
|    loss                 | 0.00279    |
|    n_updates            | 2430       |
|    policy_gradient_loss | -0.00499   |
|    std                  | 0.532      |
|    value_loss           | 0.0404     |
----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-----------------------------------------
| time/                   |             |
|    fps                  | 461         |
|    iterations           | 245         |
|    time_elapsed         | 1087        |
|    total_timesteps      | 501760      |
| train/                  |             |
|    approx_kl            | 0.011365718 |
|    clip_fraction        | 0.124       |
|    clip_range           | 0.2         |
|    entropy_loss         | -2.35       |
|    explained_variance   | 0.538       |
|    learning_rate        | 0.0002      |
|    loss                 | -0.000953   |
|    n_updates            | 2440        |
|    policy_gradient_loss | -0.00752    |
|    std                  | 0.531       |
|    value_loss           | 0.0411      |
-----------------------------------------

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Saved model: model/saved/ppo_model_basket.zip

dict_keys(['pair_0050_2330', 'basket_0050_2330_2412'])

## 9. Export Models to ONNX

This section exports the trained PPO models to the ONNX format, allowing them to be used in other environments or with ONNX runtime for deployment.

In [33]:
import torch # Ensure torch is imported for ONNX export
import torch.nn as nn # For the wrapper

for config in CONFIGS_TO_TRAIN:
    model = trained_models[config.name]

    # Re-create the environment to get the observation space shape
    # This is necessary because the model object itself doesn't directly expose env.observation_space
    # but we need it for the input_shape of ONNX export.
    feature_df = feature_data[config.name]
    env = TWTradingEnv(
        feature_df=feature_df,
        config=config,
        initial_balance=INITIAL_BALANCE,
    )
    # The input shape for ONNX export needs to be a tuple (batch_size, obs_dim).
    # Since the model expects a single observation at a time for inference, batch_size is 1.
    input_shape = (1, env.observation_space.shape[0])

    # Define the ONNX output path
    onnx_path = config.model_path.replace('.zip', '.onnx')
    ensure_model_dir(onnx_path)

    print(f"\nExporting {config.name} to ONNX: {onnx_path}")

    # Create a dummy input tensor for ONNX export
    # Ensure it's on the correct device (CPU or CUDA, as determined by DEVICE global)
    dummy_input = torch.randn(input_shape).to(DEVICE)

    # Set the model to evaluation mode
    model.policy.eval()

    # Define a wrapper module to expose only the deterministic prediction
    class SB3PolicyPredictor(nn.Module):
        def __init__(self, policy_module):
            super().__init__()
            # Extract the relevant sub-modules for deterministic action prediction
            self.features_extractor = policy_module.features_extractor
            self.mlp_extractor = policy_module.mlp_extractor
            self.action_net = policy_module.action_net

        def forward(self, obs: torch.Tensor) -> torch.Tensor:
            # Manually trace the deterministic action prediction path
            # 1. Extract features from observation
            features = self.features_extractor(obs)
            # 2. Pass features through the actor's MLP to get latent_pi
            latent_pi = self.mlp_extractor.forward_actor(features)
            # 3. Get the mean actions from the action network
            mean_actions = self.action_net(latent_pi)
            return mean_actions

    # Create an instance of our wrapper
    predictor = SB3PolicyPredictor(model.policy)

    input_names = ['obs']
    # Our wrapper only outputs the 'action'
    output_names = ['action']

    try:
        torch.onnx.export(
            predictor, # Export the wrapper module
            dummy_input,
            onnx_path,
            verbose=True, # Set to True for more detailed output during export
            input_names=input_names,
            output_names=output_names,
            opset_version=18, # Use opset_version 18
            dynamic_shapes={ # Specify dynamic batch size only for the input 'obs'
                'obs': {0: 'batch_size'}
            }
        )
        print(f"Successfully exported {config.name} model to {onnx_path}")
    except Exception as e:
        print(f"Error exporting {config.name} model to ONNX: {e}")

Exporting pair_0050_2330 to ONNX: model/saved/ppo_model_pair.onnx

/tmp/ipykernel_5874/2966189933.py:60: UserWarning: Exporting a model while it is in training mode. Please ensure that this is intended, as it may lead to different behavior during inference. Calling model.eval() before export is recommended.
  torch.onnx.export(

[torch.onnx] Obtain model graph for `SB3PolicyPredictor([...]` with `torch.export.export(..., strict=False)`...
[torch.onnx] Obtain model graph for `SB3PolicyPredictor([...]` with `torch.export.export(..., strict=False)`... ✅
[torch.onnx] Run decompositions...

/usr/lib/python3.12/copyreg.py:99: FutureWarning: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
  return cls.__new__(cls, *args)
/tmp/ipykernel_5874/2966189933.py:60: UserWarning: Exporting a model while it is in training mode. Please ensure that this is intended, as it may lead to different behavior during inference. Calling model.eval() before export is recommended.
  torch.onnx.export(

[torch.onnx] Run decompositions... ✅
[torch.onnx] Translate the graph into ONNX...
[torch.onnx] Translate the graph into ONNX... ✅
[torch.onnx] Optimize the ONNX graph...
[torch.onnx] Optimize the ONNX graph... ✅
Successfully exported pair_0050_2330 model to model/saved/ppo_model_pair.onnx

Exporting basket_0050_2330_2412 to ONNX: model/saved/ppo_model_basket.onnx

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

[torch.onnx] Obtain model graph for `SB3PolicyPredictor([...]` with `torch.export.export(..., strict=False)`...
[torch.onnx] Obtain model graph for `SB3PolicyPredictor([...]` with `torch.export.export(..., strict=False)`... ✅
[torch.onnx] Run decompositions...
[torch.onnx] Run decompositions... ✅
[torch.onnx] Translate the graph into ONNX...
[torch.onnx] Translate the graph into ONNX... ✅
[torch.onnx] Optimize the ONNX graph...
[torch.onnx] Optimize the ONNX graph... ✅
Successfully exported basket_0050_2330_2412 model to model/saved/ppo_model_basket.onnx

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/lib/python3.12/copyreg.py:99: FutureWarning: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
  return cls.__new__(cls, *args)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

## 10. Load ONNX Model and Perform Inference

This section loads the exported ONNX model and uses it to perform inference on the last 20% of the data, simulating trading and evaluating performance.

In [34]:
# Install onnxruntime if not already installed
%pip install -q onnxruntime

In [35]:
import onnxruntime as ort

# Define the configuration for the model we want to test
# Assuming '0050' refers to the PAIR_CONFIG model
config_to_test = PAIR_CONFIG

# Define the ONNX path
onnx_model_path = config_to_test.model_path.replace('.zip', '.onnx')

# Load the ONNX model
print(f"Loading ONNX model from: {onnx_model_path}")

try:
    # Create an ONNX Runtime session
    # Run on CPU as DEVICE is 'cpu'
    ort_session = ort.InferenceSession(onnx_model_path, providers=['CPUExecutionProvider'])
    print("ONNX model loaded successfully.")
except Exception as e:
    print(f"Error loading ONNX model: {e}")
    ort_session = None

if ort_session:
    # Prepare the data for inference (last 20% of the feature data)
    feature_df = feature_data[config_to_test.name]
    total_rows = len(feature_df)
    inference_start_index = int(total_rows * 0.8)
    inference_df = feature_df.iloc[inference_start_index:].reset_index(drop=True)

    print(f"\nPrepared inference data from index {inference_start_index} (last 20%): {len(inference_df)} rows")

    # Create a new environment for inference
    eval_env = TWTradingEnv(
        feature_df=inference_df,
        config=config_to_test,
        initial_balance=INITIAL_BALANCE,
    )

    obs, _ = eval_env.reset()
    done = False
    episode_reward = 0
    inference_history = []

    print("\nStarting inference...")
    while not done:
        # Convert observation to float32 and add batch dimension (1, obs_dim)
        obs_tensor = np.array(obs, dtype=np.float32).reshape(1, -1)

        # Get model outputs from ONNX runtime
        # The input name is 'obs' as defined during export
        # The output names are 'action', 'value', 'log_prob'
        ort_inputs = {ort_session.get_inputs()[0].name: obs_tensor}
        ort_outputs = ort_session.run(None, ort_inputs)

        # Extract action from the outputs. It's the first output.
        action = ort_outputs[0][0] # Assuming action is the first output and we need the first item in batch

        obs, reward, terminated, truncated, info = eval_env.step(action)
        done = terminated or truncated
        episode_reward += reward

        # Collect history for analysis
        inference_history.append(eval_env.history[-1])

    print("Inference completed.")
    print(f"Total reward: {episode_reward}")

    # Analyze results
    inference_history_df = pd.DataFrame(inference_history)
    metrics = calculate_metrics(inference_history_df, INITIAL_BALANCE)

    print("\nInference Performance Metrics:")
    for key, value in metrics.items():
        print(f"  {key}: {value:.4f}")

    print("\nInference History (first 5 rows):")
    display(inference_history_df.head())

    print("\nInference History (last 5 rows):")
    display(inference_history_df.tail())

Loading ONNX model from: model/saved/ppo_model_pair.onnx
ONNX model loaded successfully.

Prepared inference data from index 1360 (last 20%): 340 rows

Starting inference...

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Inference completed.
Total reward: 1.1526766350108977

Inference Performance Metrics:
  cumulative_return: 0.5291
  sharpe_ratio: 1.3210
  max_drawdown: -0.2402

Inference History (first 5 rows):

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,date,raw_action,net_worth,pnl,pnl_rate,transaction_cost,drawdown,reward,failed_orders,raw_action_0050.TW,weight_0050.TW,weight_2330.TW
0,2023-08-10,0.836580,999320.488155,-679.511845,-0.000680,679.511845,0.000680,-2.718047e-03,0,0.836580,0.795291,0.0
1,2023-08-11,1.161151,998559.526194,-760.961961,-0.000761,132.213100,0.001440,-1.654227e-03,0,1.161151,0.950126,0.0
2,2023-08-14,1.188992,985037.553336,-13521.972858,-0.013541,0.470654,0.014962,-2.704442e-02,0,1.188992,0.950000,0.0
3,2023-08-15,1.142877,986540.661022,1503.107686,0.001526,0.140256,0.013459,-1.423861e-07,0,1.142877,0.950000,0.0
4,2023-08-16,1.122733,981655.261922,-4885.399100,-0.004952,0.208728,0.018345,-9.771010e-03,0,1.122733,0.950000,0.0

Inference History (last 5 rows):

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,date,raw_action,net_worth,pnl,pnl_rate,transaction_cost,drawdown,reward,failed_orders,raw_action_0050.TW,weight_0050.TW,weight_2330.TW
334,2024-12-23,-2.289973,1.515723e+06,60111.571858,4.129644e-02,11.596047,0.131792,3.543928e-02,0,-2.289973,0.0,0.950007
335,2024-12-24,-2.291606,1.515723e+06,-0.042468,-2.801806e-08,0.042468,0.131792,-1.310567e-07,0,-2.291606,0.0,0.950000
336,2024-12-25,-2.317322,1.522388e+06,6665.089715,4.397300e-03,1.285099,0.127975,1.132450e-02,0,-2.317322,0.0,0.950001
337,2024-12-26,-2.313890,1.522388e+06,-0.004706,-3.091429e-09,0.004706,0.127975,-1.656378e-08,0,-2.313890,0.0,0.950000
338,2024-12-27,-2.329868,1.529052e+06,6663.548307,4.377036e-03,1.284664,0.124158,1.211418e-02,0,-2.329868,0.0,0.950001

### Install missing ONNX dependencies

In [21]:
%pip install -q onnxscript

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 714.8/714.8 kB 21.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 57.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.8/166.8 kB 14.5 MB/s eta 0:00:00